<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'message', language 'el', branch 'MOODLE_36_STABLE'
 *
 * @package   message
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['acceptandaddcontact'] = 'Αποδοχή και προσθήκη στις επαφές';
$string['addcontact'] = 'Προσθήκη επαφής';
$string['addcontactconfirm'] = 'Είστε βέβαιοι ότι θέλετε να προσθέσετε τον/την {$a} στις επαφές σας;';
$string['addtofavourites'] = 'Επισήμανση συνομιλίας με αστερίσκο';
$string['addtoyourcontacts'] = 'Προσθήκη στις επαφές';
$string['addtoyourcontactsandmessage'] = 'Προσθήκη στις επαφές και στο μήνυμα';
$string['ago'] = 'πριν {$a}';
$string['allusers'] = 'Όλα τα μηνύματα από όλους τους χρήστες';
$string['backto'] = 'Πίσω στο {$a}';
$string['backupmessageshelp'] = 'Εάν ενεργοποιηθεί, τότε τα άμεσα μηνύματα θα συμπεριληφθούν στα αυτόματα αντίγραφα ασφαλείας του ιστοτόπου.';
$string['blockcontact'] = 'Φραγμός επαφής';
$string['blockedusers'] = 'Αποκλεισμένοι χρήστες';
$string['blocknoncontacts'] = 'Φραγή όλων των νέων μηνυμάτων από χρήστες που δεν βρίσκονται στη λίστα επαφών σας.';
$string['blockuser'] = 'Αποκλεισμός χρήστη';
$string['blockuserconfirm'] = 'Είστε βέβαιοι ότι θέλετε να αποκλείσετε τον/την {$a};';
$string['blockuserconfirmbutton'] = 'Μπλοκ';
$string['canceledit'] = 'Ακύρωση επεξεργασίας μηνυμάτων';
$string['cancelselection'] = 'Ακύρωση επιλογής μηνυμάτων';
$string['contactableprivacy'] = 'Αποδοχή μηνυμάτων από:';
$string['contactableprivacy_coursemember'] = 'Οι επαφές μου και οποιοσδήποτε από τα μαθήματά μου';
$string['contactableprivacy_onlycontacts'] = 'Μόνο οι επαφές μου';
$string['contactableprivacy_site'] = 'Οποιοσδήποτε στον ιστότοπο';
$string['contactblocked'] = 'Η επαφή αποκλείστηκε';
$string['contactrequests'] = 'Αιτήματα επαφής';
$string['contactrequestsent'] = 'Το αίτημα επαφής στάλθηκε';
$string['contacts'] = 'Επαφές';
$string['conversationactions'] = 'Μενού ενεργειών συνομιλίας';
$string['decline'] = 'Άρνηση';
$string['defaultmessageoutputs'] = 'Προεπιλεγμένα μηνύματα που παράγονται';
$string['defaults'] = 'Προεπιλογές';
$string['deleteallconfirm'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε όλη αυτή τη συνομιλία; Δεν θα διαγραφεί το αντίγραφο των άλλων συμμετεχόντων στη συζήτηση.';
$string['deleteallmessages'] = 'Διαγραφή όλων των μηνυμάτων';
$string['deleteconversation'] = 'Διαγραφή συζήτησης';
$string['deleteselectedmessages'] = 'Διαγραφή επιλεγμένων μηνυμάτων';
$string['deleteselectedmessagesconfirm'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τα επιλεγμένα μηνύματα; Δεν θα διαγραφούν από τους άλλους συμμετέχοντες συζητήσεων.';
$string['disableall'] = 'Απενεργοποίηση ειδοποιήσεων';
$string['disabled'] = 'Η ανταλλαγή μηνυμάτων έχει απενεργοποιηθεί σε αυτό τον ιστότοπο';
$string['disallowed'] = 'Απογορεύεται';
$string['editmessages'] = 'Επεξεργασία μηνυμάτων';
$string['emailtagline'] = 'Αυτό είναι ένα αντίγραφο ενός μηνύματος που σας στάλθηκε στον ιστότοπο «{$a->sitename}». Μπορείτε να απαντήσετε στη διεύθυνση {$a->url}.';
$string['enabled'] = 'Ενεργοποιημένο';
$string['errorcallingprocessor'] = 'Σφάλμα κατά την κλήση του ορισμένου μέσου ειδοποίησης';
$string['errorconversationdoesnotexist'] = 'Η συζήτηση δεν υπάρχει';
$string['errortranslatingdefault'] = 'Σφάλμα μετάφρασης της προεπιλεγμένης ρύθμισης που παρέχεται από το πρόσθετο. Αντ\' αυτού γίνεται χρήση της προεπιλογής του συστήματος.';
$string['eventgroupmessagesent'] = 'Το ομαδικό μήνυμα στάλθηκε';
$string['eventmessagecontactadded'] = 'Η επαφή μηνυμάτων προστέθηκε';
$string['eventmessagecontactblocked'] = 'Η επαφή μηνυμάτων αποκλείστηκε';
$string['eventmessagecontactremoved'] = 'Η επαφή μηνυμάτων αφαιρέθηκε';
$string['eventmessagecontactunblocked'] = 'Ο αποκλεισμός επαφής μηνυμάτων ακυρώθηκε';
$string['eventmessagedeleted'] = 'Το μήνυμα διαγράφηκε';
$string['eventmessagesent'] = 'Το μήνυμα στάλθηκε';
$string['eventmessageuserblocked'] = 'Ο χρήστης αποκλείστηκε';
$string['eventmessageuserunblocked'] = 'Ο χρήστης ξεκλειδώθηκε';
$string['eventmessageviewed'] = 'Το μήνυμα προβλήθηκε';
$string['eventnotificationsent'] = 'Η ειδοποίηση στάλθηκε';
$string['eventnotificationviewed'] = 'Η ειδοποίηση προβλήθηκε';
$string['forced'] = 'Κλείδωμα';
$string['groupconversations'] = 'Ομάδα';
$string['groupinfo'] = 'Στοιχεία ομάδας';
$string['groupmessages'] = 'Ομάδα';
$string['guestnoeditmessage'] = 'Οι επισκέπτες δεν μπορούν να τροποποιήσουν τις επιλογές μηνημάτων';
$string['guestnoeditmessageother'] = 'Οι επισκέπτες δεν μπορούν να τροποποιήσουν τις επιλογές μηνυμάτων άλλων χρηστών';
$string['hidemessagewindow'] = 'Απόκρυψη παραθύρου μηνύματος';
$string['hidenotificationwindow'] = 'Απόκρυψη παράθυρου ειδοποίησης';
$string['individualconversations'] = 'Ιδιωτικές';
$string['info'] = 'Πληροφορίες χρήστη';
$string['isnotinyourcontacts'] = 'Ο/Η {$a} δεν βρίσκεται στις επαφές σας';
$string['loadmore'] = 'Φόρτωσε περισσότερα';
$string['loggedin'] = 'Εντός σύνδεσης';
$string['loggedindescription'] = 'Όταν έχετε συνδεθεί στο Moodle';
$string['loggedin_help'] = 'Προσαρμόστε το πώς επιθυμείτε να λαμβάνετε ειδοποιήσεις όταν έχετε συνδεθεί στη πλατφόρμα';
$string['loggedoff'] = 'Εκτός σύνδεσης';
$string['loggedoffdescription'] = 'Όταν δεν έχετε συνδεθεί στο Moodle';
$string['loggedoff_help'] = 'Προσαρμόστε το πώς επιθυμείτε να λαμβάνετε ειδοποιήσεις όταν δεν έχετε συνδεθεί στο Moodle';
$string['managemessageoutputs'] = 'Διαχείριση μηνυμάτων που παράγονται';
$string['message'] = 'Μήνυμα';
$string['messagecontactrequestsnotification'] = 'Ο/Η {$a} ζητά να προστεθεί ως επαφή';
$string['messagecontactrequestsnotificationsubject'] = 'Αίτημα επαφής από τον/την {$a}';
$string['messagedrawerviewcontact'] = 'Στοιχεία χρήστη για τον/την {$a}';
$string['messagedrawerviewcontacts'] = 'Επαφές μηνυμάτων';
$string['messagedrawerviewconversation'] = 'Συνομιλία με τον/την {$a}';
$string['messagedrawerviewgroupinfo'] = 'Στοιχεία της ομάδας {$a}';
$string['messagedrawerviewoverview'] = 'Επισκόπηση μηνυμάτων';
$string['messagedrawerviewsearch'] = 'Τα αποτελέσματα αναζήτησης μηνυμάτων για {$a}';
$string['messagedrawerviewsettings'] = 'Ρυθμίσεις μηνυμάτων';
$string['messageoutputs'] = 'Μηνύματα που παράγονται';
$string['messagepreferences'] = 'Προτιμήσεις μηνυμάτων';
$string['messages'] = 'Μηνύματα';
$string['messagesselected:'] = 'Επιλεγμένα μηνύματα:';
$string['messagingdatahasnotbeenmigrated'] = 'Τα μηνύματά σας είναι προσωρινά μη διαθέσιμα λόγω αναβαθμίσεων στην υποδομή ανταλλαγής μηνυμάτων. Παρακαλούμε, περιμένετε να μετεγκατασταθούν (μεταφορά/μετατροπή).';
$string['messagingdisabled'] = 'Η ανταλλαγή μηνυμάτων έχει απενεργοποιηθεί σε αυτό τον ιστότοπο. Aντί αυτών θα σταλούν μηνύματα ηλε.ταχυδρομείου';
$string['newmessage'] = 'Νέο μήνυμα';
$string['newmessagesearch'] = 'Επιλέξτε ή αναζητήστε μια επαφή για να στείλετε μήνυμα.';
$string['newonlymsg'] = 'Εμφάνιση μόνο νέων';
$string['nocontactrequests'] = 'Καθόλου αιτήματα επαφών';
$string['nocontacts'] = 'Καμία επαφή';
$string['nocontactsgetstarted'] = 'Καθόλου επαφές';
$string['nofavourites'] = 'Δεν υπάρχουν συνομιλίες με αστερίσκο';
$string['noframesjs'] = 'Χρήση μιας περισσότερο προσβάσιμης διεπαφής';
$string['nogroupconversations'] = 'Καθόλου ομαδικές συζητήσεις';
$string['nogroupmessages'] = 'Καθόλου ομαδικές συζητήσεις';
$string['noindividualconversations'] = 'Καθόλου ιδιωτικές συζητήσεις';
$string['nomessages'] = 'Δεν υπάρχουν μηνύματα';
$string['nomessagesfound'] = 'Δε βρέθηκαν μηνύματα';
$string['noncontacts'] = 'Μη επαφές';
$string['nonotifications'] = 'Δεν έχετε καμία ειδοποίηση';
$string['noparticipants'] = 'Καθόλου συμμετέχοντες';
$string['noreply'] = 'Μην απαντήσετε σε αυτό το μήνυμα';
$string['notificationdatahasnotbeenmigrated'] = 'Οι ειδοποιήσεις σας είναι προσωρινά μη διαθέσιμες λόγω αναβαθμίσεων στην υποδομή ειδοποιήσεων. Παρακαλούμε, περιμένετε να μετεγκατασταθούν (μεταφορά/μετατροπή).';
$string['notificationimage'] = 'Εικόνα ειδοποίησης';
$string['notificationpreferences'] = 'Προτιμήσεις ειδοποιήσεων';
$string['notifications'] = 'Ειδοποιήσεις';
$string['notificationwindow'] = 'Παράθυρο ειδοποίησης';
$string['notincontacts'] = 'Χρειάζεται να προσθέσετε τον/την {$a} στις επαφές σας για να μπορέσετε να του/της στείλετε μηνύματα.';
$string['notincontactsheading'] = 'Ο/Η {$a} δεν βρίσκεται στις επαφές σας';
$string['numparticipants'] = '{$a} συμμετέχοντες';
$string['off'] = 'ΟΧΙ';
$string['offline'] = 'Εκτός σύνδεσης';
$string['on'] = 'ΝΑΙ';
$string['online'] = 'Εντός σύνδεσης';
$string['otherparticipants'] = 'Άλλοι συμμετέχοντες';
$string['outputdisabled'] = 'Έξοδος απενεργοποιημένη';
$string['outputdoesnotexist'] = 'Η έξοδος μηνύματος δεν υπάρχει';
$string['outputenabled'] = 'Ενεργοποιημένη έξοδος';
$string['outputnotavailable'] = 'Μη διαθέσιμη';
$string['outputnotconfigured'] = 'Δεν έχει ρυθμιστεί';
$string['participants'] = 'Συμμετέχοντες';
$string['pendingcontactrequests'] = 'Υπάρχουν {$a} αιτήματα επικοινωνίας σε εκκρεμότητα';
$string['permitted'] = 'Επιτρέπεται';
$string['privacy'] = 'Ιδιωτικότητα';
$string['privacy_desc'] = 'Μπορείτε να περιορίσετε ποιος μπορεί να σας στείλει μήνυμα';
$string['privacy:export:conversationprefix'] = 'Συζήτηση:';
$string['privacy:metadata:core_favourites'] = 'Οι συνομιλίες που επισημάνθηκαν με αστερίσκο από το χρήστη';
$string['privacy:metadata:message_contact_requests'] = 'Η λίστα των αιτημάτων επικοινωνίας';
$string['privacy:metadata:message_contact_requests:requesteduserid'] = 'Το αναγνωριστικό του χρήστη που έλαβε το αίτημα επικοινωνίας';
$string['privacy:metadata:message_contact_requests:timecreated'] = 'Η ώρα δημιουργίας του αιτήματος επαφής';
$string['privacy:metadata:message_contact_requests:userid'] = 'Το αναγνωριστικό του χρήστη που έστειλε το αίτημα επικοινωνίας';
$string['privacy:metadata:message_contacts'] = 'Η λίστα των επαφών';
$string['privacy:metadata:message_contacts:contactid'] = 'Το αναγνωριστικό του χρήστη που είναι στις επαφές';
$string['privacy:metadata:message_contacts:timecreated'] = 'Η ώρα δημιουργίας της επαφής';
$string['privacy:metadata:message_contacts:userid'] = 'Το αναγνωριστικό του χρήστη του οποίου τη λίστα με τις επαφές βλέπουμε';
$string['privacy:metadata:message_conversation_members'] = 'Η λίστα των χρηστών σε μια συζήτηση';
$string['privacy:metadata:message_conversation_members:conversationid'] = 'Το αναγνωριστικό της συζήτησης';
$string['privacy:metadata:message_conversation_members:timecreated'] = 'Πότε δημιουργήθηκε/εντάχθηκε το μέλος';
$string['privacy:metadata:message_conversation_members:userid'] = 'Το αναγνωριστικό ενός χρήστη σε μια συζήτηση';
$string['privacy:metadata:messages'] = 'Μηνύματα';
$string['privacy:metadata:messages:conversationid'] = 'Το αναγνωριστικό της συνομιλίας';
$string['privacy:metadata:messages:fullmessage'] = 'Το πλήρες μήνυμα';
$string['privacy:metadata:messages:fullmessageformat'] = 'Ο μορφότυπος του πλήρους μηνύματος';
$string['privacy:metadata:messages:fullmessagehtml'] = 'Ο μορφότυπος HTML του πλήρους μηνύματος';
$string['privacy:metadata:messages:smallmessage'] = 'Μια μικρή έκδοση του μηνύματος';
$string['privacy:metadata:messages:subject'] = 'Το θέμα του μηνύματος';
$string['privacy:metadata:messages:timecreated'] = 'Η ώρα δημιουργίας του μηνύματος';
$string['privacy:metadata:messages:useridfrom'] = 'Το αναγνωριστικό του χρήστη που έστειλε το μήνυμα';
$string['privacy:metadata:message_user_actions'] = 'Η λίστα των ενεργειών χρηστών για μηνύματα';
$string['privacy:metadata:message_user_actions:action'] = 'Η ενέργεια που πραγματοποιήθηκε';
$string['privacy:metadata:message_user_actions:messageid'] = 'Το αναγνωριστικό του μηνύματος στο οποίο αυτή η ενέργεια ανήκει';
$string['privacy:metadata:message_user_actions:timecreated'] = 'Πότε δημιουργήθηκε η ενέργεια';
$string['privacy:metadata:message_user_actions:userid'] = 'Το αναγνωριστικό του χρήστη που εκτέλεσε αυτή την ενέργεια';
$string['privacy:metadata:message_users_blocked'] = 'Η λίστα των αποκλεισμένων χρηστών';
$string['privacy:metadata:message_users_blocked:blockeduserid'] = 'Το αναγνωριστικό του χρήστη που αποκλείστηκε';
$string['privacy:metadata:message_users_blocked:timecreated'] = 'Η ώρα δημιουργίας της ενέργειας αποκλεισμού';
$string['privacy:metadata:message_users_blocked:userid'] = 'Το αναγνωριστικό του χρήστη που πραγματοποίησε την ενέργεια αποκλεισμού';
$string['privacy:metadata:notifications'] = 'Ειδοποιήσεις';
$string['privacy:metadata:notifications:component'] = 'Το στοιχείο λογισμικού που είναι υπεύθυνο για την αποστολή της ειδοποίησης';
$string['privacy:metadata:notifications:contexturl'] = 'Η διεύθυνση URL που σχετίζεται με αυτή την ειδοποίηση';
$string['privacy:metadata:notifications:contexturlname'] = 'Το όνομα του πλαισίου';
$string['privacy:metadata:notifications:eventtype'] = 'Ο τύπος του γεγονότος';
$string['privacy:metadata:notifications:fullmessage'] = 'Η πλήρης ειδοποίηση';
$string['privacy:metadata:notifications:fullmessageformat'] = 'Ο μορφότυπος της ειδοποίησης';
$string['privacy:metadata:notifications:fullmessagehtml'] = 'Ο HTML κώδικας της ειδοποίησης';
$string['privacy:metadata:notifications:smallmessage'] = 'Το σύντομο μήνυμα της ειδοποίησης';
$string['privacy:metadata:notifications:subject'] = 'Το θέμα της ειδοποίησης';
$string['privacy:metadata:notifications:timecreated'] = 'Πότε δημιουργήθηκε η ειδοποίηση';
$string['privacy:metadata:notifications:timeread'] = 'Πότε αναγνώστηκε η ειδοποίηση';
$string['privacy:metadata:notifications:useridfrom'] = 'Το αναγνωριστικό του χρήστη που έστειλε την ειδοποίηση';
$string['privacy:metadata:notifications:useridto'] = 'Το αναγνωριστικό του χρήστη που έλαβε την ειδοποίηση';
$string['privacy:metadata:preference:core_message_settings'] = 'Ρυθμίσεις σχετικές με την ανταλλαγή μηνυμάτων';
$string['privacy:request:preference:set'] = 'Η τιμή των ρυθμίσεων «{$a->name}» ήταν «{$a->value}»';
$string['processorsettings'] = 'Ρυθμίσεις επεξεργαστή';
$string['removecontact'] = 'Αφαίρεση επαφής';
$string['removecontactconfirm'] = 'Είστε βέβαιοι ότι θέλετε να καταργήσετε τον/την {$a} από τις επαφές σας;';
$string['removecoursefilter'] = 'Αφαίρεση φίλτρου για το μάθημα «{$a}»';
$string['removefromfavourites'] = 'Αφαίρεση αστερίσκου';
$string['removefromyourcontacts'] = 'Αφαίρεση από τις επαφές';
$string['requirecontacttomessage'] = 'Θα πρέπει να ζητήσετε από τον/την {$a} να σας προσθέσει ως επαφή για να μπορέσετε να στείλετε μήνυμα.';
$string['requiresconfiguration'] = 'Απαιτούνται ρυθμίσεις';
$string['searchcombined'] = 'Αναζήτηση επαφών και μηνυμάτων';
$string['searchforuser'] = 'Αναζήτηση χρήστη';
$string['searchforuserorcourse'] = 'Ψάξτε για χρήστη ή για μάθημα';
$string['searchmessages'] = 'Αναζήτηση μηνυμάτων';
$string['searchnocontactsfound'] = 'Δεν βρέθηκαν επαφές';
$string['searchnomessagesfound'] = 'Δεν βρέθηκαν μηνύματα';
$string['searchnononcontactsfound'] = 'Δεν βρέθηκαν μη επαφές';
$string['seeall'] = 'Όλα τα μηνύματα';
$string['selectmessagestodelete'] = 'Επιλέξτε τα μηνύματα που θα διαγραφούν';
$string['selectnotificationtoview'] = 'Επιλέξτε από τη λίστα των ειδοποιήσεων για να δείτε περισσότερες λεπτομέρειες';
$string['send'] = 'Αποστολή';
$string['sendbulkmessage'] = 'Αποστολή μηνύματος σε {$a} άτομα';
$string['sendbulkmessagesent'] = 'Το μήνυμα στάλθηκε σε {$a} άτομα';
$string['sendbulkmessagesentsingle'] = 'Το μήνυμα στάλθηκε σε 1 άτομο';
$string['sendbulkmessagesingle'] = 'Αποστολή μηνύματος σε 1 άτομο';
$string['sendcontactrequest'] = 'Αποστολή αιτήματος δημιουργίας επαφής';
$string['sender'] = '{$a}:';
$string['sendingvia'] = 'Αποστολή «{$a->provider}» μέσω «{$a->processor}»';
$string['sendingviawhen'] = 'Αποστολή «{$a->provider}» μέσω «{$a->processor}» όταν {$a->state}';
$string['sendmessage'] = 'Αποστολή μηνύματος';
$string['sendmessageto'] = 'Αποστολή μηνύματος σε {$a}';
$string['sendmessagetopopup'] = 'Αποστολή μηνύματος σε {$a} - νέο παράθυρο';
$string['settings'] = 'Ρυθμίσεις';
$string['showmessagewindownonew'] = 'Εμφάνιση παραθύρου μηνύματος χωρίς νέα μηνύματα';
$string['showmessagewindowwithcount'] = 'Εμφάνιση παράθυρου μηνυμάτων με {$a} νέα μηνύματα';
$string['shownotificationwindownonew'] = 'Εμφάνιση παραθύρου ειδοποιήσεων χωρίς νέες ειδοποιήσεις';
$string['shownotificationwindowwithcount'] = 'Εμφάνιση παραθύρου ειδοποιήσεων με {$a} νέες ειδοποιήσεις';
$string['togglemessagemenu'] = 'Συρτάρι μηνυμάτων: Άνοιγμα/κλείσιμο';
$string['togglenotificationmenu'] = 'Εναλλαγή εμφάνισης/απόκρυψης του μενού ειδοποιήσεων';
$string['totalconversations'] = '{$a} συνολικές συζητήσεις';
$string['touserdoesntexist'] = 'Δεν μπορείτε να αποστείλετε μήνυμα σε ένα αναγνωριστικό χρήστη ({$a}) που δεν υπάρχει';
$string['unabletomessage'] = 'Δεν μπορείτε να στείλετε μήνυμα σε αυτόν τον χρήστη';
$string['unblock'] = 'Ξεκλείδωμα';
$string['unblockcontact'] = 'Ξεμπλόκαρε την επαφή';
$string['unblockuser'] = 'Ξεκλείδωμα χρήστη';
$string['unblockuserconfirm'] = 'Είστε βέβαιοι ότι θέλετε να ξεκλειδώσετε τον/την {$a};';
$string['unknownuser'] = 'Άγνωστος χρήστης';
$string['unreadconversations'] = 'Υπάρχουν {$a} μη αναγνωσμένες συζητήσεις';
$string['unreadmessages'] = 'Υπάρχουν {$a} μη αναγνωσμένα μηνύματα';
$string['unreadnewgroupconversationmessage'] = 'Νέο μήνυμα από τον/την {$a->name} στην συζήτηση {$a->conversationname}';
$string['unreadnewmessage'] = 'Νέο μήνυμα από {$a}';
$string['unreadnotification'] = 'Αδιάβαστη ειδοποίηση: {$a}';
$string['unreadnotifications'] = 'Υπάρχουν {$a} μη αναγνωσμένες ειδοποιήσεις';
$string['useentertosend'] = 'Χρήση του πλήκτρου Enter για τέλος εισόδου & αποστολή';
$string['usercantbemessaged'] = 'Δεν μπορείτε να στείλετε μηνύματα στον χρήστη {$a} λόγω των προτιμήσεων μηνυμάτων του. Προσπαθήστε να τον προσθέσετε ως επαφή.';
$string['userisblockingyou'] = 'Αυτός ο χρήστης έχει μπλοκάρει την αποδοχή μηνυμάτων από σας.';
$string['userisblockingyounoncontact'] = 'Ο/Η χρήστης {$a} δέχεται μηνύματα μόνο από όσους βρίσκονται στις επαφές του/της.';
$string['userwouldliketocontactyou'] = 'Ο/Η {$a} θα ήθελε να επικοινωνήσει μαζί σας';
$string['viewfullnotification'] = 'Ολόκληρη η ειδοποίηση';
$string['viewinganotherusersmessagearea'] = 'Παρακολουθείτε την περιοχή μηνυμάτων άλλου χρήστη.';
$string['viewmessageswith'] = 'Εμφάνιση μηνυμάτων με {$a}';
$string['viewnotificationresource'] = 'Μετάβαση σε: {$a}';
$string['viewunreadmessageswith'] = 'Εμφάνιση αδιάβαστων μηνυμάτων με {$a}';
$string['wouldliketocontactyou'] = 'Θα ήθελαν να επικοινωνήσουν μαζί σας';
$string['writeamessage'] = 'Γράψτε ένα μήνυμα...';
$string['you'] = 'Εσείς:';
$string['youhaveblockeduser'] = 'Έχετε αποκλείσει αυτόν τον χρήστη.';
$string['yourcontactrequestpending'] = 'Η αίτηση επαφής σας επικοινωνίας εκκρεμεί για τον/την {$a}';
