<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'hvp', language 'gl', version '4.5'.
 *
 * @package     hvp
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['action'] = 'Acción';
$string['addedandupdatedpp'] = 'Engadida(s) {$a->%new} nova(s) biblioteca(s) H5P e actualizada(s) {$a->%old} antiga(s).';
$string['addedandupdatedps'] = 'Engadida(s) {$a->%new} nova(s) biblioteca(s) H5P e actualizada(s) {$a->%old} antiga(s).';
$string['addedandupdatedsp'] = 'Engadida(s) {$a->%new} nova(s) biblioteca(s) H5P e actualizada(s) {$a->%old} antiga(s).';
$string['addedandupdatedss'] = 'Engadida(s) {$a->%new} nova(s) biblioteca(s) H5P e actualizada(s) {$a->%old} antiga(s).';
$string['addednewlibraries'] = 'Engadidas {$a->%new} novas bibliotecas H5P.';
$string['addednewlibrary'] = 'Engadida {$a->%new} nova biblioteca H5P.';
$string['additionalinfo'] = 'Información Adicional';
$string['additionallicenseinfo'] = 'Calquera información adicional sobre a licenza';
$string['addlibraries'] = 'Engadir bibliotecas';
$string['ajaxfailed'] = 'Non se puideron cargar os datos.';
$string['anunexpectedsave'] = 'Ocorreu algo inesperado. No puidemos gardar este contido.';
$string['attribution'] = 'Recoñecemento 4.0';
$string['attributionnc'] = 'Recoñecemento-Non comercial 4.0';
$string['attributionncnd'] = 'Recoñecemento-Non comercial-Sen obra derivada 4.0';
$string['attributionncsa'] = 'Recoñecemento-Non comercial-Compartir igual 4.0';
$string['attributionnd'] = 'Recoñecemento-Sen obra derivada 4.0';
$string['attributionsa'] = 'Recoñecemento-Compartir igual 4.0';
$string['author'] = 'Autor';
$string['authorcomments'] = 'Comentarios do autor';
$string['authorcommentsdescription'] = 'Comentarios para o editor do contido (Este texto non se publicará como parte da información de dereitos de autor)';
$string['authorname'] = 'Nome do autor';
$string['authorrole'] = 'Papel do autor';
$string['by'] = 'por';
$string['cancellabel'] = 'Cancelar';
$string['ccattribution'] = 'Recoñecemento (CC BY)';
$string['ccattributionnc'] = 'Recoñecemento-Non comercial (CC BY-NC)';
$string['ccattributionncnd'] = 'Recoñecemento-Non comercial-Sen obra derivada (CC BY-NC-ND)';
$string['ccattributionncsa'] = 'Recoñecemento-Non comercial-Compartir igual (CC BY-NC-SA)';
$string['ccattributionnd'] = 'Recoñecemento-Sen obra derivada (CC BY-ND)';
$string['ccattributionsa'] = 'Recoñecemento-Compartir igual (CC BY-SA)';
$string['ccpdd'] = 'Dedicación de dominio público (CC0)';
$string['ccpdm'] = 'Marca de dominio público (PDM)';
$string['changedby'] = 'Cambiado por';
$string['changedescription'] = 'Descrición do cambio';
$string['changelog'] = 'Rexistro de cambios';
$string['changeplaceholder'] = 'Foto recortada, texto cambiado, etc.';
$string['close'] = 'Pechar';
$string['completionpass'] = 'Requirir cualificación para aprobar';
$string['completionpass_help'] = 'Se activamos isto, a actividade considerarase completada cando o alumno reciba a nota de aprobado (segundo especifiquemos na sección de cualificación da configuración da actividade H5P) ou maior.';
$string['completionpassdesc'] = 'Os alumnos deben acadar unha cualificación de aprobado para completar esta actividade';
$string['confirmdialogbody'] = 'Por favor, confirma que queres continuar. Esta acción non pode desfacerse.';
$string['confirmdialogheader'] = 'Confirmar acción';
$string['confirmlabel'] = 'Confirmar';
$string['connectionlost'] = 'Perdeuse a conexión. Os resultados almacenaranse e enviaranse cando a conexión se restableza.';
$string['connectionreestablished'] = 'Conexión restablecida.';
$string['contentchanged'] = 'Este contido cambiou desde que o usaches por última vez.';
$string['contentcopied'] = 'Copiouse o contido ao portapapeis';
$string['contentstatefrequency'] = 'Frecuencia do gardado do estado do contido';
$string['contentstatefrequency_help'] = 'En segundos, con que frecuencia queres que o usuario garde o seu progreso automaticamente. Aumenta este número se estás a ter problemas con moitas peticións ajax';
$string['contenttype'] = 'Tipo de contido';
$string['contenttypecacheheader'] = 'Caché de tipos de contido';
$string['copyright'] = 'Dereitos de uso';
$string['copyrightinfo'] = 'Información de dereitos de autor';
$string['copyrightstring'] = 'Dereitos de autor';
$string['copyrighttitle'] = 'Ver información de dereitos de autor para este contido.';
$string['couldnotcopy'] = 'Non se puido copiar o ficheiro.';
$string['couldnotparsejsonfromzip'] = 'Non podemos examinar o JSON do paquete: %fileName';
$string['couldnotparsepostdata'] = 'Non podemos ler os datos da publicación.';
$string['couldnotreadfilefromzip'] = 'Non podemos ler o ficheiro do paquete: %fileName';
$string['couldnotsave'] = 'Non se puido gardar o ficheiro.';
$string['create'] = 'Crear';
$string['creativecommons'] = 'Creative Commons';
$string['ctcachebuttonlabel'] = 'Actualizar a caché de tipos de contido';
$string['ctcacheconnectionfailed'] = 'Non foi posible establecer comunicación co hub H5P. Por favor, proba outra vez máis tarde.';
$string['ctcachedescription'] = 'Manter a caché de tipos de contido ao día asegúrache poder ver, descargar e usar as últimas bibliotecas. Isto non é o mesmo que actualizar as bibliotecas.';
$string['ctcachelastupdatelabel'] = 'Última actualización';
$string['ctcacheneverupdated'] = 'Nunca';
$string['ctcachenolibraries'] = 'Non se recibiron tipos de contido do hub H5P. Por favor, proba outra vez máis tarde.';
$string['ctcachesuccess'] = 'Actualizouse a caché de bibliotecas satisfactoriamente!';
$string['ctcachetaskname'] = 'Actualizar a caché de tipos de contido';
$string['currentpage'] = 'Páxina $current de $total';
$string['dataviewreportlabel'] = 'Ver Respostas';
$string['date'] = 'Data';
$string['disablefileextensioncheck'] = 'Desactivar comprobación de extensión de arquivos';
$string['disablefileextensioncheckwarning'] = 'Ollo! Desactivar a comprobación de extensión de arquivo pode ter implicacións de seguridade porque permite a subida de arquivos php. Isto podería permitir que un atacante executase código malicioso no teu sitio. Por favor, asegúrate de saber exactamente que estás a subir.';
$string['disablefullscreen'] = 'Desactivar Pantalla Completa';
$string['disablehubconfirmationmsg'] = 'Aínda queres activar o hub ?';
$string['disablehubdescription'] = 'Aconséllase manter esta opción activada. O hub H5P proporciona unha interface moi doada de usar para conseguir novos tipos de contido e manter actualizados os existentes. No futuro, tamén facilitará a compartimento e reutilización de contido. Se desactivas esta opción, terás que instalar e actualizar os tipos de contido mediante formularios de subida de ficheiros.';
$string['displayoptionalwaysshow'] = 'Amosar sempre';
$string['displayoptionauthoroff'] = 'Controlado polo autor, desactivado por defecto';
$string['displayoptionauthoron'] = 'Controlado polo autor, activado por defecto';
$string['displayoptiondownloadalways'] = 'Sempre';
$string['displayoptiondownloadnever'] = 'Nunca';
$string['displayoptiondownloadpermission'] = 'Só se o usuario ten permisos para exportar H5P';
$string['displayoptionnevershow'] = 'Nunca amosar';
$string['displayoptionpermissions'] = 'Amosar só se o usuario ten permisos para exportar H5P';
$string['displayoptionpermissionsembed'] = 'Amosar só se o usuario ten permisos para embeber H5P';
$string['displayoptions'] = 'Opcións de Presentación';
$string['download'] = 'Descargar';
$string['downloadfailed'] = 'Fallou a descarga da biblioteca solicitada.';
$string['downloadtitle'] = 'Descargar este contido como arquivo H5P.';
$string['editor'] = 'Editor';
$string['emailconfirmbody'] = 'Ola {$a->username},

Grazas por enviar as túas respostas para \'{$a->hvpname}\' na materia \'{$a->coursename}\'.

Este mensaxe confirma que as túas respostas foron gardadas.

Podes acceder a este H5P en {$a->hvpurl}.';
$string['emailconfirmsmall'] = 'Grazas por enviar as túas respostas para \'{$a->hvpname}\'';
$string['emailconfirmsubject'] = 'Confirmación de envío: {$a->hvpname}';
$string['emailnotifybody'] = 'Ola {$a->username},

{$a->studentname} completou \'{$a->hvpname}\' ({$a->hvpurl}) no curso \'{$a->coursename}\'.

Podes revisar este intento en {$a->hvpreporturl}.';
$string['emailnotifysmall'] = '{$a->studentname} completou {$a->hvpname}. Mira {$a->hvpreporturl}';
$string['emailnotifysubject'] = '{$a->studentname} completou {$a->hvpname}';
$string['embed'] = 'Embeber';
$string['embedloginfailed'] = 'Non tes permiso para acceder a este contido. Proba a acceder ao sitio.';
$string['embedtitle'] = 'Ver o código para embeber este contido.';
$string['empty'] = 'Non hai resultados dispoñibles';
$string['enableabout'] = 'Botón Acerca de H5P';
$string['enablecopyright'] = 'Botón Copyright';
$string['enabledlrscontenttypes'] = 'Activa os tipos dependentes de LRS';
$string['enabledlrscontenttypes_help'] = 'Activa a posibilidade de usar tipos de contido que dependan dunha función LRS para funcionar axeitadamente, como o tipo de contido Cuestionario.';
$string['enabledownload'] = 'Permitir descarga';
$string['enableembed'] = 'Botón embeber';
$string['enableframe'] = 'Amosar barra de acción e marco';
$string['enablehublabel'] = 'Usar H5P Hub';
$string['enablejavascript'] = 'Por favor, activa JavaScript.';
$string['enablesavecontentstate'] = 'Gardar o estado do contido';
$string['enablesavecontentstate_help'] = 'Garda o estado do contido interactivo automaticamente para cada usuario. Isto quere dicir que o usuario pode continuar onde o deixou.';
$string['failedtodownloadh5p'] = 'Non se puido descargar o H5P solicitado.';
$string['fileexceedsmaxsize'] = 'Un dos ficheiros do paquete excede o tamaño máximo de ficheiro permitido. (%file %used > %max)';
$string['filenotfoundonserver'] = 'Ficheiro non atopado no servidor. Comproba a configuración de subida de ficheiros.';
$string['filenotimage'] = 'O ficheiro non é unha imaxe.';
$string['filetypenotallowed'] = 'Non se permite o tipo de ficheiro.';
$string['finished'] = 'Rematado';
$string['fullscreen'] = 'Pantalla Completa';
$string['gpl'] = 'Licenza pública xeral v3';
$string['gradetopassmustbeset'] = 'A cualificación para aprobar non pode ser cero porque esta actividade H5P está configurada para requirir unha nota de aprobado como condición de completado. Por favor, escolle un valor distinto de cero.';
$string['gradetopassnotset'] = 'Esta actividade H5P aínda non ten establecida unha cualificación de aprobado. Pódese establecer na sección de cualificación da configuración da actividade H5P.';
$string['h5pfile'] = 'Arquivo H5P';
$string['h5ptitle'] = 'Visita H5P.org para probar máis contido interesante.';
$string['hide'] = 'Agachar';
$string['hideadvanced'] = 'Agachar avanzado';
$string['hubcommunicationdisabled'] = 'Desactivouse a comunicación co hub H5P porque fallaron un ou máis requirimentos de H5P.';
$string['hubisdisabled'] = 'O Hub está desactivado. Podes reactivalo na configuración H5P.';
$string['hubisdisableduploadlibraries'] = 'Desactivouse o hub H5P ata que poida resolverse este problema. Con todo, aínda podes subir bibliotecas usando a páxina "Bibliotecas H5P".';
$string['hubsettingsheader'] = 'Tipos de Contido';
$string['hvp:addinstance'] = 'Crear novas actividades H5P';
$string['hvp:emailconfirmsubmission'] = 'Recibir mensaxe de confirmación ao enviar';
$string['hvp:emailnotifysubmission'] = 'Recibir mensaxe de notificación cando se envíe un intento';
$string['hvp:getcachedassets'] = 'Requirido para ver as actividades H5P';
$string['hvp:getembedcode'] = 'Ver o código de embebido H5P cando estea activa a opción \'controlado por permiso\'';
$string['hvp:getexport'] = 'Descarga o arquivo .h5p cando estea activa a opción \'controlado por permiso\'';
$string['hvp:installrecommendedh5plibraries'] = 'Instalar novos tipos de contido H5P seguros recomendados por H5P.org';
$string['hvp:manage'] = 'Editar actividades H5P existentes';
$string['hvp:restrictlibraries'] = 'Restrinxir o acceso a determinados tipos de contido H5P';
$string['hvp:savecontentuserdata'] = 'Gardar o progreso dos usuarios nas actividades H5P';
$string['hvp:saveresults'] = 'Gardar os resultados das actividades H5P completadas';
$string['hvp:updatelibraries'] = 'Instalar novos tipos de contido H5P ou actualizar os existentes';
$string['hvp:userestrictedlibraries'] = 'Usar tipos de contido H5P restrinxidos';
$string['hvp:view'] = 'Ver e interactuar coas actividades H5P';
$string['hvp:viewallresults'] = 'Ver todos os resultados nas actividades H5P completadas';
$string['hvp:viewresults'] = 'Ver os propios resultados nas actividades H5P completadas';
$string['installdenied'] = 'Non tes permiso para instalar tipos de contido. Contacta co administrador do sitio.';
$string['installedlibraries'] = 'Bibliotecas instaladas';
$string['intro'] = 'Introdución';
$string['invalidaudioformat'] = 'Formato de ficheiro de audio non válido. Usa mp3 ou wav.';
$string['invalidcontentfolder'] = 'Cartafol de contido non válido';
$string['invalidcontenttype'] = 'O contido escollido non é válido.';
$string['invalidfieldtype'] = 'Tipo de campo non válido.';
$string['invalidfile'] = 'Ficheiro "{$a->%filename}" non permitido. Permítense só ficheiros coas seguintes extensións: {$a->%files-allowed}.';
$string['invalidh5ppost'] = 'Non se puido obter o H5P publicado.';
$string['invalidimageformat'] = 'Formato de ficheiro de imaxe non válido. Usa jpg, png ou gif.';
$string['invalidlanguagefile'] = 'Ficheiro de idioma {$a->%file} non válido na biblioteca {$a->%library}';
$string['invalidlanguagefile2'] = 'Ficheiro de idioma {$a->%languageFile} non válido incluído na biblioteca {$a->%name}';
$string['invalidlibrary'] = 'Biblioteca non válida';
$string['invalidlibrarydata'] = 'Datos inválidos fornecidos para {$a->%property} en {$a->%library}';
$string['invalidlibrarydataboolean'] = 'Datos non válidos fornecidos para {$a->%property} en {$a->%library}. Esperábase booleano.';
$string['invalidlibraryname'] = 'Nome de librería: {$a->%name} non válido';
$string['invalidlibrarynamed'] = 'A biblioteca H5P {$a->%library} usada no contexto non é válida';
$string['invalidlibraryoption'] = 'Opción ilegal {$a->%option} en {$a->%library}';
$string['invalidlibraryproperty'] = 'Imposible ler a propiedade {$a->%property} en {$a->%library}';
$string['invalidmainjson'] = 'Falta un ficheiro principal h5p.json válido';
$string['invalidmultiselectoption'] = 'Opción seleccionada en selección múltiple non válida.';
$string['invalidparameters'] = 'Parámetros non válidos';
$string['invalidselectoption'] = 'Opción non válida seleccionada en selección.';
$string['invalidsemanticsjson'] = 'A biblioteca {$a->%name} contén un ficheiro semantics.json non válido';
$string['invalidsemanticstype'] = 'Erro interno H5P: tipo de contido "{$a->@type}" descoñecido en semantics. Eliminando o contido!';
$string['invalidstring'] = 'A cadea fornecida non é válida segundo o regexp en semantics. (valor: \\"{$a->%value}\\", regexp: \\"{$a->%regexp}\\")';
$string['invalidtoken'] = 'Código de seguranza non válido.';
$string['invalidvideoformat'] = 'Formato de ficheiro de vídeo non válido. Usa mp4 ou webm.';
$string['invalidxapiresult'] = 'Non se atoparon resultados xAPI para a combinación de contido e id de usuario especificados';
$string['javascriptloading'] = 'Agardando por JavaScript...';
$string['libraries'] = 'Bibliotecas H5P';
$string['librarydirectoryerror'] = 'O cartafol das bibliotecas debe coincidir con machineName ou con machineName-majorVersion.minorVersion (do ficheiro library.json). (Cartafol: {$a->%directoryName} , machineName: {$a->%machineName}, majorVersion: {$a->%majorVersion}, minorVersion: {$a->%minorVersion})';
$string['librarylistactions'] = 'Accións';
$string['librarylistinstancedependencies'] = 'Dependencias da instancia';
$string['librarylistinstances'] = 'Instancias';
$string['librarylistlibrarydependencies'] = 'Dependencias da biblioteca';
$string['librarylistrestricted'] = 'Restrinxido';
$string['librarylisttitle'] = 'Título';
$string['librarynotselected'] = 'Debes seleccionar un tipo de contido.';
$string['license'] = 'Licenza';
$string['licenseCC010'] = 'CC0 1.0 Universal (CC0 1.0) Dedicación de dominio público';
$string['licenseCC010U'] = 'CC0 1.0 Universal';
$string['licenseCC10'] = '1.0 Xenérica';
$string['licenseCC20'] = '2.0 Xenérica';
$string['licenseCC25'] = '2.5 Xenérica';
$string['licenseCC30'] = '3.0 Non portada';
$string['licenseCC40'] = '4.0 Internacional';
$string['licenseGPL'] = 'Licenza pública xeral';
$string['licenseV1'] = 'Versión 1';
$string['licenseV2'] = 'Versión 2';
$string['licenseV3'] = 'Versión 3';
$string['licensee'] = 'Licenciado';
$string['licenseextras'] = 'Extras da Licenza';
$string['licenseversion'] = 'Versión de Licenza';
$string['loadingdata'] = 'Cargando datos.';
$string['lookforupdates'] = 'Buscar actualizacións de H5P';
$string['maximumgrade'] = 'Cualificación máxima';
$string['maximumgradeerror'] = 'Por favor, fornece un número enteiro positivo válido como número máximo de puntos dispoñible para esta actividade';
$string['maxpostsizetoosmall'] = 'O teu valor para max post size en PHP é bastante pequeno. Coa configuración actual, non podes subir ficheiros de máis de {$a->%number} MB. Isto podería ser un problema cando intentes subir arquivos H5P, imaxes e vídeos. Por favor, pensa en aumentar ese valor a máis de 5MB.';
$string['maxscore'] = 'Puntuación Máxima';
$string['maxuploadsizetoosmall'] = 'O valor max upload size de PHP e bastante pequeno. Coa configuración actual, non podes subir ficheiros de máis de {$a->%number} MB. Isto podería ser un problema cando intentes subir arquivos H5P, imaxes e vídeos. Por favor, pensa en aumentar ese valor a máis de 5MB.';
$string['messageprovider:confirmation'] = 'Confirmación dos teus propios envíos H5P';
$string['messageprovider:submission'] = 'Notificación de envíos H5P';
$string['missingcontentfolder'] = 'Non se atopa un cartafol de contido válido';
$string['missingcontentuserdata'] = 'Erro: Non se puideron atopar datos de usuario para o contido';
$string['missingcoreversion'] = 'O sistema non foi quen de instalar o compoñente <em>{$a->%component}</em> do paquete porque require unha versión máis moderna do engadido H5P. Este sitio está usar a versión {$a->%current}, mentres que a versión requirida é {$a->%required} ou superior. Deberías  actualizalo e probar outra vez.';
$string['missingdependency'] = 'Falta a dependencia {$a->@dep} requirida por {$a->@lib}.';
$string['missinglibrary'] = 'Falta a biblioteca {$a->@library} requirida';
$string['missinglibraryfile'] = 'Falta o ficheiro "{$a->%file}" da biblioteca: "{$a->%name}"';
$string['missinglibraryjson'] = 'Non se atopa un ficheiro library.json con formato json válido para a biblioteca {$a->%name}';
$string['missinglibraryproperty'] = 'A propiedade requirida {$a->%property} non está presente en {$a->%library}';
$string['missingmbstring'] = 'Non está cargada a extensión PHP mbstring. H5P necesita esta extensión para funcionar correctamente';
$string['missingparameters'] = 'Faltan parámetros';
$string['missinguploadpermissions'] = 'É posible que a biblioteca exista no ficheiro que subiches pero non tes permiso para subir novas bibliotecas. Contacta co administrador do sitio.';
$string['modulename'] = 'Contido Interactivo';
$string['modulename_help'] = 'O módulo de actividade H5P permite crear contidos interactivos como Vídeos Interactivos, Conxuntos de Preguntas, Preguntas de Arrastrar e Soltar, Preguntas de Escolla Múltiple, Presentacións e moitos máis.

Ademais de ser unha ferramenta de autoría de contido enriquecido, H5P permite importar e exportar arquivos, un xeito moi eficaz de reutilizar ou compartir contido.

As interaccións do usuario e as puntuacións rastréxanse mediante xAPI e están dispoñibles no Libro de Cualificacions de Moodle. Hai que ter en conta que é posible que os usuarios con coñecementos de programación poidan facer trampa nas actividades H5P e obter a puntuación completa sen saber as respostas correctas. Non debemos usar H5P para exames ou probas similares.

O contido H5P pódese engadir creando contido coa ferramenta de autoría incluída ou subindo arquivos H5P atopados noutros sitios compatibles con H5P.';
$string['modulename_link'] = 'https://h5p.org/moodle-more-help';
$string['modulenameplural'] = 'Contido Interactivo';
$string['nextpage'] = 'Páxina seguinte';
$string['noanswersubmitted'] = 'Este usuario aínda non enviou resposta algunha para o H5P';
$string['nocontent'] = 'Non se puido ler o contido do ficheiro content.json';
$string['nocontenttype'] = 'Non se especificou o tipo de contido.';
$string['nocopyright'] = 'Non existe información de dereitos de autor para este contido.';
$string['nodata'] = 'Non hai datos dispoñibles que coincidan cos teus criterios.';
$string['noextension'] = 'O arquivo que subiches non é un paquete HTML5 válido (Non ten a extensión de arquivo .h5p)';
$string['noh5ps'] = 'Non hai contido interactivo dispoñible para este curso.';
$string['nojson'] = 'O ficheiro principal h5p.json non é válido';
$string['nombstringexteension'] = 'A extensión mbstring de PHP non está cargada. H5P precisa está extensión para funcionar correctamente';
$string['noparameters'] = 'Non hai parámetros';
$string['noparse'] = 'Non puidemos ler o ficheiro principal h5p.json';
$string['nopermissiontogettranslations'] = 'Non tes permiso para obter traducións';
$string['nopermissiontorestrict'] = 'Non tes permiso para restrinxir bibliotecas.';
$string['nopermissiontosavecontentuserdata'] = 'Non tes permiso para gardar datos de usuario do contido.';
$string['nopermissiontosaveresult'] = 'Non tes permiso para gardar o resultado deste contido.';
$string['nopermissiontoupgrade'] = 'Non tes permiso para actualizar bibliotecas.';
$string['nopermissiontouploadcontent'] = 'Non tes permiso para subir contido aquí.';
$string['nopermissiontouploadfiles'] = 'Non tes permiso para subir bibliotecas aquí.';
$string['nopermissiontoviewcontenttypes'] = 'Non tes permiso para ver os tipos de contido.';
$string['nopermissiontoviewresult'] = 'Non tes permiso para ver os resultados deste contido.';
$string['nosuchlibrary'] = 'Non existe a biblioteca';
$string['notapplicable'] = 'N/A';
$string['nounzip'] = 'O arquivo que subiches non é un paquete HTML5 válido (Non podemos descomprimilo)';
$string['noversionattribution'] = 'Recoñecemento';
$string['noversionattributionnc'] = 'Recoñecemento-Non comercial';
$string['noversionattributionncnd'] = 'Recoñecemento-Non comercial-Sen obra derivada';
$string['noversionattributionncsa'] = 'Recoñecemento-Non comercial-Compartir igual';
$string['noversionattributionnd'] = 'Recoñecemento-Sen obra derivada';
$string['noversionattributionsa'] = 'Recoñecemento-Compartir igual';
$string['nowriteaccess'] = 'Detectouse un problema co acceso de escritura do servidor. Por favor, asegúrate de que o servidor pode escribir no teu cartafol de datos.';
$string['noziparchive'] = 'A túa versión de PHP non soporta ZipArchive.';
$string['offlinedialogbody'] = 'Non puidemos enviar a información do teu progreso nesta tarefa. Por favor, comproba a túa conexión a Internet.';
$string['offlinedialogheader'] = 'Perdeuse a túa conexión co servidor';
$string['offlinedialogretrybuttonlabel'] = 'Tentar de novo agora';
$string['offlinedialogretrymessage'] = 'Tentando de novo en :num....';
$string['offlinesuccessfulsubmit'] = 'Enviáronse os resultados satisfactoriamente.';
$string['oldphpversion'] = 'A túa versión de PHP está anticuada. H5P require a versión 5.2 para funcionar correctamente. Recoméndase a versión 5.6 ou posterior.';
$string['olduploadoldcontent'] = 'Estás a intentar subir contido dunha versión antiga de H5P. Por favor, actualiza o contido no servidor no que se orixinou e intentar subilo de novo ou activa o hub H5P para que este servidor o actualice automaticamente.';
$string['onlyupdate'] = 'Actualizar só bibliotecas existentes';
$string['options'] = 'Opcións';
$string['originator'] = 'Orixinador';
$string['pd'] = 'Dominio público';
$string['pddl'] = 'Dedicación e licenza de dominio público';
$string['pdm'] = 'Marca de dominio público';
$string['pluginadministration'] = 'H5P';
$string['pluginname'] = 'H5P';
$string['postmessagerequired'] = 'Requírese a publicación dunha mensaxe para acceder ao punto final especificado';
$string['previouspage'] = 'Páxina anterior';
$string['privacy:metadata:core_files'] = 'A actividade H5P almacena ficheiros subidos como parte do contido H5P.';
$string['privacy:metadata:core_grades'] = 'A actividade H5P almacena as cualificacións dos usuarios que contestaron ao contido H5P.';
$string['privacy:metadata:hvp_content_user_data'] = 'Describe o estado dun contido determinado para un usuario. Úsase para restablecer o contido a un estado previo.';
$string['privacy:metadata:hvp_content_user_data:data'] = 'Almacenáronse os datos de usuario.';
$string['privacy:metadata:hvp_content_user_data:data_id'] = 'Identificador de tipo de datos.';
$string['privacy:metadata:hvp_content_user_data:delete_on_content_change'] = 'Marca que determina se os datos deberían borrarse cando cambia o contido.';
$string['privacy:metadata:hvp_content_user_data:hvp_id'] = 'O ID do contido H5P propietario dos datos.';
$string['privacy:metadata:hvp_content_user_data:id'] = 'O ID da relación de datos e usuario do contido.';
$string['privacy:metadata:hvp_content_user_data:preloaded'] = 'Marca que determina se deberían precargarse os datos no contido.';
$string['privacy:metadata:hvp_content_user_data:sub_content_id'] = 'Subcontido de H5P, 0 se isto non é un subcontido.';
$string['privacy:metadata:hvp_content_user_data:user_id'] = 'O ID do usuario propietario dos datos.';
$string['privacy:metadata:hvp_events'] = 'Fai un seguimento dos eventos H5P rexistrados.';
$string['privacy:metadata:hvp_events:content_id'] = 'O ID de contido sobre o que se levou a a cabo a acción, 0 se é novo ou non existe o contido.';
$string['privacy:metadata:hvp_events:content_title'] = 'Título do contido.';
$string['privacy:metadata:hvp_events:created_at'] = 'A hora á que se creou o evento.';
$string['privacy:metadata:hvp_events:id'] = 'O ID único dun evento.';
$string['privacy:metadata:hvp_events:library_name'] = 'A biblioteca á que afectou o evento.';
$string['privacy:metadata:hvp_events:library_version'] = 'A versión da biblioteca á que afectou o evento.';
$string['privacy:metadata:hvp_events:sub_type'] = 'O subtipo do evento, ou acción do evento.';
$string['privacy:metadata:hvp_events:type'] = 'O tipo de evento.';
$string['privacy:metadata:hvp_events:user_id'] = 'O ID do usuario que levou a cabo a acción.';
$string['privacy:metadata:hvp_xapi_results'] = 'Almacenar eventos xAPI no contido H5P.';
$string['privacy:metadata:hvp_xapi_results:additionals'] = 'Información adicional que pode enviar o H5P.';
$string['privacy:metadata:hvp_xapi_results:content_id'] = 'O ID do contido sobre o que se levou a cabo o evento.';
$string['privacy:metadata:hvp_xapi_results:correct_responses_pattern'] = 'O patrón de resposta correcta.';
$string['privacy:metadata:hvp_xapi_results:description'] = 'A descrición, tarefa ou pregunta do contido sobre a que se levou a cabo a acción.';
$string['privacy:metadata:hvp_xapi_results:id'] = 'O ID único do evento xAPI.';
$string['privacy:metadata:hvp_xapi_results:interaction_type'] = 'O tipo da interacción.';
$string['privacy:metadata:hvp_xapi_results:max_score'] = 'Cualificación máxima para o evento.';
$string['privacy:metadata:hvp_xapi_results:parent_id'] = 'O ID do pai do contido sobre o que se levou a cabo esta acción. Nulo se non ten pai.';
$string['privacy:metadata:hvp_xapi_results:raw_score'] = 'Cualificación arquivada para o evento.';
$string['privacy:metadata:hvp_xapi_results:response'] = 'A resposta enviada polo usuario.';
$string['privacy:metadata:hvp_xapi_results:user_id'] = 'O ID do usuario que levou a cabo a acción.';
$string['question'] = 'Pregunta';
$string['removeoldlogentries'] = 'Eliminar entradas de rexistro H5P antigas';
$string['removeoldmobileauthentries'] = 'Eliminar antigas entradas de autenticación móbil H5P';
$string['removetmpfiles'] = 'Eliminar arquivos temporais H5P antigos';
$string['reportingquestionsremaininglabel'] = 'preguntas que quedan por cualificar';
$string['reportingscaledscoredelimiter'] = ',';
$string['reportingscaledscorelabel'] = 'Puntuación do libro de cualificacións:';
$string['reportingscoredelimiter'] = 'de';
$string['reportingscorelabel'] = 'Puntuación:';
$string['reportnotsupported'] = 'Non soportado';
$string['reportsubmitgradelabel'] = 'Enviar cualificación';
$string['resizescript'] = 'Inclúe este script no teu sitio web se queres activar a redimensión dinámica do contido embebido:';
$string['resubmitscores'] = 'Intentando enviar resultados almacenados.';
$string['reuse'] = 'Reutilizar';
$string['reusecontent'] = 'Reutilizar Contido';
$string['reusedescription'] = 'Reutilizar este contido.';
$string['reveal'] = 'Revelar';
$string['reviseserversetupandretry'] = 'Cando revises a configuración do servidor, podes reactivar a comunicación co Hub H5P na configuración H5P.';
$string['score'] = 'Puntuación';
$string['search'] = 'Procurar';
$string['sendusagestatistics'] = 'Aportar estatísticas de uso';
$string['sendusagestatistics_help'] = 'Aportaranse automaticamente datos estatísticos para axudar aos expertos a entender mellor como se usa H5P e para determinar áreas potenciais  de mellora. Le máis sobre o tipo de <a {$a}>datos recollidos en h5p.org</a>.';
$string['settings'] = 'Configuración H5P';
$string['showadvanced'] = 'Amosar avanzado';
$string['showless'] = 'Amosar menos';
$string['showmore'] = 'Amosar máis';
$string['sitecouldnotberegistered'] = 'Non se puido rexistrar o sitio no hub. Por favor, contacta co administrador do sitio.';
$string['sitekey'] = 'Chave do sitio';
$string['sitekeydescription'] = 'A chave do sitio é un segredo que identifica este sitio co Hub de xeito individual.';
$string['sitekeyregistered'] = 'Acabas de recibir unha chave única que te identifica co Hub cando recibes novas actualizacións. Podes ver esta chave na páxina "Configuración H5P".';
$string['size'] = 'Tamaño';
$string['source'] = 'Orixe';
$string['sslnotenabled'] = 'O teu servidor non ten SSL activado. Deberíase activar SSL para asegurar a conexión segura co hub H5P.';
$string['startingover'] = 'Terás que empezar de novo.';
$string['sublevel'] = 'Subnivel';
$string['successfullyregisteredwithhub'] = 'O teu sitio rexistrouse no Hub H5P.';
$string['thumbnail'] = 'Miniatura';
$string['title'] = 'Título';
$string['unabletocreatedir'] = 'Imposible crear cartafol.';
$string['unabletogetfieldtype'] = 'Imposible obter o tipo do campo.';
$string['undisclosed'] = 'Non especificado';
$string['unpackedfilesexceedsmaxsize'] = 'O tamaño total dos ficheiros desempaquetados excede o tamaño máximo permitido. (%used > %max)';
$string['updatedlibraries'] = 'Actualizadas {$a->%old} bibliotecas H5P.';
$string['updatedlibrary'] = 'Actualizada {$a->%old} biblioteca H5P.';
$string['updatelibraries'] = 'Actualizar Todas as Bibliotecas';
$string['upgrade'] = 'Actualizar H5P';
$string['upgradebuttonlabel'] = 'Actualizar';
$string['upgradedone'] = 'Actualizaches {$a} elemento(s) de contido satisfactoriamente.';
$string['upgradeerror'] = 'Ocorreu un erro ao procesar os parámetros:';
$string['upgradeerrorcontent'] = 'Non se puido actualizar o contido %id:';
$string['upgradeerrordata'] = 'Non se puideron cargar datos para a biblioteca %lib.';
$string['upgradeerrormissinglibrary'] = 'Falta a biblioteca requirida %lib.';
$string['upgradeerrornotsupported'] = 'Os parámetros conteñen %used que non está soportado.';
$string['upgradeerrorparamsbroken'] = 'Os parámetros están rotos.';
$string['upgradeerrorscript'] = 'Non se puido cargar o script de actualización de %lib.';
$string['upgradeerrortoohighversion'] = 'Os parámetros conteñen %used pero sopórtanse só %supported ou anteriores.';
$string['upgradeheading'] = 'Actualizar contido {$a}';
$string['upgradeinprogress'] = 'Actualizando á %ver...';
$string['upgradeinvalidtoken'] = 'Erro: Código de seguridade non válido!';
$string['upgradelibrarycontent'] = 'Actualizar biblioteca de contidos';
$string['upgradelibrarymissing'] = 'Erro: Non se atopa a túa biblioteca!';
$string['upgrademessage'] = 'Estás a piques de actualizar {$a} elemento(s) de contido. Por favor, selecciona a versión de actualización.';
$string['upgradenoavailableupgrades'] = 'Non hai actualizacións dispoñibles para esta biblioteca.';
$string['upgradenothingtodo'] = 'Non hai elementos de contido que actualizar.';
$string['upgradereturn'] = 'Volver';
$string['upload'] = 'Subir';
$string['uploadlibraries'] = 'Subir bibliotecas';
$string['uploadsizelargerthanpostsize'] = 'O valor de PHP max upload size e maior que max post size. Sábese que isto pode causar problemas nalgunhas instalacións.';
$string['user'] = 'Usuario';
$string['validatingh5pfailed'] = 'Fallou a validación do paquete h5p.';
$string['validationfailed'] = 'O H5P solicitado non era válido';
$string['viewreportlabel'] = 'Informar';
$string['welcomecommunity'] = 'Esperamos que disfrutes con H5P e te impliques na nosa crecente comunidade por medio dos nosos<a {$a->forums}>foros</a>.';
$string['welcomecontactus'] = 'Se tes calquera tipo de comentario, non dubides en <a {$a}>contactar con nos</a>. Tomamos os comentarios moi en serio e estamos comprometidos a facer H5P mellor cada día!';
$string['welcomegettingstarted'] = 'Para iniciarte en H5P e Moodle bota unha ollada ao noso <a {$a->moodle_tutorial}>tutorial</a> e mira o <a {$a->example_content}>contido de exemplo</a> en H5P.org para inspirarte.';
$string['welcomeheader'] = 'Benvido ao mundo do H5P!';
$string['wrongversion'] = 'A versión da biblioteca H5P {$a->%machineName} usada neste contexto non é válida. O contido contén {$a->%contentLibrary}, pero debería ser {$a->%semanticsLibrary}.';
$string['year'] = 'Ano';
$string['years'] = 'Ano(s)';
$string['yearsfrom'] = 'Anos (desde)';
$string['yearsto'] = 'Anos (ata)';
