<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'workshop', language 'gl', version '3.11'.
 *
 * @package     workshop
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activitydate:assessmentsclose'] = 'Pechan as avaliacións:';
$string['activitydate:assessmentsclosed'] = 'Avaliacións pechadas:';
$string['activitydate:assessmentsopen'] = 'Abren as avaliacións:';
$string['activitydate:assessmentsopened'] = 'Avaliacións abertas:';
$string['activitydate:submissionsclose'] = 'Pechan as entregas:';
$string['activitydate:submissionsclosed'] = 'Entregas pechados:';
$string['activitydate:submissionsopen'] = 'Abren as entregas:';
$string['activitydate:submissionsopened'] = 'Entregas abertas:';
$string['aggregategrades'] = 'Volver calcular as cualificacións';
$string['aggregation'] = 'Agregación de cualificacións';
$string['allocate'] = 'Asignar entregas';
$string['allocatedetails'] = 'agardábase: {$a->expected}<br />entregouse: {$a->submitted}<br />para asignar: {$a->allocate}';
$string['allocation'] = 'Asignación de entregas';
$string['allocationconfigured'] = 'Configurada asignación';
$string['allocationdone'] = 'Feita a asignación';
$string['allocationerror'] = 'Erro de asignación';
$string['allowedfiletypesforoverallfeedback'] = 'Tipos de ficheiros permitidos como anexos a comentarios';
$string['allowedfiletypesforoverallfeedback_help'] = 'Os tipos de ficheiro permitidos como anexo de comentario poden restrinxirse escribindo unha lista separada por comas das extensións de ficheiros, por exemplo «mp4, mp3, png, jpg». Se deixa o campo baleiro, entón permítense todos os tipos de ficheiro.';
$string['allowedfiletypesforoverallfeedback_link'] = 'admin/tool/filetypes/index';
$string['allowedfiletypesforsubmission'] = 'Tipos de ficheiros permitidos como anexos a entregas';
$string['allowedfiletypesforsubmission_help'] = 'Os tipos de ficheiro permitidos como anexo de entrega poden restrinxirse escribindo unha lista separada por comas das extensións de ficheiros, por exemplo «mp4, mp3, png, jpg». Se deixa o campo baleiro, entón permítense todos os tipos de ficheiro.';
$string['allowedfiletypesforsubmission_link'] = 'admin/tool/filetypes/index';
$string['allsubmissions'] = 'Todas as entregas ({$a})';
$string['alreadygraded'] = 'Xa cualificado';
$string['areaconclusion'] = 'Texto de conclusión';
$string['areainstructauthors'] = 'Instrucións para a entrega';
$string['areainstructreviewers'] = 'Instrucións para a avaliación';
$string['areaoverallfeedbackattachment'] = 'Anexos globais de comentarios';
$string['areaoverallfeedbackcontent'] = 'Textos globais de comentarios';
$string['areasubmissionattachment'] = 'Anexos da entrega';
$string['areasubmissioncontent'] = 'Textos da entrega';
$string['assess'] = 'Avaliar';
$string['assessedexample'] = 'Entrega de exemplo avaliada';
$string['assessedsubmission'] = 'Entrega avaliada';
$string['assessingexample'] = 'Avaliando a entrega de exemplo';
$string['assessingsubmission'] = 'Avaliando a entrega';
$string['assessment'] = 'Avaliación';
$string['assessmentby'] = 'por <a href="{$a->url}">{$a->name}</a>';
$string['assessmentbyfullname'] = 'Avaliación de {$a}';
$string['assessmentbyyourself'] = 'A súa avaliación';
$string['assessmentdeleted'] = 'Avaliación desasignada';
$string['assessmentend'] = 'Data límite de avaliacións';
$string['assessmentendbeforestart'] = 'A data límite de avaliacións non pode ser anterior á data de comezo da avaliación';
$string['assessmentenddatetime'] = 'Data límite da avalición: {$a->daydatetime} ({$a->distanceday})';
$string['assessmentendevent'] = '{$a} (data límite das avaliacións)';
$string['assessmentform'] = 'Forma de avaliación';
$string['assessmentofsubmission'] = '<a href="{$a->assessmenturl}">Avaliación</a> de <a href="{$a->submissionurl}">{$a->submissiontitle}</a>';
$string['assessmentreference'] = 'Avaliación de referencia';
$string['assessmentreferenceconflict'] = 'Non é posíbel avaliar unha entrega de exemplo para que xa fixo unha avaliación de referencia.';
$string['assessmentreferenceneeded'] = 'Ten que avaliar esta entrega de exemplo, para proporcionar unha avaliación de referencia. Prema no botón «Continuar» para avaliar a entrega.';
$string['assessments'] = 'Avaliacións';
$string['assessmentsettings'] = 'Axustes da avaliación';
$string['assessmentstart'] = 'Aberto para avaliacións dende';
$string['assessmentstartdatetime'] = 'Aberto para avaliacións dende {$a->daydatetime} ({$a->distanceday})';
$string['assessmentstartevent'] = '{$a} (aberto para avaliacións)';
$string['assessmentweight'] = 'Ponderación da avaliación';
$string['assignedassessments'] = 'Entregas asignadas para avaliar';
$string['assignedassessmentsnone'] = 'Non ten entregas asignadas para avaliar';
$string['backtoeditform'] = 'Volver ao formulario de edición';
$string['byfullname'] = 'por <a href="{$a->url}">{$a->name}</a>';
$string['byfullnamewithoutlink'] = 'por {$a}';
$string['calculategradinggrades'] = 'Calcular as cualificacións da avaliación';
$string['calculategradinggradesdetails'] = 'agardábase: {$a->expected}<br />calculouse: {$a->calculated}';
$string['calculatesubmissiongrades'] = 'Calcular as cualificacións das entregas';
$string['calculatesubmissiongradesdetails'] = 'agardábase: {$a->expected}<br />calculouse: {$a->calculated}';
$string['chooseuser'] = 'Escoller un usuario...';
$string['clearaggregatedgrades'] = 'Limpar todas as cualificacións agregadas';
$string['clearaggregatedgrades_help'] = 'As cualificacións agregadas para a entrega e as cualificacións de avaliación restabeleceranse. Pode volver calcular estas cualificacións dende o principio na Fase de cualificación das avaliacións.';
$string['clearaggregatedgradesconfirm'] = 'Confirma que quere limpar as cualificacións calculadas para as entregas e as cualificacións da avaliación?';
$string['clearassessments'] = 'Limpar as avaliacións';
$string['clearassessments_help'] = 'As cualificacións calculadas para as entregas e as cualificacións de avaliación restabeleceranse. A información sobre como encher os formularios conservase, mais todos os avaliadores deberán abrir o formulario de avaliación de novo e volver gardalo, para que se calculen de novo as cualificacións.';
$string['clearassessmentsconfirm'] = 'Confirma que quere limpar todas as cualificacións de avaliación?. Non poderá volver a obter a información por vostede mesmo, os avaliadores terán que avaliar de novo as entregas asignadas.';
$string['conclusion'] = 'Conclusión';
$string['conclusion_help'] = 'O texto de conclusión amosáselle aos participantes na fin da actividade.';
$string['configexamplesmode'] = 'Modo predeterminado na avaliación dos exemplos nos obradoiros';
$string['configgrade'] = 'Cualificación máxima predeterminada para as entregas nos obradoiros';
$string['configgradedecimals'] = 'Número predeterminados de díxitos que se deberían amosar após o punto decimal ao amosar as cualificacións.';
$string['configgradinggrade'] = 'Cualificación máxima predeterminada para a avaliación nos obradoiros';
$string['configmaxbytes'] = 'O tamaño máximo predeterminado do ficheiro entregado para todos os obradoiros (suxeito ao límite do curso e a outros axustes locais)';
$string['configstrategy'] = 'Estratexia de cualificación predeterminada para os obradoiros';
$string['createsubmission'] = 'Engadir entrega';
$string['crontask'] = 'Procesamento en segundo plano para o módulo de obradoiro';
$string['daysago'] = 'hai {$a} días';
$string['daysleft'] = 'restan {$a} días';
$string['daystoday'] = 'hoxe';
$string['daystomorrow'] = 'mañá';
$string['daysyesterday'] = 'onte';
$string['deadlinesignored'] = 'A vostede non se lle aplican as restricións de tempo';
$string['deletesubmission'] = 'Eliminar a entrega';
$string['editassessmentform'] = 'Editar o formato de avaliación';
$string['editassessmentformstrategy'] = 'Editar o formato de avaliación ({$a})';
$string['editingassessmentform'] = 'Editando o formato de avaliación';
$string['editingsubmission'] = 'Editando a entrega';
$string['editsubmission'] = 'Editar entrega';
$string['err_multiplesubmissions'] = 'Mentres se estaba a editar este formulario, gardouse outra versión da entrega. Non se permiten entregas múltiples por usuario.';
$string['err_removegrademappings'] = 'Non é posíbel retirar as asignacións de cualificacións non usadas';
$string['evaluategradeswait'] = 'Agarde ata que se teñan feito as avaliacións e calculado as cualificacións';
$string['evaluation'] = 'Cualificación das avaliacións';
$string['evaluationmethod'] = 'Método de avaliación das cualificacións';
$string['evaluationmethod_help'] = 'O método de cualificación das avaliacións determina como se calculan as cualificacións nas avaliacións. Pode deixar que se volvan calcular as cualificacións segundo diferentes axustes a non ser que xa estea satisfeito co resultado.';
$string['evaluationsettings'] = 'Axustes da cualificación das avaliacións';
$string['eventassessableuploaded'] = 'Foi enviada unha entrega.';
$string['eventassessmentevaluated'] = 'Avaliación verificada';
$string['eventassessmentevaluationsreset'] = 'Restabelecer as verificacións de avaliacións';
$string['eventassessmentreevaluated'] = 'Avaliación verificada de novo';
$string['eventphaseautomaticallyswitched'] = 'Fase cambiada automaticamente';
$string['eventphaseswitched'] = 'Fase cambiada';
$string['eventsubmissionassessed'] = 'Entrega avaliada';
$string['eventsubmissionassessmentsreset'] = 'Limpadas as avaliacións das entregas';
$string['eventsubmissioncreated'] = 'Entrega creada';
$string['eventsubmissiondeleted'] = 'Entregas eliminadas';
$string['eventsubmissionreassessed'] = 'Entrega avaliada de novo';
$string['eventsubmissionupdated'] = 'Entrega actualizada';
$string['eventsubmissionviewed'] = 'Entrega vista';
$string['example'] = 'Entrega de exemplo';
$string['exampleadd'] = 'Engadir unha entrega de exemplo';
$string['exampleassess'] = 'Avaliar a entrega de exemplo';
$string['exampleassessments'] = 'Entregas de exemplo para avaliar';
$string['exampleassesstask'] = 'Avaliar exemplos';
$string['exampleassesstaskdetails'] = 'agardábase: {$a->expected}<br />avaliouse: {$a->assessed}';
$string['examplecomparing'] = 'Comparación das avaliacións da entrega de exemplo';
$string['exampledelete'] = 'Eliminar o exemplo';
$string['exampledeleteconfirm'] = 'Confirma que quere eliminar a seguinte entrega de exemplo? Prema no botón «Continuar» para eliminar a entrega.';
$string['exampleedit'] = 'Editar o exemplo';
$string['exampleediting'] = 'Editando o exemplo';
$string['exampleneedassessed'] = 'O primeiro que ten que facer é avaliar os exemplos';
$string['exampleneedsubmission'] = 'Debe enviar o seu traballo e avaliar todos os entregas de exemplo primeiro';
$string['examplesbeforeassessment'] = 'Os exemplos estarán dispoñíbeis após enviar a súa propia entrega, e teñen que ser avaliados antes da avaliación por pares';
$string['examplesbeforesubmission'] = 'Debe avaliar os exemplos antes da entrega propia';
$string['examplesmode'] = 'Modo de avaliación de exemplos';
$string['examplesubmissions'] = 'Entregas de exemplo';
$string['examplesvoluntary'] = 'A avaliación de entregas de exemplo é voluntaria';
$string['exportsubmission'] = 'Exportar esta páxina';
$string['feedbackauthor'] = 'Comentario para o autor';
$string['feedbackauthorattachment'] = 'Anexo';
$string['feedbackby'] = 'Comentario por {$a}';
$string['feedbackreviewer'] = 'Comentario para o revisor';
$string['feedbacksettings'] = 'Comentarios';
$string['formataggregatedgrade'] = '{$a->grade}';
$string['formataggregatedgradeover'] = '<del>{$a->grade}</del><br /><ins>{$a->over}</ins>';
$string['formatpeergrade'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span>';
$string['formatpeergradeover'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span>';
$string['formatpeergradeoverweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span> @ <span class="weight">{$a->weight}</span>';
$string['formatpeergradeweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span> @ <span class="weight">{$a->weight}</span>';
$string['givengrades'] = 'Cualificacións outorgadas';
$string['grade_grading_name'] = 'Avaliación';
$string['grade_submission_name'] = 'Entrega';
$string['gradecalculated'] = 'Cualificación calculada para a entrega';
$string['gradedecimals'] = 'Posicións decimais nas cualificacións';
$string['gradegivento'] = '&gt;';
$string['gradeinfo'] = 'Cualificación: {$a->received} de {$a->max}';
$string['gradeitemassessment'] = '{$a->workshopname} (avaliación)';
$string['gradeitemsubmission'] = '{$a->workshopname} (entrega)';
$string['gradeover'] = 'Anular a cualificación da entrega';
$string['gradereceivedfrom'] = '&lt;';
$string['gradesreport'] = 'Informe de cualificacións do obradoiro';
$string['gradetopassgrading'] = 'Cualificación aprobatoria de avaliación';
$string['gradetopasssubmission'] = 'Cualificación aprobatoria de entregas';
$string['gradinggrade'] = 'Cualificación da avaliación';
$string['gradinggrade_help'] = 'Este axuste especifica a cualificación máxima que pode obterse na avaliación dunha entrega.';
$string['gradinggradecalculated'] = 'Cualificación calculada da avaliación';
$string['gradinggradeof'] = 'Cualificación da avaliación (de {$a})';
$string['gradinggradeover'] = 'Anular a cualificación da avaliación';
$string['gradingsettings'] = 'Axustes da cualificación';
$string['groupnoallowed'] = 'Non se lle permite acceder a ningún grupo neste obradoiro';
$string['iamsure'] = 'Si, confirmo';
$string['indicator:cognitivedepth'] = 'Obradoiro cognitivo';
$string['indicator:cognitivedepth_help'] = 'Este indicador está baseado na profundidade cognitiva acadada polo alumno nunha actividade de obradoiro.';
$string['indicator:cognitivedepthdef'] = 'Obradoiro cognitivo';
$string['indicator:cognitivedepthdef_help'] = 'O participante acadou esta porcentaxe do compromiso cognitivo que ofrecen as actividades de Obradoiro durante este intervalo de análise (Niveis = Sen vista, Ver, Entregar, Ver comentarios, Facer comentarios, Reenviar após ver comentarios)';
$string['indicator:cognitivedepthdef_link'] = 'Indicadores_de_aprendizaxe_analítico#Profundidade_cognitiva';
$string['indicator:socialbreadth'] = 'Obradoiro social';
$string['indicator:socialbreadth_help'] = 'Este indicador está baseado na amplitude social acadada polo alumno nunha actividade de obradoiro.';
$string['indicator:socialbreadthdef'] = 'Obradoiro social';
$string['indicator:socialbreadthdef_help'] = 'O participante acadou esta porcentaxe do compromiso social que ofrecen as actividades de Obradoiro durante este intervalo de análise (Niveis = Sen participación, Participante en solitario, Participante con outros)';
$string['indicator:socialbreadthdef_link'] = 'Indicadores_de_aprendizaxe_analítico#Amplitude_social';
$string['info'] = 'Información';
$string['instructauthors'] = 'Instrucións para a entrega';
$string['instructreviewers'] = 'Instrucións para a avaliación';
$string['introduction'] = 'Descrición';
$string['latesubmissions'] = 'Entregas atrasadas';
$string['latesubmissions_desc'] = 'Permitir entregas fora de prazo';
$string['latesubmissions_help'] = 'De estar activado, un autor pode entregar o seu traballo após a data límite de entrega ou durante a fase de avaliación. As entregas posteriores non se poden editar.';
$string['latesubmissionsallowed'] = 'Permítense entregas atrasadas';
$string['legacyallocationplugincron'] = 'Asignación de obradoiro por cron legado';
$string['maxbytes'] = 'Tamaño máximo de anexo na entrega';
$string['modulename'] = 'Obradoiro';
$string['modulename_help'] = 'O módulo de actividade Obradoiro activa a recollida, revisión e avaliación por pares do traballo dos alumnos.

Os alumnos poden entregar calquera contido dixital (ficheiros) tales como documentos procesados por palabras ou follas de cálculo e tamén poden escribir directamente dentro dun campo utilizando o editor de texto.

As entregas son avaliadas utilizando un formulario de avaliación multicriterio definido polo profesor. O proceso de avaliación por pares e a comprensión do formulario de avaliación pódese practicar previamente con exemplos de entregas fornecidas polo profesor, xunto cunha avaliación de referencia. Aos alumnos dáselles a oportunidade de avaliar unha ou máis das entregas dos seus pares. As entregas e os revisores poden ser anónimos se se require.

Os alumnos obteñen dúas cualificacións nunha actividade de seminario, unha cualificación pola súa entrega e outra pola avaliación das entregas dos seus pares. Ámbalas cualificacións gárdanse no libro de cualificacións.';
$string['modulename_link'] = 'mod/workshop/view';
$string['modulenameplural'] = 'Obradoiros';
$string['myassessments'] = 'As miñas avaliacións';
$string['mysubmission'] = 'A miña entrega';
$string['nattachments'] = 'Número máximo de anexos por entrega';
$string['noexamples'] = 'Aínda non hai exemplos neste obradoiro';
$string['noexamplesformready'] = 'Debe definir a forma de avaliación antes de proporcionar entregas de exemplo';
$string['nogradeyet'] = 'Aínda non hai cualificación';
$string['nosubmissionfound'] = 'Non se atoparon entregas deste usuario';
$string['nosubmissions'] = 'Aínda non hai entregas neste obradoiro';
$string['nosubmissiontype'] = 'Polo menos debe estar dispoñíbel un tipo de entrega';
$string['notassessed'] = 'Aínda sen avaliar';
$string['nothingfound'] = 'Nada para presentar';
$string['nothingtoreview'] = 'Non hai nada que revisar';
$string['notoverridden'] = 'Sen anular';
$string['noworkshops'] = 'Non hai obradoiros neste curso';
$string['noyoursubmission'] = 'Aínda non entregou o seu traballo';
$string['nullgrade'] = '-';
$string['overallfeedback'] = 'Retroalimentación xeral';
$string['overallfeedbackfiles'] = 'Número máximo de anexos globais de comentarios';
$string['overallfeedbackmaxbytes'] = 'Tamaño máximo de anexos globais de comentarios';
$string['overallfeedbackmode'] = 'Mo do de comentario global';
$string['overallfeedbackmode_0'] = 'Desactivado';
$string['overallfeedbackmode_1'] = 'Activado e opcional';
$string['overallfeedbackmode_2'] = 'Activado e requirido';
$string['overallfeedbackmode_help'] = 'Se está activado, aparecerá un campo de texto na parte inferior do formulario de avaliación. Os revisores poderán poñer nel a avaliación global da entrega, ou proporcionar unha explicación adicional da súa avaliación.';
$string['page-mod-workshop-x'] = 'Calquera páxina do módulo de obradoiro';
$string['participant'] = 'Participante';
$string['participantrevierof'] = 'O participante é revisor de';
$string['participantreviewedby'] = 'O participante é revisado por';
$string['phaseassessment'] = 'Fase de avaliación';
$string['phaseclosed'] = 'Pechada';
$string['phaseevaluation'] = 'Fase de cualificación das avaliacións';
$string['phasesetup'] = 'Fase de configuración';
$string['phasesoverlap'] = 'A fase de entrega e a fase de avaliación, non poden solaparse';
$string['phasesubmission'] = 'Fase de entrega';
$string['pluginadministration'] = 'Administración do obradoiro';
$string['pluginname'] = 'Obradoiro';
$string['prepareexamples'] = 'Preparar unha entrega de exemplo';
$string['previewassessmentform'] = 'Vista previa';
$string['privacy:metadata:aggregatedgradinggrade'] = 'Cualificacións agregadas para todas as avaliacións realizadas polo usuario na actividade de obradoiro dada';
$string['privacy:metadata:assessmentgrade'] = 'Cualificación agregada para a entrega suxerido por esta avaliación';
$string['privacy:metadata:assessmentgradinggrade'] = 'Cualificación para fornecer esta avaliación';
$string['privacy:metadata:assessmentgradinggradeover'] = 'Valor anulado manualmente da cualificación para fornecer esta avaliación';
$string['privacy:metadata:assessmentid'] = 'ID da avaliación';
$string['privacy:metadata:authorid'] = 'ID do autor da entrega';
$string['privacy:metadata:dimensiongrade'] = 'Cualificación na dimensión de avaliación dada';
$string['privacy:metadata:dimensionid'] = 'ID da dimensión de avaliación';
$string['privacy:metadata:example'] = 'Indica se este rexistro representa unha entrega de exemplo';
$string['privacy:metadata:feedbackauthor'] = 'Comentario para o autor';
$string['privacy:metadata:feedbackauthorformat'] = 'Formato de texto dos comentarios para o autor';
$string['privacy:metadata:feedbackreviewer'] = 'Comentarios para o usuario que fornece a avaliación';
$string['privacy:metadata:feedbackreviewerformat'] = 'Formato de texto dos comentarios para o usuario que fornece a avaliación';
$string['privacy:metadata:late'] = 'Se a presentación foi presentada após o prazo';
$string['privacy:metadata:peercomment'] = 'Comentario sobre a cualificación dada polo usuario que fornece a avaliación';
$string['privacy:metadata:peercommentformat'] = 'Formato de texto do comentario na cualificación dada';
$string['privacy:metadata:preference:perpage'] = 'Número de entregas que o usuario prefire ver nunha páxina';
$string['privacy:metadata:preference:viewlet-allexamples-collapsed'] = 'O estado contraído/expandido para o visor «Entregas de exemplos»';
$string['privacy:metadata:preference:viewlet-allsubmissions-collapsed'] = 'O estado contraído/expandido para o visor «Informe de entregas do obradoiro»';
$string['privacy:metadata:preference:viewlet-assessmentform-collapsed'] = 'O estado contraído/expandido para o visor «Formulario de avaliación»';
$string['privacy:metadata:preference:viewlet-assignedassessments-collapsed'] = 'O estado contraído/expandido para o visor «Entregas asignadas para avaliar»';
$string['privacy:metadata:preference:viewlet-cleargrades-collapsed'] = 'O estado contraído/expandido para o visor « Caixa de ferramentas do obradoiro»';
$string['privacy:metadata:preference:viewlet-conclusion-collapsed'] = 'O estado contraído/expandido para o visor «Conclusión»';
$string['privacy:metadata:preference:viewlet-examples-collapsed'] = 'O estado contraído/expandido para o visor «Entregas de exemplo para avaliar»';
$string['privacy:metadata:preference:viewlet-examplesfail-collapsed'] = 'O estado contraído/expandido para o visor «Entregas de exemplo para avaliar»';
$string['privacy:metadata:preference:viewlet-gradereport-collapsed'] = 'O estado contraído/expandido para o visor «Informe de cualificacións do obradoiro»';
$string['privacy:metadata:preference:viewlet-instructauthors-collapsed'] = 'O estado contraído/expandido para o visor «Instrucións para a entrega»';
$string['privacy:metadata:preference:viewlet-instructreviewers-collapsed'] = 'O estado contraído/expandido para o visor «Instrucións para a avaliación»';
$string['privacy:metadata:preference:viewlet-intro-collapsed'] = 'O estado contraído/expandido para o visor «Introdución»';
$string['privacy:metadata:preference:viewlet-overallfeedback-collapsed'] = 'O estado contraído/expandido para o visor «Comentarios xerais»';
$string['privacy:metadata:preference:viewlet-ownsubmission-collapsed'] = 'O estado contraído/expandido para o visor «A súa entrega»';
$string['privacy:metadata:preference:viewlet-publicsubmissions-collapsed'] = 'O estado contraído/expandido para o visor «Entregas publicadas»';
$string['privacy:metadata:preference:viewlet-yourgrades-collapsed'] = 'O estado contraído/expandido para o visor «As súas cualificacións»';
$string['privacy:metadata:published'] = 'Se a entrega debe ser publicada a todos os participantes unha vez que o obradoiro estea pechado';
$string['privacy:metadata:reviewerid'] = 'ID do usuario que fornece a avaliación';
$string['privacy:metadata:strategy'] = 'Nome do subgrupo de estratexia de cualificación que interpreta os valores de rexistro';
$string['privacy:metadata:submissioncontent'] = 'Contido da entrega';
$string['privacy:metadata:submissioncontentformat'] = 'Formato de texto do contido da entrega';
$string['privacy:metadata:submissiongrade'] = 'Cualificación agregada para a entrega escrita como un número decimal do intervalo 0..100';
$string['privacy:metadata:submissiongradeover'] = 'Valor anulado manualmente da cualificación agregada';
$string['privacy:metadata:submissionid'] = 'ID da entrega';
$string['privacy:metadata:submissiontitle'] = 'Titulo da entrega';
$string['privacy:metadata:subsystem:corefiles'] = 'O módulo de obradoiro almacena ficheiros incrustados en /anexados ao texto da entrega';
$string['privacy:metadata:subsystem:coreplagiarism'] = 'O módulo de obradoiro ten compatibilidade integrada para os sistemas de prevención de plaxio';
$string['privacy:metadata:timeaggregated'] = 'Cando foi calculada por última vez a cualificación agregada';
$string['privacy:metadata:timecreated'] = 'Cando este rexistro foi creado na base de datos';
$string['privacy:metadata:timemodified'] = 'Cando este rexistro foi modificado por última vez na base de datos';
$string['privacy:metadata:userid'] = 'ID do usuario para o que se calcula a cualificación agregada';
$string['privacy:metadata:weight'] = 'Ponderación da avaliación';
$string['privacy:metadata:workshopaggregations'] = 'Contén as cualificacións agregadas para avaliación';
$string['privacy:metadata:workshopassessments'] = 'Contén información sobre as avaliacións asignadas das entregas do módulo de obradoiro';
$string['privacy:metadata:workshopgrades'] = 'Contén información sobre como se completaron os formularios de avaliación con cualificacións e comentarios';
$string['privacy:metadata:workshopid'] = 'ID da actividade do obradoiro';
$string['privacy:metadata:workshopsubmissions'] = 'Contén información sobre as entregas do módulo de obradoiro';
$string['privacy:request:delete:content'] = 'O contido foi eliminado (a pedimento do usuario ou por ter caducado)';
$string['privacy:request:delete:title'] = '[Eliminado]';
$string['publishedsubmissions'] = 'Entregas publicadas';
$string['publishsubmission'] = 'Publicar a entrega';
$string['publishsubmission_help'] = 'As entregas publicadas estarán dispoñíbeis para os demais cando o obradoiro estea pechado.';
$string['reassess'] = 'Avaliar novamente';
$string['receivedgrades'] = 'Cualificacións recibidas';
$string['recentassessments'] = 'Avaliacións do obradoiro:';
$string['recentsubmissions'] = 'Entregas do obradoiro:';
$string['resetassessments'] = 'Eliminar todas as avaliacións';
$string['resetassessments_help'] = 'Vostede pode escoller eliminar soamente as avaliacións asignadas sen afectar as entregas. De eliminarse entregas, as súas avaliacións serán eliminadas implicitamente e esta opción é ignorada. Teña en conta que isto tamén inclúe ás avaliacións de entregas de exemplo.';
$string['resetphase'] = 'Cambiar para a fase de configuración';
$string['resetphase_help'] = 'Se activa isto, todos os obradoiros poranse na fase de configuración inicial.';
$string['resetsubmissions'] = 'Eliminar todas as entregas';
$string['resetsubmissions_help'] = 'Todas as entregas e as súas avaliacións van ser eliminadas. isto non afecta ás entregas de exemplo.';
$string['saveandclose'] = 'Gardar e pechar';
$string['saveandcontinue'] = 'Garda e continuar editando';
$string['saveandpreview'] = 'Gardar e facer unha vista previa';
$string['saveandshownext'] = 'Gardar e amosar o seguinte';
$string['search:activity'] = 'Obradoiro - información de actividade';
$string['selfassessmentdisabled'] = 'Auto-avaliación desactivada';
$string['showingperpage'] = 'Amosando {$a} elementos por páxina';
$string['showingperpagechange'] = 'Cambiar ...';
$string['someuserswosubmission'] = 'Canda menos un autor aínda non entregou o seu traballo';
$string['sortasc'] = 'Orde ascendente';
$string['sortdesc'] = 'Orde descendente';
$string['strategy'] = 'Estratexia de cualificación';
$string['strategy_help'] = 'A estratexia de cualificación determina a forma de avaliación utilizada e o método de cualificación das entregas. Hai 4 opcións:

 * Cualificación acumulativa - Realízanse comentarios e cualificacións sobre os aspectos especificados.
 * Comentarios - Fanse comentarios sobre aspectos específicos, mais non se outorga cualificación.
 * Número de erros - Realízanse comentarios e unha cualificación tipo si/non sobre as afirmacións realizadas.
 * Rúbrica - Realizase unha avaliación de nivel respecto aos criterios especificados';
$string['strategyhaschanged'] = 'A estratexia de cualificación do obradoiro cambiou dende que foi aberto o formato para editalo.';
$string['submission'] = 'Entrega';
$string['submissionattachment'] = 'Anexo';
$string['submissionby'] = 'Entregado por {$a}';
$string['submissioncontent'] = 'Contido da entrega';
$string['submissiondeleteconfirm'] = 'Confirma que quere eliminar as seguintes entregas?';
$string['submissiondeleteconfirmassess'] = 'Confirma que quere eliminar as seguintes entregas? Observe que isto tamén eliminará {$a->count} avaliacións asociadas con esta entrega, o que pode afectar as cualificacións dos revisores.';
$string['submissionend'] = 'Fin das entregas';
$string['submissionendbeforestart'] = 'A data límite para as entregas non pode especificarse como anterior a data na se abre o prazo de entrega';
$string['submissionenddatetime'] = 'Data límite da entrega: {$a->daydatetime} ({$a->distanceday})';
$string['submissionendevent'] = '{$a} fin das entregas';
$string['submissionendswitch'] = 'Cambiar para a seguinte fase após a data límite para entregas';
$string['submissionendswitch_help'] = 'Se especifica a data límite para as entregas e esta caixa está marcada, o obradoiro cambiará automaticamente a fase de avaliación após a data límite de entregas.

Se activa esta característica, recomendase que defina tamén o método de asignación programada. Se non se asignan as entregas, non é posíbel facer avaliacións incluso se o obradoiro estiver en fase de avaliación.';
$string['submissiongrade'] = 'Cualificación para a entrega';
$string['submissiongrade_help'] = 'Este axuste especifica a cualificación máxima que pode obterse polo traballo entregado.';
$string['submissiongradeof'] = 'Cualificación para a entrega (de {$a})';
$string['submissionlastmodified'] = 'Última modificación';
$string['submissionrequiredcontent'] = 'Debe introducir algún texto ou engadir un ficheiro.';
$string['submissionrequiredfile'] = 'Debe engadir un ficheiro ou introducir algún texto.';
$string['submissionsettings'] = 'Axuste de entregas';
$string['submissionsreport'] = 'Informe de entregas do obradoiro:';
$string['submissionstart'] = 'Comezo da entregas de';
$string['submissionstartdatetime'] = 'Aberto para entregas dende {$a->daydatetime} ({$a->distanceday})';
$string['submissionstartevent'] = '{$a} comezo das entregas';
$string['submissiontitle'] = 'Título';
$string['submissiontypedisabled'] = 'Este tipo de entrega está desactivado para este obradoiro.';
$string['submissiontypefileavailable'] = 'Ficheiro anexo<span class="accesshide"> dispoñíbel</span>';
$string['submissiontypefilerequired'] = '<span class="accesshide">Ficheiro anexo </span>requirido';
$string['submissiontypes'] = 'Tipos de entrega';
$string['submissiontypetextavailable'] = 'Texto en liña<span class="accesshide"> dispoñíbel</span>';
$string['submissiontypetextrequired'] = '<span class="accesshide">Texto en liña </span>Requirido';
$string['submittednotsubmitted'] = 'Entregado ({$a->submitted}) / en entregar ({$a->notsubmitted})';
$string['subplugintype_workshopallocation'] = 'Método de asignación de entregas';
$string['subplugintype_workshopallocation_plural'] = 'Métodos de asignación de entregas';
$string['subplugintype_workshopeval'] = 'Método de avaliación das cualificacións';
$string['subplugintype_workshopeval_plural'] = 'Métodos de avaliación das cualificacións';
$string['subplugintype_workshopform'] = 'Estratexia de cualificación';
$string['subplugintype_workshopform_plural'] = 'Estratexias das cualificacións';
$string['switchingphase'] = 'Cambiando a fase';
$string['switchphase'] = 'Cambiar a fase';
$string['switchphase10'] = 'Cambiar para a fase de configuración';
$string['switchphase10info'] = 'Está a piques de cambiar o obradoiro a <strong>Fase de instalación</strong>. Nesta fase, os usuarios non poden modificar a súa entrega ou as súas avaliacións. Os profesores poden usar esta fase para cambiar os axustes do obradoiro e modificar a estratexia de cualificación ou a forma de avaliación.';
$string['switchphase20'] = 'Cambiar para a fase de entrega';
$string['switchphase20info'] = 'Está a piques de cambiar o obradoiro a <strong>Fase de entrega</strong>. Nesta fase, os alumnos poden enviar os seus traballos (dentro dos prazos de control de acceso existentes, se foron estabelecidos). Os profesores poden asignar entregas para ser revisadas por pares.';
$string['switchphase30'] = 'Cambiar para a fase de avaliación';
$string['switchphase30auto'] = 'O obradoiro cambiará automaticamente a fase de avaliación após {$a->daydatetime} ({$a->distanceday})';
$string['switchphase30info'] = 'Está a piques de cambiar o obradoiro a <strong>Fase de avaliación</strong>. Nesta fase, os revisores poden avaliar os traballos que lles foron asignados (dentro dos prazos de control de acceso existentes, se foron estabelecidos).';
$string['switchphase40'] = 'Cambiar para a fase de cualificación';
$string['switchphase40info'] = 'Está a piques de cambiar o obradoiro a <strong>Fase de cualificación das avaliacións</strong> do obradoiro. Nesta fase, os usuarios non poden modificar as súas entregas ou as avaliacións. Os profesores poden empregar as ferramentas de cualificación de avaliacións para calcular as cualificacións finais e fornecer comentarios para os revisores.';
$string['switchphase50'] = 'Pechar obradoiro';
$string['switchphase50info'] = 'Está a piques de pechar o obradoiro. Isto dará como resultado que as cualificacións calculadas aparecerán no libro de cualificacións. Os alumnos poden ver as súas entregas e as avaliacións destas.';
$string['switchphaseauto'] = 'Foi programado o cambio';
$string['switchphasenext'] = 'Cambiar para a fase de seguinte';
$string['taskassesspeers'] = 'Avaliar pares';
$string['taskassesspeersdetails'] = 'total: {$a->total}<br />pendente: {$a->todo}';
$string['taskassessself'] = 'Avaliarse a un mesmo';
$string['taskconclusion'] = 'Proporcionar unha conclusión da actividade';
$string['taskdone'] = 'Tarefa feita';
$string['taskfail'] = 'Fallou a tarefa';
$string['taskinfo'] = 'Información da tarefa';
$string['taskinstructauthors'] = 'Proporcionar instrucións para a entrega';
$string['taskinstructreviewers'] = 'Proporcionar instrucións para a avaliación';
$string['taskintro'] = 'Estabelecer a descrición do obradoiro';
$string['tasksubmit'] = 'Entregar o seu trabllo';
$string['tasktodo'] = 'Tarefa a facer';
$string['toolbox'] = 'Caixa de ferramentas do obradoiro';
$string['undersetup'] = 'Estase a configurar o obradoiro. Agarde ata que cambie á seguinte fase.';
$string['useexamples'] = 'Empregar exemplos';
$string['useexamples_desc'] = 'Proporciónanse exemplos de entregas para practicar a avaliación';
$string['useexamples_help'] = 'Si está activado, os usuarios poden practicar a avaliación sobre unha ou máis entregas de exemplo e comparar a súa avaliación cunha avaliación de referencia. Esta cualificación non contabiliza para a cualificación da avaliación.';
$string['usepeerassessment'] = 'Empregar a avaliación por pares';
$string['usepeerassessment_desc'] = 'Os alumnos poden avaliar o traballo dos outros';
$string['usepeerassessment_help'] = 'Se está activado, un usuario pode recibir entregas doutros usuarios para avalialas e recibirá una cualificación pola avaliación, ademais dunha cualificación pola propia entrega.';
$string['userdatecreated'] = 'entregado o <span>{$a}</span>';
$string['userdatemodified'] = 'modificado o <span>{$a}</span>';
$string['userplan'] = 'Planificador do obradoiro';
$string['userplan_help'] = 'O planificador do obradoiro amosa todas as fases da actividade e a lista de tarefas de cada fase. A fase actual vese resaltada e indícanse as tarefas rematadas cunha marca de verificación';
$string['userplanaccessibilityskip'] = 'Saltar ata as tarefas actuais';
$string['userplanaccessibilitytitle'] = 'Liña de tempo do obradoiro con {$a} fases';
$string['userplancurrentphase'] = 'Fase actual';
$string['useselfassessment'] = 'Empregar a autoavaliación';
$string['useselfassessment_desc'] = 'Os alumnos poden avaliar o seu propio traballo';
$string['useselfassessment_help'] = 'Se está activado, un usuario pode ser asignado a sua propia entrega para avaliala e recibirá una cualificación pola avaliación, ademais dunha cualificación pola propia entrega.';
$string['viewworkshopsummary'] = 'Ver o resumo do obradoiro';
$string['weightinfo'] = 'Ponderación: {$a}';
$string['withoutsubmission'] = 'Revisor sen entrega propia';
$string['workshop:addinstance'] = 'Engadir un novo obradoiro';
$string['workshop:allocate'] = 'Asignar entregas para revisar';
$string['workshop:deletesubmissions'] = 'Eliminar entregas';
$string['workshop:editdimensions'] = 'Editar o formato de avaliación';
$string['workshop:exportsubmissions'] = 'Exportar entregas';
$string['workshop:ignoredeadlines'] = 'Ignorar as restricións de tempo';
$string['workshop:manageexamples'] = 'Administrar as entregas de exemplo';
$string['workshop:overridegrades'] = 'Anular as cualificacións calculadas';
$string['workshop:peerassess'] = 'Avaliar por pares';
$string['workshop:publishsubmissions'] = 'Publicar as entregas';
$string['workshop:submit'] = 'Entregar';
$string['workshop:switchphase'] = 'Cambiar a fase';
$string['workshop:view'] = 'Ver o obradoiro';
$string['workshop:viewallassessments'] = 'Ver todas as avaliacións';
$string['workshop:viewallsubmissions'] = 'Ver todas as entregas';
$string['workshop:viewauthornames'] = 'Ver os nomes dos autores';
$string['workshop:viewauthorpublished'] = 'Ver os autores das entregas publicadas';
$string['workshop:viewpublishedsubmissions'] = 'Ver as entregas publicadas';
$string['workshop:viewreviewernames'] = 'Ver os nomes dos revisores';
$string['workshopname'] = 'Nome do obradoiro';
$string['yourassessmentfor'] = 'A súa avaliación para {$a}';
$string['yourgrades'] = 'A súa cualificación';
$string['yoursubmission'] = 'A súa entrega';
$string['yoursubmissionwithassessments'] = 'A súa entraga con avaliacións';
