<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'calendar', language 'ur', version '4.4'.
 *
 * @package     calendar
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activityevent'] = 'سرگرمی کی تقریب';
$string['addevent'] = 'تقاریب شامل کریں';
$string['advancedoptions'] = 'جدید انتخابات';
$string['allday'] = 'سارا دن';
$string['annually'] = 'سالانہ';
$string['calendar'] = 'کیلنڈر';
$string['calendarheading'] = '{$a} کیلنڈر';
$string['calendarpreferences'] = 'کیلنڈر کی ترجیحات';
$string['calendartypes'] = 'کیلنڈر کی اقسام';
$string['category'] = 'زمرہ';
$string['categoryevent'] = 'زمرہ کی تقریب';
$string['categoryevents'] = 'زمرہ کی تقاریب';
$string['clickhide'] = 'چھپانے کے لیے کلک کریں';
$string['clickshow'] = 'سامنے لانے کیلیے کلک کریں';
$string['colactions'] = 'اعمال';
$string['colcalendar'] = 'کیلنڈر';
$string['collastupdated'] = 'آخری بار اپ ڈیٹ کیا گیا';
$string['colpoll'] = 'اپ ڈیٹ';
$string['commontasks'] = 'انتخابات';
$string['confirmeventdelete'] = 'کیا آپ واقعی "{$a}" تقریب کو حذف کرنا چاہتے ہیں؟';
$string['confirmeventseriesdelete'] = '"{$a->name}" تقریب ایک سیریز کا حصہ ہے۔ کیا آپ صرف اس تقریب کو، یا سیریز کی تمام {$a->count} تقاریب کو حذف کرنا چاہتے ہیں؟';
$string['course'] = 'کورس';
$string['coursecalendar'] = '{$a} کیلنڈر';
$string['courseevent'] = 'کورس کی تقریب';
$string['courseevents'] = 'کورس کی تقاریب';
$string['courses'] = 'کورسز';
$string['customexport'] = 'حسب ضرورت رینج ({$a->timestart} - {$a->timeend})';
$string['daily'] = 'روزانہ';
$string['day'] = 'دن';
$string['dayeventsmany'] = '{$a->num} تقاریب، {$a->day}';
$string['dayeventsnone'] = 'کوئی تقریب نہیں، {$a}';
$string['dayeventsone'] = '1 تقریب، {$a}';
$string['daynext'] = 'اگلے دن';
$string['dayprev'] = 'گزرا ہوا دن';
$string['dayviewfor'] = 'دن کا منظر برائے:';
$string['dayviewtitle'] = 'دن کا منظر: {$a}';
$string['daywithnoevents'] = 'آج کوءی تقریب نہیں ہے۔';
$string['default'] = 'بنیادی';
$string['deleteallevents'] = 'تمام تقاریب کو حذف کریں';
$string['deleteevent'] = 'تقریب کو حذف کریں';
$string['deleteevents'] = 'تقاریب کو حذف کریں';
$string['deleteoneevent'] = 'اس تقریب کو حذف کریں';
$string['detailedmonthviewfor'] = 'تفصیلی ماہ کا نظارہ برائے:';
$string['detailedmonthviewtitle'] = 'مہینے کا تفصیلی منظر: {$a}';
$string['durationminutes'] = 'مدت، منٹوں میں';
$string['durationnone'] = 'مدت کے بغیر';
$string['durationuntil'] = 'تاوقتیکہ';
$string['editevent'] = 'تقریب میں ردوبدل ہو رہا ہے';
$string['erroraddingevent'] = 'تقریب شامل کرنے میں ناکام';
$string['errorbadsubscription'] = 'کیلنڈر کی رکنیت نہیں ملی۔';
$string['errorbeforecoursestart'] = 'کورس شروع ہونے کی تاریخ سے پہلے تقریب سیٹ نہیں کیا جا سکتی';
$string['errorcannotimport'] = 'آپ اس وقت کیلنڈر سبسکرپشن ترتیب نہیں دے سکتے۔';
$string['errorhasuntilandcount'] = 'یا تو UNTIL یا COUNT تکرار کے اصول میں ظاہر ہو سکتے ہیں، لیکن UNTIL اور COUNT ایک ہی تکرار کے اصول میں نہیں ہونا چاہیے۔';
$string['errorinvalidbydayprefix'] = 'BYDAY قواعد سے پہلے والی عددی اقدار صرف ماہانہ یا سالانہ تکراری اصول کے لیے موجود ہو سکتی ہیں۔';
$string['errorinvalidbydaysuffix'] = 'BYDAY اصول کے ہفتے کے دن کے لیے درست اقدار MO, TU, WE, TH, FR, SA اور SU ہیں';
$string['errorinvalidbyhour'] = 'BYHOUR اصول کے لیے درست قدریں 0 سے 23 ہیں۔';
$string['errorinvalidbyminute'] = 'BYMINUTE اصول کے لیے درست قدریں 0 سے 59 ہیں۔';
$string['errorinvalidbymonth'] = 'BYMONTH اصول کے لیے درست قدریں 1 سے 12 ہیں۔';
$string['errorinvalidbymonthday'] = 'BYMONTHDAY اصول کے لیے درست قدریں 1 سے 31 یا -31 سے -1 ہیں۔';
$string['errorinvalidbysecond'] = 'BYSECOND اصول کے لیے درست قدریں 0 سے 59 ہیں۔';
$string['errorinvalidbysetpos'] = 'BYSETPOS اصول کے لیے درست قدریں 1 سے 366 یا -366 سے -1 ہیں۔';
$string['errorinvalidbyweekno'] = 'BYWEEKNO اصول کے لیے درست قدریں 1 سے 53 یا -53 سے -1 ہیں۔';
$string['errorinvalidbyyearday'] = 'BYYEARDAY اصول کے لیے درست قدریں 1 سے 366 یا -366 سے -1 ہیں۔';
$string['errorinvaliddate'] = 'تاریخ غلط ہے';
$string['errorinvalidicalurl'] = 'دیا گیا iCal URL غلط ہے۔';
$string['errorinvalidinterval'] = 'INTERVAL اصول کی قدر ایک مثبت عددی ہونا ضروری ہے۔';
$string['errorinvalidminutes'] = '1 اور 999 کے درمیان نمبر دے کر منٹوں میں دورانیہ بتائیں۔';
$string['errorinvalidrepeats'] = '1 سے 99 تک واقعات کی تعداد متعین کریں';
$string['errormustbeusedwithotherbyrule'] = 'BYSETPOS اصول کو صرف BYxxx اصول کے دوسرے حصے کے ساتھ استعمال کیا جانا چاہیے۔';
$string['errornodescription'] = 'تفصیل ضروری ہے';
$string['errornoeventname'] = 'نام ضروری ہے';
$string['errornonyearlyfreqwithbyweekno'] = 'BYWEEKNO اصول صرف سالانہ اصولوں کے لیے درست ہے۔';
$string['errorrequiredurlorfile'] = 'کیلنڈر درآمد کرنے کے لیے یا تو URL یا فائل درکار ہے۔';
$string['errorrrule'] = 'منظور شدہ تکرار کا اصول غلط لگتا ہے۔';
$string['errorrruleday'] = 'تکرار کے اصول میں دن کا ایک غلط پیرامیٹر ہے۔';
$string['errorrrulefreq'] = 'تکرار کے اصول میں ایک غلط فریکوئنسی پیرامیٹر ہے۔';
$string['eventcalendareventcreated'] = 'کیلنڈر تقریب بنائ';
$string['eventcalendareventdeleted'] = 'کیلنڈر تقریب حذف کر دئ';
$string['eventcalendareventupdated'] = 'کیلنڈر تقریب اپ ڈیٹ ہو گئ';
$string['eventdate'] = 'تاریخ';
$string['eventdescription'] = 'تفصیل';
$string['eventduration'] = 'مدت';
$string['eventendtime'] = 'ختم ہونے کا وقت';
$string['eventendtimewrapped'] = '{$a} (اختتام کا وقت)';
$string['eventinstanttime'] = 'وقت';
$string['eventkind'] = 'تقریب کی قسم';
$string['eventname'] = 'تقریب نام';
$string['eventnone'] = 'کوئی تقاریب نہیں';
$string['eventrepeat'] = 'دوہرائیاں';
$string['events'] = 'تقاریب';
$string['eventsall'] = 'تمام تقاریب';
$string['eventsdeleted'] = 'تقاریب حذف کر دی';
$string['eventsfor'] = '{$a} تقاریب';
$string['eventsimported'] = 'تقاریب درآمد کی گئ: {$a}';
$string['eventskey'] = 'تقاریب کی کنجی';
$string['eventsource'] = 'تقریب کا ذریعہ';
$string['eventspersonal'] = 'میری ذاتی تقاریب';
$string['eventsrelatedtocategories'] = 'زمرہ جات سے متعلق واقعات';
$string['eventsrelatedtocourses'] = 'کورسز سے متعلقہ واقعات';
$string['eventsrelatedtogroups'] = 'گروہوں سے متعلق واقعات';
$string['eventsskipped'] = 'ایونٹس کو چھوڑ دیا گیا: {$a}';
$string['eventstarttime'] = 'شروع ہونے کا وقت';
$string['eventstoexport'] = 'ایکسپورٹ کرنے کے لیے ایونٹس';
$string['eventsubscriptioncreated'] = 'کیلنڈر کی رکنیت بن گئی';
$string['eventsubscriptiondeleted'] = 'کیلنڈر کی رکنیت حذف کر دی گئی';
$string['eventsubscriptioneditwarning'] = 'یہ کیلنڈر ایونٹ سبسکرپشن کا حصہ ہے۔ اگر سبسکرپشن حذف ہو جاتی ہے تو آپ اس ایونٹ میں جو بھی تبدیلیاں کرتے ہیں وہ ضائع ہو جائے گی۔';
$string['eventsubscriptionupdated'] = 'کیلنڈر کی رکنیت کو اپ ڈیٹ کر دیا گیا۔';
$string['eventsupdated'] = 'واقعات کو اپ ڈیٹ کیا گیا: {$a}';
$string['eventtime'] = 'وقت';
$string['eventtype'] = 'واقعہ قسم';
$string['eventtypecategory'] = 'زمرہ';
$string['eventtypecourse'] = 'کورس';
$string['eventtypegroup'] = 'گروپ';
$string['eventtypemodule'] = 'ماڈیول';
$string['eventtypeother'] = 'دوسرے';
$string['eventtypesite'] = 'سائٹ';
$string['eventtypeuser'] = 'صارف';
$string['eventview'] = 'تقریب کی تفصیلات';
$string['expired'] = 'ختم شدہ';
$string['explain_site_timeformat'] = 'آپ پوری سائٹ کے لیے 12 یا 24 گھنٹے کے فارمیٹ میں اوقات دیکھنے کا انتخاب کر سکتے ہیں۔ اگر آپ "ڈیفالٹ" کا انتخاب کرتے ہیں، تو فارمیٹ خود بخود اس زبان کے مطابق منتخب ہو جائے گا جو آپ سائٹ میں استعمال کرتے ہیں۔ اس ترتیب کو صارف کی ترجیحات سے اوور رائڈ کیا جا سکتا ہے۔';
$string['export'] = 'برآمد کرو';
$string['exportbutton'] = 'برآمد کرو';
$string['exportcalendar'] = 'کیلنڈر برآمد کرو';
$string['exporthelp'] = 'میں کیلنڈر ایپلیکیشن (Google/Outlook/Other) سے اس کیلنڈر کو کیسے سبسکرائب کروں؟';
$string['forcecalendartype'] = 'زبردستی کیلنڈر';
$string['fri'] = 'جمعہ';
$string['friday'] = 'جمعہ';
$string['generateurlbutton'] = 'کیلنڈر کا یو آر ایل حاصل کرو';
$string['gotoactivity'] = 'سرگرمی پر جائیں';
$string['gotocalendar'] = 'کیلنڈر کی طرف جاؤ';
$string['group'] = 'گروپ';
$string['groupevent'] = 'گروپ کی تقریب';
$string['groupevents'] = 'گروپ کی تقاریب';
$string['hideeventtype'] = '{$a} تقاریب چھپائیں';
$string['hourly'] = 'فی گھنٹہ';
$string['importcalendar'] = 'کیلنڈر درآمد کریں';
$string['importcalendarfrom'] = 'سے درآمد کریں';
$string['importcalendarheading'] = 'کیلنڈر درآمد کریں۔۔۔';
$string['importfromfile'] = 'کیلنڈر فائل (.ics)';
$string['importfromurl'] = 'کیلنڈر URL';
$string['invalideventtype'] = 'آپ نے جو تقریب کی قسم منتخب کی ہے وہ غلط ہے۔';
$string['invalidtimedurationminutes'] = 'آپ کے درج کردہ منٹوں میں دورانیہ غلط ہے۔ براہ کرم 0 سے زیادہ منٹ میں دورانیہ درج کریں یا کوئی مدت نہیں منتخب کریں۔';
$string['invalidtimedurationuntil'] = 'تاریخ اور وقت جو آپ نے مدت کے لیے منتخب کیا ہے وہ تقریب کے آغاز کے وقت سے پہلے کا ہے۔ براہ کرم آگے بڑھنے سے پہلے اسے درست کریں۔';
$string['iwanttoexport'] = 'برآمد کرو';
$string['less'] = 'کم';
$string['managesubscriptions'] = 'سبسکرپشنز کا نظم کریں';
$string['manyevents'] = '{$a} تقاریب';
$string['mon'] = 'سوموار';
$string['monday'] = 'سوموار';
$string['monthly'] = 'ماهوار';
$string['monthnext'] = 'اگلے ماہ';
$string['monthprev'] = 'پچھلے مہینے';
$string['monththis'] = 'حالیہ ماہ';
$string['more'] = 'مزید';
$string['never'] = 'کبھی نہیں';
$string['newevent'] = 'نئی تقریب';
$string['nocalendarsubscriptions'] = 'آپ کے پاس کوئی کیلنڈر سبسکرپشنز نہیں ہیں۔';
$string['notitle'] = 'بلا عنوان';
$string['noupcomingevents'] = 'یہاں کوئی آنے والی تقاریب نہیں ہیں';
$string['oneevent'] = 'پہلی تقریب';
$string['pollinterval'] = 'اپ ڈیٹ وقفہ';
$string['pollinterval_help'] = 'آپ کتنی بار کیلنڈر کو نئی تقاریب کے ساتھ اپ ڈیٹ کرنا چاہیں گے۔';
$string['pref_lookahead'] = 'لک آہیڈ آنے والی تقاریب';
$string['pref_lookahead_help'] = 'یہ مستقبل میں (زیادہ سے زیادہ) دنوں کی تعداد کو متعین کرتا ہے جن میں ایک تقریب کو آنے والی تقریب کے طور پر ظاہر کرنے کے لیے شروع ہونا ہے۔ اس سے آگے شروع ہونے والی تقاریب کو آئندہ کے طور پر کبھی نہیں دکھایا جائے گا۔ براہ کرم نوٹ کریں کہ <strong>کوئی گارنٹی نہیں ہے</strong> کہ اس ٹائم فریم میں شروع ہونے والی تمام تقاریب دکھائی جائیں گی۔ اگر بہت زیادہ ہیں ("زیادہ سے زیادہ آنے والی تقاریب" کی ترجیح سے زیادہ) تو دور دراز کی تقاریب نہیں دکھائی جائیں گی۔';
$string['pref_maxevents'] = 'زیادہ سے زیادہ آنے والی تقاریب';
$string['pref_maxevents_help'] = 'یہ آنے والی تقاریب کی زیادہ سے زیادہ تعداد کا تعین کرتا ہے جو ظاہر کیے جا سکتے ہیں۔ اگر آپ یہاں ایک بڑی تعداد کا انتخاب کرتے ہیں تو یہ ممکن ہے کہ آنے والی تقاریب کے ڈسپلے آپ کی اسکرین پر کافی جگہ لیں گی۔';
$string['pref_persistflt'] = 'فلٹر کی ترتیبات کو یاد رکھیں';
$string['pref_persistflt_help'] = 'اگر یہ فعال ہے، تو Moodle آپ کی آخری تقریب فلٹر کی ترتیبات کو یاد رکھے گا اور ہر بار لاگ ان ہونے پر انہیں خود بخود بحال کر دے گا۔';
$string['pref_startwday'] = 'ہفتے کا پہلہ دن';
$string['pref_startwday_help'] = 'کیلنڈر کے ہفتے اس دن سے شروع ہوتے ہوئے دکھائے جائیں گے جسے آپ یہاں منتخب کرتے ہیں۔';
$string['pref_timeformat'] = 'وقت کا طرز ظاہریت';
$string['pref_timeformat_help'] = 'آپ 12 یا 24 گھنٹے کی شکل میں اوقات دیکھنے کا انتخاب کر سکتے ہیں۔ اگر آپ "ڈیفالٹ" کا انتخاب کرتے ہیں، تو فارمیٹ خود بخود اس زبان کے مطابق منتخب ہو جائے گا جو آپ سائٹ میں استعمال کرتے ہیں۔';
$string['preferences'] = 'ترجیحات';
$string['preferences_available'] = 'آپ کی ذاتی ترجیحات';
$string['preferredcalendar'] = 'ترجیحی کیلنڈر';
$string['privacy:metadata:calendar:event'] = 'کیلنڈر کا جزو صارف کیلنڈر تقریب کی تفصیلات کو بنیادی سب سسٹم میں محفوظ کر سکتا ہے۔';
$string['privacy:metadata:calendar:event:description'] = 'کیلنڈر تقریب کی تفصیل۔';
$string['privacy:metadata:calendar:event:eventtype'] = 'کیلنڈر ایونٹ کی تقریب کی قسم۔';
$string['privacy:metadata:calendar:event:name'] = 'کیلنڈر تقریب کا نام۔';
$string['privacy:metadata:calendar:event:timeduration'] = 'کیلنڈرتقریب کا دورانیہ۔';
$string['privacy:metadata:calendar:event:timestart'] = 'کیلنڈر تقریب کے آغاز کا وقت۔';
$string['privacy:metadata:calendar:event_subscriptions'] = 'کیلنڈر کا جزو بنیادی سب سسٹم کے اندر صارف کیلنڈر سبسکرپشن کی تفصیلات کو اسٹور کر سکتا ہے۔';
$string['privacy:metadata:calendar:event_subscriptions:eventtype'] = 'کیلنڈر سبسکرپشن کی تقریب کی قسم۔';
$string['privacy:metadata:calendar:event_subscriptions:name'] = 'کیلنڈر کی رکنیت کا نام۔';
$string['privacy:metadata:calendar:event_subscriptions:url'] = 'کیلنڈر سبسکرپشن کا یو آر ایل۔';
$string['privacy:metadata:calendar:preferences:calendar_savedflt'] = 'ترتیب شدہ کیلنڈر تقریب کی قسم صارف کی ترجیحات کو ظاہر کرتی ہے۔';
$string['recentupcoming'] = 'حالیہ اور اگلے 60 دن';
$string['repeatedevents'] = 'بار بار ہونے والی تقاریب';
$string['repeateditall'] = 'دوہرائی گئی سیریز میں تمام تقاریب پر یہ تبدیلیاں اثر انداز کریں';
$string['repeateditthis'] = 'صرف اس تقریب میں ردو بدل کرو';
$string['repeatevent'] = 'اس تقریب کو دہرائیں';
$string['repeatnone'] = 'کوئی دوہرائی نہیں';
$string['repeatweeksl'] = 'ہفتہ وار دوہرائی، سب ملا کر تخلیق ہو رہا ہے';
$string['repeatweeksr'] = 'تقاریب';
$string['sat'] = 'ہفتہ';
$string['saturday'] = 'ہفتہ';
$string['showeventtype'] = '{$a} تقاریب دکھائیں';
$string['shown'] = 'ظاہر ہے';
$string['site'] = 'سائٹ';
$string['siteevent'] = 'سائٹ تقریب';
$string['siteevents'] = 'سائٹ کی تقاریب';
$string['spanningevents'] = 'تقریبات جاری ہیں';
$string['subscriptionname'] = 'کیلنڈر کا نام';
$string['subscriptionremoved'] = 'کیلنڈر کی رکنیت {$a} ہٹا دی گئی';
$string['subscriptions'] = 'سبسکرپشنز';
$string['subscriptionsource'] = 'تقریب کا ذریعہ: {$a}';
$string['subscriptionupdated'] = 'کیلنڈر سبسکرپشن {$a} کو اپ ڈیٹ کر دیا گیا';
$string['sun'] = 'اتوار';
$string['sunday'] = 'اتوار';
$string['thu'] = 'جمعرات';
$string['thursday'] = 'جمعرات';
$string['timeformat_12'] = 'گھنٹہ (am/pm) - 12';
$string['timeformat_24'] = 'گھنٹہ - 24';
$string['timeperiod'] = 'وقت کی مدت';
$string['today'] = 'آج';
$string['todayplustitle'] = 'آج {$a}';
$string['tomorrow'] = 'آنے والا کل';
$string['tt_deleteevent'] = 'تقریب کو حذف کریں';
$string['tt_editevent'] = 'تقریب میں ردو بدل کریں';
$string['tue'] = 'منگل';
$string['tuesday'] = 'منگل';
$string['typecategory'] = 'زمرہ کی تقریب';
$string['typeclose'] = 'تقریب بند کریں';
$string['typecourse'] = 'کورس کی تقاریب';
$string['typedue'] = 'مقررہ تقریب';
$string['typegradingdue'] = 'درجہ بندی کی مقررہ تقریب';
$string['typegroup'] = 'گروپ تقریب';
$string['typeopen'] = 'اوپن تقریب';
$string['typesite'] = 'سائٹ کی تقاریب';
$string['typeuser'] = 'صارف کی تقریب';
$string['upcomingevents'] = 'آنے والی تقاریب';
$string['upcomingeventsfor'] = 'آنے والی تقاریب برائے:';
$string['urlforical'] = 'آئی کیلنڈر کی برآمد کا یو آر ایل، تقویم پر رجسٹر ہونے کیلیے';
$string['user'] = 'صارف';
$string['userevent'] = 'صارف کی تقریب';
$string['userevents'] = 'صارف کی تقاریب';
$string['viewupcomingactivitiesdue'] = 'آئندہ ہونے والی سرگرمیاں دیکھیں';
$string['wed'] = 'بدھ';
$string['wednesday'] = 'بدھ';
$string['weekly'] = 'ہفتہ وار';
$string['weeknext'] = 'اگلے ہفتے';
$string['weekthis'] = 'اس ہفتے';
$string['when'] = 'جب';
$string['whendate'] = 'جب: {$a}';
$string['yesterday'] = 'گزشتہ روز';
$string['youcandeleteallrepeats'] = 'یہ تقریب دوہرائی جانے والی تقاریب کی سیریز کا حصہ ہے۔ آپ یہ تقریب یا تمام {$a} تقاریب ایک ہی لمحے میں خارج کر سکتے ہیں';
