<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'message', language 'ro', version '4.4'.
 *
 * @package     message
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['acceptandaddcontact'] = 'Acceptă și adaugă la contacte';
$string['addcontact'] = 'Adaugă prieten';
$string['addcontactconfirm'] = 'Ești sigur că vrei să adaugi pe {$a} la contactele dumneavoastră?';
$string['addtofavourites'] = 'Evidențiază conversația';
$string['addtoyourcontacts'] = 'Adaugă la contacte';
$string['addtoyourcontactsandmessage'] = 'Adaugă la contacte și mesaje';
$string['ago'] = 'în urmă cu {$a}';
$string['allusers'] = 'Toate mesajele de la toţi utilizatorii';
$string['backto'] = 'Înapoi la {$a}';
$string['backupmessageshelp'] = 'Dacă activaţi acest parametru, mesajele instant vor fi incluse în backup-ul automat al SITE-ULUI';
$string['blockcontact'] = 'Blochează această persoană';
$string['blockedusers'] = 'Utilizatori blocați';
$string['blocknoncontacts'] = 'Împiedică non-contactele să-mi trimită mesaje';
$string['blockuser'] = 'Blochează utilizatorul';
$string['blockuserconfirm'] = 'Ești sigur că vrei să blochezi pe {$a}?';
$string['blockuserconfirmbutton'] = 'Bloc';
$string['cancelselection'] = 'Anulați selecția mesajelor';
$string['cantblockuser'] = 'Nu îl/o poți bloca pe {$a} pentru că are permisiunea de a trimite mesaje tuturor utilizatorilor.';
$string['contactableprivacy'] = 'Acceptă mesaje de la:';
$string['contactableprivacy_coursemember'] = 'Contactele mele și ceilalți participanți la curs';
$string['contactableprivacy_onlycontacts'] = 'Doar contactele mele';
$string['contactableprivacy_site'] = 'Orice utilizator de pe site';
$string['contactblocked'] = 'Contactul a fost blocat';
$string['contactrequests'] = 'Cereri de contact';
$string['contactrequestsent'] = 'Solicitarea de contact a fost trimisă';
$string['contacts'] = 'Prieteni';
$string['conversationactions'] = 'Meniul de acțiuni de conversație';
$string['decline'] = 'Respinge';
$string['defaultmessageoutputs'] = 'Setări de notificare';
$string['deleteallconfirm'] = 'Sigur vrei să ștergi întreaga conversație? Nu va fi ștearsă și  pentru alți participanți la conversație.';
$string['deleteallmessages'] = 'Șterge toate mesajele';
$string['deleteallselfconfirm'] = 'Ești sigur că vrei să ștergi toată această conversație personală?';
$string['deleteconversation'] = 'Șterge conversația';
$string['deleteforeveryone'] = 'Șterge pentru mine și pentru ceilalți participanți';
$string['deleteforeveryoneselectedmessagesconfirm'] = 'Sunteți sigur că doriți să ștergeți mesajele selectate?';
$string['deleteselectedmessages'] = 'Șterge mesajele selectate';
$string['deleteselectedmessagesconfirm'] = 'Sigur doriți să ștergeți mesajele selectate? Nu vor fi șterse pentru alți participanți la conversație.';
$string['deleteselectedmessagesconfirmselfconversation'] = 'Sunteți sigur că doriți să selectați mesajele personale selectate?';
$string['disableall'] = 'Dezactivează notificările';
$string['disabled'] = 'Schimbul de mesaje este dezactivat pe acest site';
$string['disallowed'] = 'Blocat';
$string['editmessages'] = 'Editează mesajele';
$string['emailtagline'] = 'Aceasta este o copie a unui mesaj care ți-a fost trimis pe site-ul "{$a->sitename}". Mergi la {$a->url} pentru a răspunde.';
$string['enabled'] = 'Activat';
$string['errorcallingprocessor'] = 'Eroarea la apelarea ieșirii definite';
$string['errorconversationdoesnotexist'] = 'Conversația nu există';
$string['errormessagetoolong'] = 'Mesajul este mai lung decât maximul permis.';
$string['errortranslatingdefault'] = 'Eroare în traducerea setărilor implicite furnizate de plugin, se folosesc în schimb setările implicite ale sistemului.';
$string['eventgroupmessagesent'] = 'S-a trimis mesajul grupului';
$string['eventmessagecontactadded'] = 'Mesaj de contact adăugat';
$string['eventmessagecontactremoved'] = 'Mesaj de contact șters';
$string['eventmessagedeleted'] = 'Mesaj șters';
$string['eventmessagesent'] = 'Mesaj trimis';
$string['eventmessageuserblocked'] = 'Utilizator blocat';
$string['eventmessageuserunblocked'] = 'Utilizator deblocat';
$string['eventmessageviewed'] = 'Mesaj vizualizat';
$string['eventnotificationsent'] = 'Notificare trimisă';
$string['eventnotificationviewed'] = 'Notificare vizualizată';
$string['forced'] = 'Blocat';
$string['forcedmessage'] = 'Blocat';
$string['groupconversations'] = 'Grup';
$string['groupinfo'] = 'Informații despre grup';
$string['guestnoeditmessage'] = 'Utilizatorul vizitator nu poate edita opțiunile mesajelor';
$string['guestnoeditmessageother'] = 'Utilizatorul vizitator nu poate edita opțiunile mesajelor altor utilzatori';
$string['hidemessagewindow'] = 'Ascunde fereastra mesajului';
$string['hidenotificationwindow'] = 'Ascundeți fereastra de notificare';
$string['individualconversations'] = 'Confidențial';
$string['info'] = 'Informații despre utilizator';
$string['isnotinyourcontacts'] = '{$a} nu este în contactele dumneavoastră';
$string['loadmore'] = 'Încarcă mai mult';
$string['loggedin'] = 'Online';
$string['loggedoff'] = 'Offline';
$string['managemessageoutputs'] = 'Preferințe de notificare implicite';
$string['message'] = 'Mesaj';
$string['messagecontactrequest'] = '{$a->user} solicită să fie adăugat ca persoană de contact. Accesați pagina <a href="{$a->url}"> solicitări de contact </a> pentru a răspunde la cerere';
$string['messagecontactrequestsubject'] = '{$a->sitename}: solicitare de contact de la {$a->user}';
$string['messagecontentaudio'] = 'Audio';
$string['messagecontentimage'] = 'Imagine';
$string['messagecontentmultimediageneral'] = 'Alte fișiere mass-media';
$string['messagecontentvideo'] = 'Video';
$string['messagedrawerviewcontact'] = 'Detalii utilizator pentru {$a}';
$string['messagedrawerviewcontacts'] = 'Trimiteți mesaje de contact';
$string['messagedrawerviewconversation'] = 'Conversație cu {$a}';
$string['messagedrawerviewgroupinfo'] = 'Detalii despre grup pentru {$a}';
$string['messagedrawerviewoverview'] = 'Privire de ansamblu asupra mesageriei';
$string['messagedrawerviewsearch'] = 'Rezultatele căutării mesajelor pentru {$a}';
$string['messagedrawerviewsettings'] = 'Setările mesajului';
$string['messageoutputs'] = 'Pluginuri de notificare';
$string['messagepreferences'] = 'Preferințe pentru mesaje';
$string['messages'] = 'Mesaje';
$string['messagesselected:'] = 'Mesaje selectate:';
$string['messagetextrequired'] = 'Vă rugăm să inserați textul mesajului';
$string['messagingdatahasnotbeenmigrated'] = 'Mesajele dumneavoastră sunt indisponibile temporar din cauza actualizărilor în infrastructura de mesagerie. Vă rugăm să așteptați migrarea acestora.';
$string['muteconversation'] = 'Blocat';
$string['mutedconversation'] = 'Conversație blocată';
$string['newmessage'] = 'Mesaj nou';
$string['newmessagesearch'] = 'Selectați sau căutați un contact pentru a trimite un nou mesaj.';
$string['newonlymsg'] = 'Afişează doar noi';
$string['nocontactrequests'] = 'Fără solicitări de contact';
$string['nocontacts'] = 'Nu există contacte';
$string['nocontactsgetstarted'] = 'Fără contacte';
$string['nofavourites'] = 'Nu există conversații evidențiate';
$string['noframesjs'] = 'Versiune fără frame-uri şi JavaScript';
$string['nogroupconversations'] = 'Fără conversații de grup';
$string['noindividualconversations'] = 'Nu există conversații private';
$string['nomessagesfound'] = 'Nu s-a găsit niciun mesaj';
$string['noncontacts'] = 'Nu este în lista de prieteni';
$string['nonotifications'] = 'Nu există notificări';
$string['noparticipants'] = 'Nu există participanți';
$string['noreply'] = 'Nu răspundeți la acest mesaj';
$string['notificationdatahasnotbeenmigrated'] = 'Notificările dumneavoastră sunt indisponibile temporar din cauza actualizărilor în infrastructura de notificare. Vă rugăm să așteptați migrarea acestora.';
$string['notificationimage'] = 'Imagine de notificare';
$string['notificationpreferences'] = 'Preferințe de notificare';
$string['notifications'] = 'Notificări';
$string['notificationwindow'] = 'Fereastra de notificare';
$string['notincontacts'] = 'Trebuie să adăugați {$a} la persoanele de contact pentru a le putea trimite mesaje.';
$string['notincontactsheading'] = '{$a} nu este în lista dumneavoastră de prieteni';
$string['numparticipants'] = '{$a} participanți';
$string['off'] = 'Off';
$string['offline'] = 'Offline';
$string['on'] = 'On';
$string['online'] = 'Online';
$string['otherparticipants'] = 'Alți participanți';
$string['outputnotavailable'] = 'Nu este disponibil';
$string['page-message-x'] = 'Orice pagini de mesaje';
$string['participants'] = 'Participanți';
$string['pendingcontactrequests'] = 'Există {$a} solicitări de contact în așteptare';
$string['permitted'] = 'Permis';
$string['privacy'] = 'Confidențialitate';
$string['privacy:export:conversationprefix'] = 'Conversație:';
$string['privacy:metadata:core_favourites'] = 'Conversațiile marcate de utilizator';
$string['privacy:metadata:message_contact_requests'] = 'Lista solicitărilor de contact';
$string['privacy:metadata:message_contact_requests:requesteduserid'] = 'ID-ul utilizatorului care a primit solicitarea de contact';
$string['privacy:metadata:message_contact_requests:timecreated'] = 'Ora la care a fost creată solicitarea de contact';
$string['privacy:metadata:message_contact_requests:userid'] = 'ID-ul utilizatorului care a trimis solicitarea de contact';
$string['privacy:metadata:message_contacts'] = 'Lista contactelor';
$string['privacy:metadata:message_contacts:contactid'] = 'ID-ul utilizatorului care este un contact';
$string['privacy:metadata:message_contacts:timecreated'] = 'Ora la care a fost creat contactul';
$string['privacy:metadata:message_contacts:userid'] = 'ID-ul utilizatorului a cărui listă de contacte o afișăm';
$string['privacy:metadata:message_conversation_actions'] = 'Lista acțiunilor de conversație ale utilizatorului';
$string['privacy:metadata:message_conversation_actions:action'] = 'Acțiunea care a fost efectuată';
$string['privacy:metadata:message_conversation_actions:conversationid'] = 'ID-ul conversației de care aparține această acțiune';
$string['privacy:metadata:message_conversation_actions:timecreated'] = 'Ora când a fost creată acțiunea';
$string['privacy:metadata:message_conversation_actions:userid'] = 'ID-ul utilizatorului care a efectuat această acțiune';
$string['privacy:metadata:message_conversation_members'] = 'Lista utilizatorilor dintr-o conversație';
$string['privacy:metadata:message_conversation_members:conversationid'] = 'ID-ul conversației';
$string['privacy:metadata:message_conversation_members:timecreated'] = 'Ora când a fost creat membrul';
$string['privacy:metadata:message_conversation_members:userid'] = 'ID-ul utilizatorului într-o conversație';
$string['privacy:metadata:message_user_actions'] = 'Lista acțiunilor utilizatorului de mesaje';
$string['privacy:metadata:message_user_actions:action'] = 'Acțiunea care a fost efectuată';
$string['privacy:metadata:message_user_actions:messageid'] = 'ID-ul mesajului căruia îi aparține această acțiune';
$string['privacy:metadata:message_user_actions:timecreated'] = 'Ora când a fost creată acțiunea';
$string['privacy:metadata:message_user_actions:userid'] = 'ID-ul utilizatorului care a efectuat această acțiune';
$string['privacy:metadata:message_users_blocked'] = 'Lista utilizatorilor blocați';
$string['privacy:metadata:message_users_blocked:blockeduserid'] = 'ID-ul utilizatorului care a fost blocat';
$string['privacy:metadata:message_users_blocked:timecreated'] = 'Ora la care a fost creată acțiunea blocată';
$string['privacy:metadata:message_users_blocked:userid'] = 'ID-ul utilizatorului care a efectuat acțiunea blocată';
$string['privacy:metadata:messages'] = 'Mesaje';
$string['privacy:metadata:messages:conversationid'] = 'ID-ul conversației';
$string['privacy:metadata:messages:customdata'] = 'Date personalizate, care conțin de obicei ID-uri interne și o adresă URL publică a imaginii expeditorului (utilizator sau grup)';
$string['privacy:metadata:messages:fullmessage'] = 'Mesajul complet';
$string['privacy:metadata:messages:fullmessageformat'] = 'Formatul mesajului complet';
$string['privacy:metadata:messages:fullmessagehtml'] = 'Formatul HTML al mesajului complet';
$string['privacy:metadata:messages:smallmessage'] = 'O versiune mică a mesajului';
$string['privacy:metadata:messages:subject'] = 'Subiectul mesajului';
$string['privacy:metadata:messages:timecreated'] = 'Ora când a fost creat mesajul';
$string['privacy:metadata:messages:useridfrom'] = 'ID-ul utilizatorului care a trimis mesajul';
$string['privacy:metadata:notifications'] = 'Notificări';
$string['privacy:metadata:notifications:component'] = 'Componenta responsabilă cu trimiterea notificării';
$string['privacy:metadata:notifications:contexturl'] = 'Adresa URL legată de această notificare';
$string['privacy:metadata:notifications:contexturlname'] = 'Numele contextului';
$string['privacy:metadata:notifications:customdata'] = 'Date personalizate, care conțin de obicei ID-uri interne și o adresă URL publică a imaginii expeditorului (dacă există)';
$string['privacy:metadata:notifications:eventtype'] = 'Tipul evenimentului';
$string['privacy:metadata:notifications:fullmessage'] = 'Notificarea completă';
$string['privacy:metadata:notifications:fullmessageformat'] = 'Formatul de notificare';
$string['privacy:metadata:notifications:fullmessagehtml'] = 'Codul HTML al notificării';
$string['privacy:metadata:notifications:smallmessage'] = 'Micul mesaj al notificării';
$string['privacy:metadata:notifications:subject'] = 'Subiectul notificării';
$string['privacy:metadata:notifications:timecreated'] = 'Când a fost creată notificarea';
$string['privacy:metadata:notifications:timeread'] = 'Când a fost citită notificarea';
$string['privacy:metadata:notifications:useridfrom'] = 'ID-ul utilizatorului care a trimis notificarea';
$string['privacy:metadata:notifications:useridto'] = 'ID-ul utilizatorului care a primit notificarea';
$string['privacy:metadata:preference:core_message_settings'] = 'Setări legate de mesagerie';
$string['privacy:request:preference:set'] = 'Valoarea setării \'{$a->name}\' a fost \'{$a->value}\'';
$string['privacy_desc'] = 'Puteți restricționa mesajele';
$string['processorsettings'] = 'Setările procesorului';
$string['providerenabled'] = 'Se trimite "{$a}" status-ul activat';
$string['providerprocesorisdisallowed'] = '"{$a->provider}" al "{$a->processor}" este deblocat';
$string['providerprocesorislocked'] = '"{$a->provider}" al "{$a->processor}" este blocat';
$string['removecontact'] = 'Şterge contact';
$string['removecontactconfirm'] = 'Sigur doriți să eliminați {$a} din lista persoanelor de contact?';
$string['removecoursefilter'] = 'Eliminați filtrul pentru cursul {$a}';
$string['removefromfavourites'] = 'Scoateți de la favorite conversația';
$string['removefromyourcontacts'] = 'Șterge din lista de contacte';
$string['requirecontacttomessage'] = 'Trebuie să solicitați {$a} să vă adauge ca persoană de contact pentru a le putea trimite mesaje.';
$string['requiresconfiguration'] = 'Este necesară configurarea';
$string['searchcombined'] = 'Caută persoane și mesaje';
$string['searchforuser'] = 'Caută un utilzator';
$string['searchforuserorcourse'] = 'Căutați un utilizator sau un curs';
$string['searchmessages'] = 'Caută mesaj';
$string['seeall'] = 'Vezi toate';
$string['selectmessagestodelete'] = 'Selectează mesajele care vor fi șterse';
$string['selectnotificationtoview'] = 'Selectați din lista de notificări din lateral pentru a vedea mai multe detalii';
$string['selfconversation'] = 'Spatiu personal';
$string['selfconversationdefaultmessage'] = 'Salvați mesajele nefinalizate, linkurile, notele etc. pentru a le accesa ulterior.';
$string['send'] = 'Trimite';
$string['sendbulkmessage'] = 'Trimite mesajul la {$a} persoane';
$string['sendbulkmessagesent'] = 'Mesaj trimis la {$a} persoane';
$string['sendbulkmessagesentsingle'] = 'Mesaj trimis la o persoană';
$string['sendbulkmessagesingle'] = 'Trimite mesajul la o persoană';
$string['sendcontactrequest'] = 'Trimiteți cererea de contact';
$string['sender'] = '{$a}:';
$string['sendingviaenabled'] = 'Se trimite "{$a->provider}" via "{$a->processor}" status-ul activat';
$string['sendingvialocked'] = 'Sending "{$a->provider}" via "{$a->processor}" status-ul blocat';
$string['sendmessage'] = 'Trimite mesaj';
$string['sendmessageto'] = 'Trimite mesaj la {$a}';
$string['sendmessagetopopup'] = 'Trimite mesaj la {$a} - în fereastră nouă';
$string['settings'] = 'Setări';
$string['showmessagewindownonew'] = 'Afișați fereastra de mesaje fără mesaje noi';
$string['showmessagewindowwithcount'] = 'Afișați fereastra de mesaje cu {$a} mesaje noi';
$string['shownotificationwindownonew'] = 'Afișați fereastra de notificări fără notificări noi';
$string['shownotificationwindowwithcount'] = 'Afișați fereastra de notificări cu {$a} notificări noi';
$string['togglemessagemenu'] = 'Acționați sertarul pentru mesaje';
$string['togglenotificationmenu'] = 'Acționați meniul de notificări';
$string['totalconversations'] = '{$a} conversații în total';
$string['touserdoesntexist'] = 'Nu puteți trimite un mesaj unui ID de utilizator ({$a}) inexistent.';
$string['unabletomessage'] = 'Nu puteți trimite mesaje acestui utilizator';
$string['unblock'] = 'Deblocați';
$string['unblockcontact'] = 'Deblochează utilizator';
$string['unblockuser'] = 'Deblocați utilizatorul';
$string['unblockuserconfirm'] = 'Sigur doriți să îl/o deblocați pe {$a}?';
$string['unknownuser'] = 'Utilizator necunoscut';
$string['unmuteconversation'] = 'Deblocați';
$string['unreadconversations'] = '{$a} conversații necitite';
$string['unreadmessages'] = '{$a} mesaje necitite';
$string['unreadnewgroupconversationmessage'] = 'Mesaj nou de la {$a->name} în {$a->conversationname}';
$string['unreadnewmessage'] = 'Mesaj nou de la {$a}';
$string['unreadnotification'] = 'Notificări necitite: {$a}';
$string['unreadnotifications'] = 'Există {$a} notificări necitite';
$string['useentertosend'] = 'Folosiți tasta Enter pentru a trimite mesaje';
$string['usercantbemessaged'] = 'Nu poți trimite mesaje acestui utilizator din cauza preferințelor lor pentru mesaje. Încercați să îl adăugați ca persoană de contact.';
$string['userwouldliketocontactyou'] = '{$a} ar dori să vă contacteze';
$string['viewfullnotification'] = 'Vizualizați notificarea completă';
$string['viewmessageswith'] = 'Vizualizează mesajele cu {$a}';
$string['viewnotificationresource'] = 'Mergi la: {$a}';
$string['viewunreadmessageswith'] = 'Vizualizați mesajele necitite cu {$a}';
$string['waitingforcontactaccept'] = 'Așteaptă să fie adăugat ca și contact';
$string['wouldliketocontactyou'] = 'Dorește să vă contacteze';
$string['writeamessage'] = 'Scrie un mesaj...';
$string['you'] = 'Tu:';
$string['youhaveblockeduser'] = 'Ați blocat acest utilizator.';
$string['yourcontactrequestpending'] = 'Solicitarea dvs. de contact este în așteptare cu {$a}';
