<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'countries', language 'sv', version '3.11'.
 *
 * @package     countries
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['AD'] = 'Andorra';
$string['AE'] = 'Förenade Arabemiraten';
$string['AF'] = 'Afghanistan';
$string['AG'] = 'Antigua och Barbuda';
$string['AI'] = 'Anguilla';
$string['AL'] = 'Albanien';
$string['AM'] = 'Armenien';
$string['AO'] = 'Angola';
$string['AQ'] = 'Antarktis';
$string['AR'] = 'Argentina';
$string['AS'] = 'Amerikanska Samoa';
$string['AT'] = 'Österrike';
$string['AU'] = 'Australien';
$string['AW'] = 'Aruba';
$string['AX'] = 'Åland';
$string['AZ'] = 'Azerbajdzjan';
$string['BA'] = 'Bosnien och Hercegovina';
$string['BB'] = 'Barbados';
$string['BD'] = 'Bangladesh';
$string['BE'] = 'Belgien';
$string['BF'] = 'Burkina Faso';
$string['BG'] = 'Bulgarien';
$string['BH'] = 'Bahrain';
$string['BI'] = 'Burundi';
$string['BJ'] = 'Benin';
$string['BL'] = 'Saint-Barthélemy';
$string['BM'] = 'Bermuda';
$string['BN'] = 'Brunei Darussalam';
$string['BO'] = 'Bolivia (Mångnationella staten)';
$string['BQ'] = 'Bonaire, Sint Eustatius och Saba';
$string['BR'] = 'Brasilien';
$string['BS'] = 'Bahamas';
$string['BT'] = 'Bhutan';
$string['BV'] = 'Bouvetön';
$string['BW'] = 'Botswana';
$string['BY'] = 'Belarus';
$string['BZ'] = 'Belize';
$string['CA'] = 'Kanada';
$string['CC'] = 'Kokos- Keelingöarna';
$string['CD'] = 'Kongo-Kinshasa';
$string['CF'] = 'Centralafrikanska Republiken';
$string['CG'] = 'Kongo-Brazzaville';
$string['CH'] = 'Schweiz';
$string['CI'] = 'Elfenbenskusten';
$string['CK'] = 'Cooköarna';
$string['CL'] = 'Chile';
$string['CM'] = 'Kamerun';
$string['CN'] = 'Kina';
$string['CO'] = 'Colombia';
$string['CR'] = 'Costa Rica';
$string['CU'] = 'Kuba';
$string['CV'] = 'Kap Verde';
$string['CW'] = 'Curaçao';
$string['CX'] = 'Julöarna';
$string['CY'] = 'Cypern';
$string['CZ'] = 'Tjeckien';
$string['DE'] = 'Tyskland';
$string['DJ'] = 'Djibouti';
$string['DK'] = 'Danmark';
$string['DM'] = 'Dominica';
$string['DO'] = 'Dominikanska republiken';
$string['DZ'] = 'Algeriet';
$string['EC'] = 'Ecuador';
$string['EE'] = 'Estland';
$string['EG'] = 'Egypten';
$string['EH'] = 'Västsahara';
$string['ER'] = 'Eritrea';
$string['ES'] = 'Spanien';
$string['ET'] = 'Etiopien';
$string['FI'] = 'Finland';
$string['FJ'] = 'Fijiöarna';
$string['FK'] = 'Falklandsöarna';
$string['FM'] = 'Mikronesiska federationen';
$string['FO'] = 'Färöarna';
$string['FR'] = 'Frankrike';
$string['GA'] = 'Gabon';
$string['GB'] = 'Storbritannien';
$string['GD'] = 'Grenada';
$string['GE'] = 'Georgien';
$string['GF'] = 'Franska Guyana';
$string['GG'] = 'Guernsey';
$string['GH'] = 'Ghana';
$string['GI'] = 'Gibraltar';
$string['GL'] = 'Grönland';
$string['GM'] = 'Gambia';
$string['GN'] = 'Guinea';
$string['GP'] = 'Guadeloupe';
$string['GQ'] = 'Ekvatorialguinea';
$string['GR'] = 'Grekland';
$string['GS'] = 'Sydgeorgien och Sydsandwichöarna';
$string['GT'] = 'Guatemala';
$string['GU'] = 'Guam';
$string['GW'] = 'Guinea-Bissau';
$string['GY'] = 'Guyana';
$string['HK'] = 'Hong Kong';
$string['HM'] = 'Heard- och McDonaldöarna';
$string['HN'] = 'Honduras';
$string['HR'] = 'Kroatien';
$string['HT'] = 'Haiti';
$string['HU'] = 'Ungern';
$string['ID'] = 'Indonesien';
$string['IE'] = 'Irland';
$string['IL'] = 'Israel';
$string['IM'] = 'Isle of Man';
$string['IN'] = 'Indien';
$string['IO'] = 'Brittiska territoriet i Indiska oceanen (BIOT)';
$string['IQ'] = 'Irak';
$string['IR'] = 'Islamiska republiken Iran';
$string['IS'] = 'Island';
$string['IT'] = 'Italien';
$string['JE'] = 'Jersey';
$string['JM'] = 'Jamaica';
$string['JO'] = 'Jordanien';
$string['JP'] = 'Japan';
$string['KE'] = 'Kenya';
$string['KG'] = 'Kirgizistan';
$string['KH'] = 'Kambodja';
$string['KI'] = 'Kiribati';
$string['KM'] = 'Komorerna';
$string['KN'] = 'Saint Kitts och Nevis';
$string['KP'] = 'Nordkorea (Demokratiska Folkrepubliken Korea)';
$string['KR'] = 'Sydkorea';
$string['KW'] = 'Kuwait';
$string['KY'] = 'Caymanöarna';
$string['KZ'] = 'Kazakstan';
$string['LA'] = 'Demokratiska folkrepubliken Laos';
$string['LB'] = 'Libanon';
$string['LC'] = 'Saint Lucia';
$string['LI'] = 'Lichtenstein';
$string['LK'] = 'Sri Lanka';
$string['LR'] = 'Liberia';
$string['LS'] = 'Lesotho';
$string['LT'] = 'Litauen';
$string['LU'] = 'Luxemburg';
$string['LV'] = 'Lettland';
$string['LY'] = 'Libyen';
$string['MA'] = 'Marocko';
$string['MC'] = 'Monaco';
$string['MD'] = 'Moldavien';
$string['ME'] = 'Montenegro';
$string['MF'] = 'Saint-Martin (Franska delen)';
$string['MG'] = 'Madagaskar';
$string['MH'] = 'Marshallöarna';
$string['MK'] = 'Nordmakedonien';
$string['ML'] = 'Mali';
$string['MM'] = 'Myanmar';
$string['MN'] = 'Mongoliet';
$string['MO'] = 'Macao';
$string['MP'] = 'Nordmarianerna';
$string['MQ'] = 'Martinique';
$string['MR'] = 'Mauritanien';
$string['MS'] = 'Montserrat';
$string['MT'] = 'Malta';
$string['MU'] = 'Mauritius';
$string['MV'] = 'Maldiverna';
$string['MW'] = 'Malawi';
$string['MX'] = 'Mexiko';
$string['MY'] = 'Malaysia';
$string['MZ'] = 'Moçambique';
$string['NA'] = 'Namibia';
$string['NC'] = 'Nya Kaledonien';
$string['NE'] = 'Niger';
$string['NF'] = 'Norfolkön';
$string['NG'] = 'Nigeria';
$string['NI'] = 'Nicaragua';
$string['NL'] = 'Nederländerna';
$string['NO'] = 'Norge';
$string['NP'] = 'Nepal';
$string['NR'] = 'Nauru';
$string['NU'] = 'Niue';
$string['NZ'] = 'Nya Zeeland';
$string['OM'] = 'Oman';
$string['PA'] = 'Panama';
$string['PE'] = 'Peru';
$string['PF'] = 'Franska Polynesien';
$string['PG'] = 'Papua Nya Guinea';
$string['PH'] = 'Filippinerna';
$string['PK'] = 'Pakistan';
$string['PL'] = 'Polen';
$string['PM'] = 'Saint-Pierre och Miquelon';
$string['PN'] = 'Pitcairn';
$string['PR'] = 'Puerto Rico';
$string['PS'] = 'Palestina';
$string['PT'] = 'Portugal';
$string['PW'] = 'Palau';
$string['PY'] = 'Paraguay';
$string['QA'] = 'Qatar';
$string['RE'] = 'Réunion';
$string['RO'] = 'Rumänien';
$string['RS'] = 'Serbien';
$string['RU'] = 'Ryssland';
$string['RW'] = 'Rwanda';
$string['SA'] = 'Saudiarabien';
$string['SB'] = 'Salomonöarna';
$string['SC'] = 'Seychellerna';
$string['SD'] = 'Sudan';
$string['SE'] = 'Sverige';
$string['SG'] = 'Singapore';
$string['SH'] = 'Sankta Helena, Ascension och Tristan da Cunha';
$string['SI'] = 'Slovenien';
$string['SJ'] = 'Svalbard och Jan Mayen';
$string['SK'] = 'Slovakien';
$string['SL'] = 'Sierra Leone';
$string['SM'] = 'San Marino';
$string['SN'] = 'Senegal';
$string['SO'] = 'Somalia';
$string['SR'] = 'Surinam';
$string['SS'] = 'Sydsudan';
$string['ST'] = 'São Tomé och Príncipe';
$string['SV'] = 'El Salvador';
$string['SX'] = 'Sint Maarten';
$string['SY'] = 'Syrien';
$string['SZ'] = 'Swaziland';
$string['TC'] = 'Turks- och Caicosöarna';
$string['TD'] = 'Tchad';
$string['TF'] = 'Franska sydterritorierna';
$string['TG'] = 'Togo';
$string['TH'] = 'Thailand';
$string['TJ'] = 'Tadzjikistan';
$string['TK'] = 'Tokelau';
$string['TL'] = 'Östtimor';
$string['TM'] = 'Turkmenistan';
$string['TN'] = 'Tunisien';
$string['TO'] = 'Tonga';
$string['TR'] = 'Turkiet';
$string['TT'] = 'Trinidad och Tobago';
$string['TV'] = 'Tuvalu';
$string['TW'] = 'Taiwan';
$string['TZ'] = 'Tanzania';
$string['UA'] = 'Ukraina';
$string['UG'] = 'Uganda';
$string['UM'] = 'Förenta staternas mindre öar i Oceanien och Västindien';
$string['US'] = 'USA';
$string['UY'] = 'Uruguay';
$string['UZ'] = 'Uzbekistan';
$string['VA'] = 'Vatikanstaten';
$string['VC'] = 'Saint Vincent och Grenadinerna';
$string['VE'] = 'Venezuela (Bolivarianska republiken Venezuela)';
$string['VG'] = 'Brittiska Jungfruöarna';
$string['VI'] = 'Amerikanska Jungfruöarna';
$string['VN'] = 'Vietnam (Socialistiska republiken Vietnam)';
$string['VU'] = 'Vanuatu';
$string['WF'] = 'Wallis- och Futunaöarna';
$string['WS'] = 'Samoa';
$string['YE'] = 'Jemen';
$string['YT'] = 'Mayotte';
$string['ZA'] = 'Sydafrika';
$string['ZM'] = 'Zambia';
$string['ZW'] = 'Zimbabwe';
