<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'repository', language 'eu', version '3.11'.
 *
 * @package     repository
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['accessiblefilepicker'] = 'Fitxategi-hautatzailea eskuragarri';
$string['activaterep'] = 'Biltegi aktiboa';
$string['activerepository'] = 'Eskura dauden biltegi-pluginak';
$string['activitybackup'] = 'Jardueraren segurtasun-kopia';
$string['add'] = 'Gehitu';
$string['addfile'] = 'Gehitu...';
$string['addfiletext'] = 'Gehitu fitxategia';
$string['addplugin'] = 'Gehitu biltegi-plugin bat';
$string['aliaseschange'] = 'Fitxategi honetara zuzendutako {$a} esteka daude. Jarraituz gero fitxategiaren esteka horien ordez fitxategiaren kopiak erabiltzeko automatikoki eguneratuko dira.';
$string['allowexternallinks'] = 'Baimendu kanpoko estekak';
$string['areacategoryintro'] = 'Kategoriaren sarrera';
$string['areacourseintro'] = 'Ikastaroaren sarrera';
$string['areacourseoverviewfiles'] = 'Ikastaroaren irudia';
$string['areamainfile'] = 'Fitxategi nagusia';
$string['arearoot'] = 'Sistema';
$string['areauserbackup'] = 'Erabiltzailearen segurtasun-kopia';
$string['areauserdraft'] = 'Zirriborroak';
$string['areauserpersonal'] = 'Fitxategi pribatuak';
$string['areauserprofile'] = 'Profila';
$string['attachedfiles'] = 'Erantsitako fitxategiak';
$string['attachment'] = 'Eranskina';
$string['author'] = 'Egilea';
$string['automatedbackup'] = 'Segurtasun-kopia automatizatua';
$string['back'] = 'Atzera';
$string['backtodraftfiles'] = 'Itzuli zirriborro-fitxategien kudeatzailera';
$string['cachecleared'] = 'Cacheatutako fitxategiak ezabatuak izan dira';
$string['cacheexpire'] = 'Cache-a iraungi';
$string['cannotaccessparentwin'] = 'HTTPS erabiltzean, biltegia ez da automatikoki eguneratzen. Horren ordez, fitxategi-hautatzailera itzuli eta biltegia berriz aukeratu beharko duzu.';
$string['cannotdelete'] = 'Ezin da fitxategi hau ezabatu.';
$string['cannotdownload'] = 'Ezin da fitxategi hau jaitsi';
$string['cannotdownloaddir'] = 'Ezin da karpeta hau jaitsi';
$string['cannotinitplugin'] = 'Errorea plugin_init-era deia egitean';
$string['cannotunzipcontentunreadable'] = 'Ezin da fitxategi hau erauzi bere edukiak ezin direlako irakurri.';
$string['cannotunzipextractfileerror'] = 'Ezin da fitxategia deskonprimatu fitxategiren bat ezin delako irakurri.';
$string['cannotunzipquotaexceeded'] = 'Ezin da fitxategia erauzi eremu honetako gehieneko tamaina gaindituko litzatekeelako.';
$string['choosealink'] = 'Aukeratu esteka bat...';
$string['chooselicense'] = 'Aukeratu lizentzia';
$string['chooselicense_help'] = 'Jarraitu hurrengo estekak eskuragarri dauden lizentzien inguruko informazio gehiago eskuratzeko:';
$string['cleancache'] = 'Garbitu nire cache-ko fitxategiak';
$string['close'] = 'Itxi';
$string['commonrepositorysettings'] = 'Biltegien ezarpen komunak';
$string['configallowexternallinks'] = 'Aukera honek erabiltzaile guztiei kanpoko multimedia Moodlera kopiatu nahi duen edo ez erabakitzeko aukera ematen die. Aukera desgaituta badago multimedia fitxategiak beti Moodlera kopiatzen dira (datu-osotasuna eta segurtasun aldetik hau da normalean aukerarik onena). Aukera gaituz gero erabiltzaileak multimedia fitxategiak gehitzen dituen bakoitzean aukeratu ahal izango du.';
$string['configcacheexpire'] = 'Fitxategi-zerrendak lokalki cacheatuta mantenduko diren denbora (segundoetan) kanpo-biltegietan nabigatzean.';
$string['configgetfiletimeout'] = 'Kanpoko fitxategi bat Moodlera jaistean erabili beharreko gehieneko denbora (segundoetan).';
$string['configsaved'] = 'Ezarpenak gordeta!';
$string['configsyncfiletimeout'] = 'Kanpoko fitxategi baten tamaina sinkronizatzeko gehieneko denbora (segundoetan).';
$string['configsyncimagetimeout'] = 'Kanpoko fitxategi baten irudia kanpo-biltegitik jaisteko gehieneko denbora (segundoetan)sinkronizazioa egiten denean.';
$string['confirmdelete'] = 'Ziur zaude {$a} biltegia ezabatu nahi duzula? "Jarraitu eta jaitsi" aukeratzen baduzu kanpoko fitxategien estekak Moodlera jaitsiko dira, baina hori egiteko denbora luzea eraman dezake.';
$string['confirmdeletefile'] = 'Ziur zaude fitxategi hau ezabatu nahi duzula?';
$string['confirmdeletefilewithhref'] = 'Ziur zaude fitxategi hau ezabatu nahi duzula? Fitxategi honetara zuzendutako {$a} esteka daude. Jarraituz gero fitxategiaren esteka horien ordez fitxategiaren kopiak erabiltzeko automatikoki eguneratuko dira.';
$string['confirmdeletefolder'] = 'Ziur zaude karpeta hau ezabatu nahi duzula? Fitxategi eta azpikarpeta guztiak ere ezabatuko dira.';
$string['confirmdeleteselectedfile'] = 'Ziur zaude aukeratutako {$a} fitxategiak ezabatu nahi dituzula?';
$string['confirmremove'] = 'Ziur zaude biltegi-plugin hau ezabatu nahi duzula, aukerak eta <strong>instantzia guztiak</strong> barne - {$a}? "Jarraitu eta jaitsi" aukeratzen baduzu kanpoko fitxategien estekak Moodlera jaitsiko dira. Lan honek denbora luzea eraman dezake.';
$string['confirmrenamefile'] = 'Ziur zaude fitxategi hau berrizendatu/mugitu nahi duzula?';
$string['confirmrenamefolder'] = 'Ziur zaude karpeta hau mugitu/berrizendatu nahi duzula? Karpeta horretan dagoen edozein fitxategira zuzendutako esteken ordez fitxategiaren kopiak erabiltzeko automatikoki eguneratuko dira.';
$string['continueuninstall'] = 'Jarraitu';
$string['continueuninstallanddownload'] = 'Jarraitu eta jaitsi';
$string['copying'] = 'Kopiatzen';
$string['coursebackup'] = 'Ikastaroaren segurtasun-kopiak';
$string['create'] = 'Sortu';
$string['createfolder'] = 'Sortu karpeta';
$string['createfolderfail'] = 'Karpeta hau sortzeak huts egin du';
$string['createfoldersuccess'] = 'Karpeta ondo sortu da';
$string['createinstance'] = 'Sortu biltegi-instantzia';
$string['createrepository'] = 'Sortu biltegi-instantzia';
$string['createxxinstance'] = 'Sortu "{$a}" instantzia';
$string['date'] = 'Data';
$string['datecreated'] = 'Sortu da';
$string['deleted'] = 'Biltegia ezabatuta';
$string['deleterepository'] = 'Ezabatu biltegi hau';
$string['detailview'] = 'Ikusi xehetasunak';
$string['dimensions'] = 'Neurriak';
$string['disabled'] = 'Desgaituta';
$string['displayasdetails'] = 'Erakutsi fitxategi-xehetasunak bezala';
$string['displayasicons'] = 'Erakutsi fitxategi-ikonoak bezala';
$string['displayastree'] = 'Erakutsi fitxategi-zuhaitza bezala';
$string['displaydetails'] = 'Erakutsi karpeta fitxategien xehatasun guztiekin';
$string['displayicons'] = 'Erakutsi karpeta fitxategien ikonoekin';
$string['displaytree'] = 'Erakutsi karpeta fitxategien zuhaitzekin';
$string['download'] = 'Jaitsi';
$string['downloadallfiles'] = 'Jaitsi fitxategi guztiak';
$string['downloadfolder'] = 'Jaitsi guztiak';
$string['downloadsucc'] = 'Fitxategia ondo jaitsi da';
$string['draftareanofiles'] = 'Ezin da jaitsi zeren ez baitago erantsitako fitxategirik';
$string['editrepositoryinstance'] = 'Editatu biltegi-instantzia';
$string['emptylist'] = 'Zerrenda hutsik dago';
$string['emptytype'] = 'Ezin da bltegi mota sortu: motaren zena hutsik dago';
$string['enablecourseinstances'] = 'Baimendu erabiltzaileei biltegiko elementu bat ikastaroan gehitzea';
$string['enableuserinstances'] = 'Baimendu erabiltzaileei biltegiko elementu bat erabiltzailearen testuinguruan gehitzea';
$string['enter'] = 'Sartu';
$string['entername'] = 'Mesedez, idatzi karpetaren izena';
$string['enternewname'] = 'Mesedez, idatzi fitxategi berriaren izena';
$string['error'] = 'Errore ezezagun bat gertatu da!';
$string['errordoublereference'] = 'Ezin izan da fitxategia esteka batekin gainidatzi dagoeneko fitxategi horretara zuzendutako estekak daudelako.';
$string['errornotyourfile'] = 'Soilik zuk gehitu dituzun fitxategiak aukeratu ditzakezu.';
$string['errorpostmaxsize'] = 'Igotzen saiatu zaren fitxategia handiegia da eta zerbitzariak ez du prozesatu.';
$string['erroruniquename'] = 'Biltegiaren instantziaren izena bakarra izan behar da';
$string['errorwhilecommunicatingwith'] = 'Errorea gertatu da \'{$a}\' biltegiarekin komunikatzean.';
$string['errorwhiledownload'] = 'Errorea gertatu da ondorengo fitxategia jaitsi bitartean: {$a}';
$string['existingrepository'] = 'Biltegia lehendik bazen';
$string['federatedsearch'] = 'Federatutako bilaketa';
$string['fileexists'] = 'Fitxategiaren izena dagoeneko erabilita dago. Mesedez, erabili beste izen bat';
$string['fileexistsdialog_editor'] = 'Lehendik izen hori duen fitxategi bat txertatu da editatzen ari zaren testuan.';
$string['fileexistsdialog_filemanager'] = 'Lehendik izen hori duen fitxategi bat txertatu da';
$string['fileexistsdialogheader'] = 'Fitxategia dagoeneko badago';
$string['filename'] = 'Fitxategiaren izena';
$string['filenotnull'] = 'Fitxategi bat aukeratu behar duzu igotzeko.';
$string['filepicker'] = 'Fitxategi-hautatzailea';
$string['filesaved'] = 'Fitxategia gorde egin da';
$string['filesizenull'] = 'Ezin da fitxategiaren tamaina zehaztu';
$string['folderexists'] = 'Karpetaren izena dagoeneko erabilita dago. Mesedez, erabili beste izen bat';
$string['foldernotfound'] = 'Ez da karpeta aurkitu';
$string['folderrecurse'] = 'Karpeta bat ezin da bere azpikarpeta batera mugitu.';
$string['getfile'] = 'Aukeratu fitxategi hau';
$string['getfiletimeout'] = 'Fitxategiak eskuratzeko gehieneko denbora';
$string['help'] = 'Laguntza';
$string['iconview'] = 'Ikusi ikono gisa';
$string['imagesize'] = '{$a->width} x {$a->height} px';
$string['instance'] = 'instantzia';
$string['instancedeleted'] = 'Instantzia ezabatuta';
$string['instances'] = 'Biltegi-instantziak';
$string['instancesforcourses'] = 'Ikastaroetarako {$a} instantzia komun';
$string['instancesforsite'] = 'Gune osorako {$a} instantzia komun';
$string['instancesforusers'] = 'Erabiltzaileen {$a} instantzia pribatu';
$string['invalidfiletype'] = '{$a} fitxategi mota ezin da onartu.';
$string['invalidjson'] = 'JSON katea ez da baliagarria';
$string['invalidparams'] = 'Parametro baliogabeak';
$string['invalidplugin'] = '{$a} biltegi-plugin baliogabea';
$string['invalidrepositoryid'] = 'Biltegiaren IDa ez da baliagarria';
$string['isactive'] = 'Aktiboa?';
$string['keyword'] = 'Gakoa';
$string['lastmodified'] = 'Azken aldaketa';
$string['license'] = 'Lizentzia';
$string['linkexternal'] = 'Kanpoko esteka';
$string['listview'] = 'Ikusi zerrenda gisa';
$string['loading'] = 'Kargatzen...';
$string['login'] = 'Sartu zure kontuan';
$string['logintoaccount'] = 'Sartu zure kontuan ({$a} )';
$string['logout'] = 'Amaitu saioa';
$string['lostsource'] = 'Errorea. Iturria falta da. {$a}';
$string['makefilecontrolledlink'] = 'Sortu kontrolatutako sarbide-esteka fitxategira';
$string['makefileinternal'] = 'Egin fitxategiaren kopia';
$string['makefilelink'] = 'Estekatu kanpoko fitxategia';
$string['makefilereference'] = 'Estekatu fitxategia';
$string['manage'] = 'Kudeatu biltegiak';
$string['manageinstances'] = 'Kudeatu instantziak';
$string['manageurl'] = 'Kudeatu';
$string['manageuserrepository'] = 'Kudeatu norberaren biltegia';
$string['missingsourcekey'] = 'Jatorrizko gakoa falta da. Gako hau derrigorrezkoa da fitxategia eskuratzeko.';
$string['moving'] = 'Mugitzen';
$string['name'] = 'Izena';
$string['newfolder'] = 'Karpeta berria';
$string['newfoldername'] = 'Karpeta berriaren izena';
$string['noenter'] = 'Ez duzu ezer sartu';
$string['nofilesattached'] = 'Ez dago erantsitako fitxategirik';
$string['nofilesavailable'] = 'Ez dago fitxategirik eskuragarri';
$string['nofilesselected'] = 'Ez duzu fitxategirik aukeratu';
$string['nolicenses'] = 'Ez dago lizentziarik eskuragarri';
$string['nomorefiles'] = 'Ez dago baimenduta eraskin gehiago';
$string['nopathselected'] = 'Ez duzu fitxategia nora mugitu aukeratu (egin klik bikoitza nahi duzun direktorioa aukeratzeko)';
$string['nopermissiontoaccess'] = 'Ez duzu biltegi honetara sartzeko baimenik.';
$string['norepositoriesavailable'] = 'Sentitzen dugu, oraingo biltegietatik batek ere ezin du eskatutako formatuan fitxategirik bueltatu.';
$string['norepositoriesexternalavailable'] = 'Sentitzen dugu, oraingo biltegietatik batek ere ezin du kanpoko fitxategirik bueltatu.';
$string['noresult'] = 'Ez dago bilaketaren emaitzarik';
$string['notyourinstances'] = 'Orain beste erabiltzaile baten biltegi-instantziak ikusi/editatu ditzakezu';
$string['off'] = 'Gaituta baina ezkutuan';
$string['on'] = 'Gaituta eta ikusgai';
$string['openpicker'] = 'Aukeratu fitxategi bat...';
$string['operation'] = 'Eragiketa';
$string['original'] = 'Jatorrizkoa';
$string['originalextensionchange'] = 'Fitxategiaren izena aldatzean jatorrizko fitxategi-luzapena aldatu duzu. Luzapena ".{$a->originalextension}" izatetik ".{$a->newextension}" izatera aldatzeak fitxategia ezin irekitzea eragin dezake.';
$string['originalextensionremove'] = 'Fitxategiaren izena aldatzean jatorrizko fitxategi-luzapena ezabatu duzu. ".{$a}" luzapena ezabatzeak fitxategia ezin irekitzea eragin dezake.';
$string['overwrite'] = 'Berridatzi';
$string['overwriteall'] = 'Berridatzi dena';
$string['path'] = 'Bidea';
$string['plugin'] = 'Biltegi-pluginak';
$string['pluginerror'] = 'Erroreak biltegi-pluginean';
$string['pluginname'] = 'Biltegi-pluginaren izena';
$string['pluginnamehelp'] = 'Hau hutsik utziz gero, lehenetsitako izena erabiliko da.';
$string['popup'] = 'Egin klik "Sartu" botoian saioa hasteko';
$string['popupblockeddownload'] = 'Deskargarako leihoa blokeatuta dago, mesedez baimendu popup leihoa eta saiatu berriro.';
$string['preview'] = 'Aurreikusi';
$string['privacy:metadata:repository'] = 'Biltegien osagaiak sistemako biltegi motak gordetzen ditu.';
$string['privacy:metadata:repository_instances'] = 'Biltegien pluginen osagaiak sistemako erabiltzaileen biltegien azpisistemako instantziak gordetzen ditu.';
$string['privacy:metadata:repository_instances:name'] = 'Biltegi-instantziaren izen pertsonalitzatua.';
$string['privacy:metadata:repository_instances:password'] = 'Biltegi-instantziarentzako konfiguratutako pasahitza (aukerazkoa).';
$string['privacy:metadata:repository_instances:timecreated'] = 'Biltegi-instantzia sortu zeneko unea.';
$string['privacy:metadata:repository_instances:timemodified'] = 'Biltegi-instantzia aldatu zeneko unea.';
$string['privacy:metadata:repository_instances:typeid'] = 'Biltegi-instantzia motaren IDa.';
$string['privacy:metadata:repository_instances:userid'] = 'Biltegi-instantziaren jabea den erabiltzailearen IDa.';
$string['privacy:metadata:repository_instances:username'] = 'Biltegi-instantziarentzako konfiguratutako erabiltzaile-izena (aukerazkoa).';
$string['privatefilesof'] = 'Fitxategi pribatuak {$a}';
$string['readonlyinstance'] = 'Ezin duzu editatu/ezabatu soilik-irakurtzekoa (read-only) den instantzia bat';
$string['referencesexist'] = 'Fitxategi honetara zuzendutako {$a} esteka daude';
$string['referenceslist'] = 'Estekak';
$string['refresh'] = 'Freskatu';
$string['refreshnonjsfilepicker'] = 'Mesedez itxi leiho hau eta freskatu Javascript-gabeko fitxategi-hautatzailea';
$string['removed'] = 'Biltegia kenduta';
$string['renameall'] = 'Aldatu izena guztiei';
$string['renameto'] = 'Aldatu izena honetara: "{$a}"';
$string['repositories'] = 'Biltegiak';
$string['repository'] = 'Biltegia';
$string['repositorycourse'] = 'Ikastaro-biltegiak';
$string['repositoryerror'] = 'Urrutiko biltegiak errorea itzuli du: {$a}';
$string['repositoryicon'] = 'Biltegiaren ikonoa';
$string['save'] = 'Gorde';
$string['saveas'] = 'Gorde honela';
$string['saved'] = 'Gordeta';
$string['saving'] = 'Gordetzen';
$string['search'] = 'Bilatu';
$string['searching'] = 'Bilatu hemen';
$string['searchrepo'] = 'Bilatu biltegia';
$string['sectionbackup'] = 'Atalen segurtasun-kopiak';
$string['select'] = 'Aukeratu';
$string['setmainfile'] = 'Konfiguratu fitxategi nagusia';
$string['setmainfile_help'] = 'Karpetan fitxategi bat baino gehiago badago, fitxategi nagusia izango da orrian erakutsiko dena. Bestelako fitxategiak bertan txerta daitezke, hala nola irudiak edota bideoak. Fitxategi-kudeatzailean fitxategi nagusia letra lodiz erakutsiko da.';
$string['settings'] = 'Ezarpenak';
$string['setupdefaultplugins'] = 'Lehenetsitako biltegi-pluginak konfiguratzen';
$string['siteinstances'] = 'Gune honen biltegi-instantziak';
$string['size'] = 'Tamaina';
$string['sourcekeymismatch'] = 'Jatorrizko URLa ez dator bat jatorrizko gakoarekin.';
$string['submit'] = 'Bidali';
$string['sync'] = 'Sync';
$string['syncfiletimeout'] = 'Fitxategi-sinkronizazioaren gehieneko denbora';
$string['syncimagetimeout'] = 'Irudi-sinkronizazioaren gehieneko denbora';
$string['thumbview'] = 'Ikusi ikono bezala';
$string['title'] = 'Aukeratu fitxategi bat...';
$string['type'] = 'Mota';
$string['typenotvisible'] = 'Mota ezin da ikusi';
$string['undisclosedreference'] = '(Ez da ezagutarazi)';
$string['undisclosedsource'] = '(Ez da ezagutarazi)';
$string['unknownoriginal'] = 'Ezezaguna';
$string['unknownsource'] = 'Iturburu ezezaguna';
$string['unzipped'] = 'Ondo deskonprimatu da';
$string['upload'] = 'Igo fitxategi hau';
$string['uploading'] = 'Igotzen...';
$string['uploadsucc'] = 'Fitxategia ondo igo da';
$string['uselatestfile'] = 'Erabili azken fitxategia';
$string['usenonjsfilemanager'] = 'Ireki fitxategi-kudeatzailea leiho berrian';
$string['usenonjsfilepicker'] = 'Ireki fitxategi-hautatzailea leiho berrian';
$string['usercontextrepositorydisabled'] = 'Ezin duzu biltegi hau editatu erabiltzailearen testuinguruan';
$string['wrongcontext'] = 'Ez duzu testuinguru honetarako sarbiderik';
$string['xhtmlerror'] = 'Ziur aski XHTML goiburu hertsi bat (XHTML strict header) erabiltzen ari zara. Modu honetan YUI osagai batzuek ez dute funtzionatzen; mesedez, itzal ezazu.';
$string['ziped'] = 'Karpeta ondo konprimatu da';
