<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'workshop', language 'eu', branch 'MOODLE_38_STABLE'
 *
 * @package   workshop
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['aggregategrades'] = 'Birkalkulatu kalifikazioak';
$string['aggregation'] = 'Kalifikazioen agregazioa';
$string['allocate'] = 'Esleitu bidalketak';
$string['allocatedetails'] = 'espero direnak: {$a->expected}<br />bidalitakoak: {$a->submitted}<br />esleitu beharrekoak: {$a->allocate}';
$string['allocation'] = 'Bidalketen esleipena';
$string['allocationconfigured'] = 'Esleipena konfiguratu da';
$string['allocationdone'] = 'Esleipena egin da';
$string['allocationerror'] = 'Esleipen-errorea';
$string['allowedfiletypesforoverallfeedback'] = 'Feedback-eko fitxategietan onartutako fitxategi-motak';
$string['allowedfiletypesforoverallfeedback_help'] = 'Feedback-eko fitxategietan onartutako fitxategi-motak mugatu daitezke onartutako fitxategi-luzapenen zerrenda sartuta. Eremu hau hutsik utziz gero, fitxategi-mota guztiak onartuko dira.';
$string['allowedfiletypesforsubmission'] = 'Bidalketetako fitxategietan onartutako fitxategi-motak';
$string['allowedfiletypesforsubmission_help'] = 'Bidalketetako fitxategietan onartutako fitxategi-motak mugatu daitezke onartutako fitxategi-luzapenen zerrenda sartuta. Eremu hau hutsik utziz gero, fitxategi-mota guztiak onartuko dira.';
$string['allsubmissions'] = 'Bidalketa guztiak ({$a})';
$string['alreadygraded'] = 'Dagoeneko kalifikatuta';
$string['areaconclusion'] = 'Ondorio-testua';
$string['areainstructauthors'] = 'Bidalketarako argibideak';
$string['areainstructreviewers'] = 'Ebaluaziorako argibideak';
$string['areaoverallfeedbackattachment'] = 'Feedback orokorraren eranskinak';
$string['areaoverallfeedbackcontent'] = 'Feedback orokorraren testuak';
$string['areasubmissionattachment'] = 'Bidalketaren eranskinak';
$string['areasubmissioncontent'] = 'Bidalketaren testuak';
$string['assess'] = 'Ebaluatu';
$string['assessedexample'] = 'Adibiderako bidalketa ebaluatu da';
$string['assessedsubmission'] = 'Ebaluatutakoaren bidalketa';
$string['assessingexample'] = 'Adibiderako bidalketa ebaluatzen';
$string['assessingsubmission'] = 'Ebaluatutakoaren bidalketa';
$string['assessment'] = 'Ebaluazioa';
$string['assessmentby'] = 'Egilea: <a href="{$a->url}">{$a->name}</a>';
$string['assessmentbyfullname'] = '{$a}-ren ebaluazioa';
$string['assessmentbyyourself'] = 'Zeuk egindako ebaluazioa';
$string['assessmentdeleted'] = 'Ebaluazio-esleipena kendu da';
$string['assessmentend'] = 'Ebaluazioetarako amaiera-data';
$string['assessmentendbeforestart'] = 'Ebaluazioetarako amaiera-data ezin da hasiera-data baino lehenagokoa izan';
$string['assessmentenddatetime'] = 'Ebaluazioetarako amaiera-data: {$a->daydatetime} ({$a->distanceday})';
$string['assessmentendevent'] = '{$a} ebaluazioetarako amaiera-data';
$string['assessmentform'] = 'Ebaluaziorako formularioa';
$string['assessmentofsubmission'] = '<a href="{$a->submissionurl}">{$a->submissiontitle}</a>-ren <a href="{$a->assessmenturl}">ebaluazioa</a>';
$string['assessmentreference'] = 'Erreferentziazko ebaluazioa';
$string['assessmentreferenceconflict'] = 'Ezin diozu adibidera bidalketarik ebaluatu erreferentziazko bidalketa zuk egin baduzu.';
$string['assessmentreferenceneeded'] = 'Zuk bidalketa hau ebaluatu behar duzu erreferentziazko ebaluazioa sortzeko. Egin klik "Jarraitu" botoian bidalketa ebaluatzeko.';
$string['assessments'] = 'Ebaluazioak';
$string['assessmentsettings'] = 'Ebaluazioaren ezarpenak';
$string['assessmentstart'] = 'Ebaluazioetarako hasiera-data';
$string['assessmentstartdatetime'] = 'Ebaluazioetarako hasiera-data: {$a->daydatetime} ({$a->distanceday})';
$string['assessmentstartevent'] = '{$a} hasiko da ebaluazio-fasea';
$string['assessmentweight'] = 'Ebaluazioaren pisua';
$string['assignedassessments'] = 'Ebaluatzeko esleitutako bidalketak';
$string['assignedassessmentsnone'] = 'Ez duzu bidalketarik esleituta ebaluatzeko';
$string['backtoeditform'] = 'Itzuli edizio-formulariora';
$string['byfullname'] = 'Egilea: <a href="{$a->url}">{$a->name}</a>';
$string['byfullnamewithoutlink'] = 'Egilea: {$a}';
$string['calculategradinggrades'] = 'Kalkulatu ebaluazioaren kalifikazioak';
$string['calculategradinggradesdetails'] = 'espero direnak: {$a->expected}<br />kalkulatutakoak: {$a->calculated}';
$string['calculatesubmissiongrades'] = 'Kalkulatu bidalketaren kalifikazioak';
$string['calculatesubmissiongradesdetails'] = 'espero direnak: {$a->expected}<br />kalkulatutakoak: {$a->calculated}';
$string['chooseuser'] = 'Aukeratu erabiltzailea...';
$string['clearaggregatedgrades'] = 'Garbitu kalifikazio batura guztiak';
$string['clearaggregatedgradesconfirm'] = 'Ziur zaude kalkulatutako kalifikazioak eta ebaluazioaren kalifikazioak ezabatu nahi dituzula?';
$string['clearaggregatedgrades_help'] = 'Berrezarri egingo dira bidalketetan batutako kalifikazioak eta baita ebaluazioetakoak ere. Kalifikazio hauek hasieratik berriz kalkulatu ditzakezu, kalifikazioen ebaluazio-fasean.';
$string['clearassessments'] = 'Garbitu ebaluazioak';
$string['clearassessmentsconfirm'] = 'Ziur zaude ebaluazioaren kalifikazio guztiak ezabatu nahi dituzula? Ezin izango duzu berriz informazio hau eskuratu, ebaluatzaileek esleitutako lanak berriz kalifikatu beharko dituzte.';
$string['clearassessments_help'] = 'Bidalketen eta ebaluazioen kalifikazioak berrabiaraziko dira. Ebaluazio-formularioen informazioa gorde egingo da, baina aztertzaile guztiek ebaluazio-formularioa berriro zabaldu eta gorde beharko dute emandako kalifikazioak berriro kalkulatzeko.';
$string['conclusion'] = 'Ondorioak';
$string['conclusion_help'] = 'Erabiltzaileari ondorioak agertuko zaizkio zeregina amaitutakoan.';
$string['configexamplesmode'] = 'Tailerretako adibideen ebaluaziorako lehenetsitako modua';
$string['configgrade'] = 'Lehenetsitako gehienezko kalifikazioa tailerretako bidalketetan';
$string['configgradedecimals'] = 'Modu lehenetsian kalifikazioak erakustean hamartarren puntuaren atzetik erakutsi behar den zenbaki kopurua.';
$string['configgradinggrade'] = 'Lehenetsitako gehienezko kalifikazioa tailerretako ebaluazioetan';
$string['configmaxbytes'] = 'Guneko tailer guztietarako bidalketetarako fitxategien gehienezko tamaina lehenetsia (ikastaroko eta bestelako ezarpen lokalen menpekoa)';
$string['configstrategy'] = 'Lehenetsitako kalifikazio-estrategia tailerretan';
$string['createsubmission'] = 'Gehitu bidalketa';
$string['crontask'] = 'Tailer-moduluaren atzeko planoko prozesatzea';
$string['daysago'] = 'duela {$a} egun';
$string['daysleft'] = '{$a} egun falta dira';
$string['daystoday'] = 'gaur';
$string['daystomorrow'] = 'bihar';
$string['daysyesterday'] = 'atzo';
$string['deadlinesignored'] = 'Denbora-muga ez zaizu zuri aplikatuko';
$string['deletesubmission'] = 'Ezabatu bidalketa';
$string['editassessmentform'] = 'Editatu ebaluazio-formularioa';
$string['editassessmentformstrategy'] = 'Editatu ({$a}) ebaluazio-formularioa';
$string['editingassessmentform'] = 'Ebaluazio-formularioa editatzen';
$string['editingsubmission'] = 'Bidalketa editatzen';
$string['editsubmission'] = 'Editatu bidalketa';
$string['err_multiplesubmissions'] = 'Formulario hau bete bitartean bidalketaren beste bertsio bat gorde da. Erabiltzaile bakoitzak bidalketa bakarra egin dezake.';
$string['err_removegrademappings'] = 'Ezin dira ezabatu erabili gabeko kalifikazio-loturak';
$string['evaluategradeswait'] = 'Mesedez, itxaron ebaluazioak kalifikatu eta kalifikazioak kalkulatu arte';
$string['evaluation'] = 'Ebaluazioa kalifikatzen';
$string['evaluationmethod'] = 'Ebaluazioen kalifikatze-metodoa';
$string['evaluationmethod_help'] = 'Ebaluazioen kalifikatze-metodoak zehazten du nola kalkulatzen den ebaluazioen kalifikazioa. Kalifikazioak ezarpen ezberdinekin nahi beste aldiz birkalkulatu daitezke emaitzarekin ados egon arte.';
$string['evaluationsettings'] = 'Ebaluazioak kalifikatzeko ezarpenak';
$string['eventassessableuploaded'] = 'Bidalketa bat igo da.';
$string['eventassessmentevaluated'] = 'Ebaluazioa kalifikatu da.';
$string['eventassessmentevaluationsreset'] = 'Ebaluazioen kalifikazioak berrezarri dira';
$string['eventassessmentreevaluated'] = 'Ebaluazioak berkalifikatu dira';
$string['eventphaseswitched'] = 'Fasea aldatu da';
$string['eventsubmissionassessed'] = 'Bidalketa ebaluatu da';
$string['eventsubmissionassessmentsreset'] = 'Bidalketen ebaluazioak garbitu dira';
$string['eventsubmissioncreated'] = 'Bidalketa sortu da';
$string['eventsubmissiondeleted'] = 'Bidalketa ezabatuta';
$string['eventsubmissionreassessed'] = 'Bidalketa berrebaluatu dira';
$string['eventsubmissionupdated'] = 'Bidalketa eguneratu da';
$string['eventsubmissionviewed'] = 'Bidalketa ikusi da';
$string['example'] = 'Adibiderako bidalketa';
$string['exampleadd'] = 'Gehitu adibiderako bidalketa';
$string['exampleassess'] = 'Ebaluatu adibiderako bidalketa';
$string['exampleassessments'] = 'Ebaluatu beharreko adibiderako bidalketak';
$string['exampleassesstask'] = 'Ebaluatu adibideak';
$string['exampleassesstaskdetails'] = 'espero direnak: {$a->expected}<br />ebaluatutakoak: {$a->assessed}';
$string['examplecomparing'] = 'Adibiderako bidalketen ebaluazioak alderatzen';
$string['exampledelete'] = 'Ezabatu adibidea';
$string['exampledeleteconfirm'] = 'Ziur zaude adibiderako bidalketa hau ezabatu nahi duzula? Egin klik \'Jarraitu\' botoian bidalketa hau ezabatzeko.';
$string['exampleedit'] = 'Editatu adibidea';
$string['exampleediting'] = 'Adibidea editatzen';
$string['exampleneedassessed'] = 'Aurretik adibiderako bidalketa guztiak ebaluatu behar dituzu.';
$string['exampleneedsubmission'] = 'Aurretik zure lana bidali eta adibidezko bidalketa guztiak ebaluatu behar dituzu.';
$string['examplesbeforeassessment'] = 'Adibideak eskuragarri daude norberaren bidalketa egin aurretik, eta parekoen arteko ebaluazioa egin aurretik ebaluatu behar dira';
$string['examplesbeforesubmission'] = 'Adibideak ebaluatu behar dira norberaren bidalketa egin aurretik';
$string['examplesmode'] = 'Adibideen ebaluazio-modua';
$string['examplesubmissions'] = 'Adibiderako bidalketak';
$string['examplesvoluntary'] = 'Adibiderako bidalketen ebaluazioa borondatezkoa da';
$string['exportsubmission'] = 'Esportatu orri hau';
$string['feedbackauthor'] = 'Egilearentzako feedbacka';
$string['feedbackauthorattachment'] = 'Eranskina';
$string['feedbackby'] = 'Ondokoaren feedbacka: {$a}';
$string['feedbackreviewer'] = 'Ebaluatzaileak emandako feedbacka';
$string['feedbacksettings'] = 'Feedbacka';
$string['formataggregatedgrade'] = '{$a->grade}';
$string['formataggregatedgradeover'] = '<del>{$a->grade}</del><br /><ins>{$a->over}</ins>';
$string['formatpeergrade'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span>';
$string['formatpeergradeover'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span>';
$string['formatpeergradeoverweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">(<del>{$a->gradinggrade}</del> / <ins>{$a->gradinggradeover}</ins>)</span> @ <span class="weight">{$a->weight}</span>';
$string['formatpeergradeweighted'] = '<span class="grade">{$a->grade}</span> <span class="gradinggrade">({$a->gradinggrade})</span> @ <span class="weight">{$a->weight}</span>';
$string['givengrades'] = 'Emandako kalifikazioak';
$string['gradecalculated'] = 'Bidalketarako kalkulatutako kalifikazioa';
$string['gradedecimals'] = 'Hamartar-kopurua kalifikazioetan';
$string['gradegivento'] = '&gt;';
$string['grade_grading_name'] = 'Ebaluazioa';
$string['gradeinfo'] = 'Kalifikazioa: {$a->received}/{$a->max}';
$string['gradeitemassessment'] = '{$a->workshopname} (ebaluazioa)';
$string['gradeitemsubmission'] = '{$a->workshopname} (bidalketa)';
$string['gradeover'] = 'Indargabetu kalifikazioa bidalketarako';
$string['gradereceivedfrom'] = '&lt;';
$string['gradesreport'] = 'Tailerraren kalifikazio-txostena';
$string['grade_submission_name'] = 'Bidalketa';
$string['gradetopassgrading'] = 'Gainditzeko ebaluazioaren kalifikazioa';
$string['gradetopasssubmission'] = 'Gainditzeko bidalketaren kalifikazioa';
$string['gradinggrade'] = 'Ebaluazioaren kalifikazioa';
$string['gradinggradecalculated'] = 'Kalkulatutako kalifikazioa ebaluaziorako';
$string['gradinggrade_help'] = 'Ezarpen honek bidalketa baten ebaluazioan lor daitekeen gehienezko kalifikazioa zehazten du.';
$string['gradinggradeof'] = 'Ebaluazioaren kalifikazioa ({$a}(e)tik)';
$string['gradinggradeover'] = 'Indargabetu kalifikazioa ebaluaziorako';
$string['gradingsettings'] = 'Kalifikazioen ezarpenak';
$string['groupnoallowed'] = 'Ez duzu tailer honetako talderen batean sartzeko baimenik';
$string['iamsure'] = 'Bai, ziur nago';
$string['indicator:cognitivedepth'] = 'Gaitasun kognitiboa tailerretan';
$string['indicator:cognitivedepthdef'] = 'Gaitasun kognitiboa tailerretan';
$string['indicator:cognitivedepthdef_help'] = 'Partaide honek Tailerra jarduerak eskaintzen duen gaitasun kognitiboaren ehuneko hau lortu du analisi-tarte honetan (Mailak = Ikusi gabe, Ikusi da, Bidali da, Feedbacka ikusi da, Feedbackari iruzkina egin da, Feedback ikusi ondoren berriz bidali da)';
$string['indicator:cognitivedepth_help'] = 'Adierazle hau ikasleak Tailerra motako jardueretan lortutako sakonera kognitiboan oinarrituta dago.';
$string['indicator:socialbreadth'] = 'Gaitasun soziala tailerretan';
$string['indicator:socialbreadthdef'] = 'Gaitasun soziala tailerretan';
$string['indicator:socialbreadthdef_help'] = 'Partaide honek Tailerra jarduerak eskaintzen duen gaitasun sozialaren ehuneko hau lortu du analisi-tarte honetan';
$string['indicator:socialbreadth_help'] = 'Helburu hau ikasleak Tailerra motako jardueretan lortutako zabalera sozialean oinarrituta dago.';
$string['info'] = 'Info';
$string['instructauthors'] = 'Bidalketarako argibideak';
$string['instructreviewers'] = 'Ebaluaziorako argibideak';
$string['introduction'] = 'Deskribapena';
$string['latesubmissions'] = 'Epez kanpoko bidalketak';
$string['latesubmissionsallowed'] = 'Epez kanpoko bidalketak baimenduta daude';
$string['latesubmissions_desc'] = 'Baimendu epez kanpoko bidalketak';
$string['latesubmissions_help'] = 'Gaituz gero, egileek bidalketak epez kanpo edo ebaluazio-fasean egin ditzakete. Hala ere, berandu egindako bidalketak ezin dira editatu.';
$string['legacyallocationplugincron'] = 'Zaharkitutako Tailer-Esleipenen Cron-a';
$string['maxbytes'] = 'Bidalketa eranskinaren gehienezko tamaina';
$string['modulename'] = 'Tailerra';
$string['modulename_help'] = 'Tailerra jarduerak ikasleen lanak jaso, berrikusi eta parekoen arteko ebaluazioa egiteko aukera ematen du.

Ikasleak edozein eduki digital bidal dezake (fitxategiak), hala nola testu-fitxategiak, eta Moodlen zuzenean ere idatz dezake testu editorea erabilita.

Bidalitako lanak irakasleak zehazturiko irizpide anitzeko ebaluazio-formulario bat erabilita kalifikatzen dira. Aurretik parekoen arteko ebaluazio prozesua eta ebaluazio formularioa ulertzeko praktikak egin daitezke irakasleak emandako adibiderako bidalketak erabilita, ebaluazio-erreferentzia batekin batera. Ikasleek kide baten edo gehiagoren ebaluazioa egiteko aukera du. Bidalketak eta berrikusketak anonimoak izan daitezke nahi izanez gero.

Ikasleak bi kalifikazio lortuko ditu tailerra jardueran, bat bere bidalketarena eta bestea beste kideei eginiko kalifikazioarena. Biak kalifikatzailean gordetzen dira.';
$string['modulenameplural'] = 'Tailerrak';
$string['myassessments'] = 'Nire ebaluazioak';
$string['mysubmission'] = 'Nire bidalketa';
$string['nattachments'] = 'Gehienezko eranskin-kopurua bidalketako';
$string['noexamples'] = 'Oraindik ez dago adibiderik tailer honetan';
$string['noexamplesformready'] = 'Ebaluazio-formularioa zehaztu behar duzu adibiderako bidalketak eman aurretik';
$string['nogradeyet'] = 'Ez da oraindik kalifikatu';
$string['nosubmissionfound'] = 'Ez da erabiltzaile honen bidalketarik aurkitu';
$string['nosubmissions'] = 'Oraindik ez dago bidalketarik tailer honetan';
$string['nosubmissiontype'] = 'Gutxienez bidalketa mota bat izango da eskuragarri.';
$string['notassessed'] = 'Ebaluatu gabea';
$string['nothingfound'] = 'Ez dago erakusteko ezer';
$string['nothingtoreview'] = 'Ez dago berrikusteko ezer';
$string['notoverridden'] = 'Baliogabetu gabe';
$string['noworkshops'] = 'Ez dago tailerrik ikastaro honetan';
$string['noyoursubmission'] = 'Oraindik ez duzu lanik bidali';
$string['nullgrade'] = '-';
$string['overallfeedback'] = 'Feedback orokorra';
$string['overallfeedbackfiles'] = 'Feedback orokorraren gehienezko eranskin-kopurua';
$string['overallfeedbackmaxbytes'] = 'Feedback orokorraren eranskinen gehienezko tamaina.';
$string['overallfeedbackmode'] = 'Feedback orokorraren modua';
$string['overallfeedbackmode_0'] = 'Desgaituta';
$string['overallfeedbackmode_1'] = 'Gaituta eta hautazkoa';
$string['overallfeedbackmode_2'] = 'Gaituta eta derrigorrezkoa';
$string['overallfeedbackmode_help'] = 'Gaituz gero, ebaluazio-formularioaren beheko aldean testu-koadro bat erakutsiko da. Ebaluatzaileek bertan ebaluazio orokorra idatz edo euren ebaluazioaren azalpen gehigarria eman dezakete.';
$string['page-mod-workshop-x'] = 'Tailerraren edozein orri';
$string['participant'] = 'Partaidea';
$string['participantrevierof'] = 'Partaidea ondokoen ebaluatzailea da';
$string['participantreviewedby'] = 'Ondokoek ebaluatu dute partaidea';
$string['phaseassessment'] = 'Ebaluazio-fasea';
$string['phaseclosed'] = 'Itxita';
$string['phaseevaluation'] = 'Ebaluazioak kalifikatzeko fasea';
$string['phasesetup'] = 'Ezarpenak zehazteko fasea';
$string['phasesoverlap'] = 'Bidalketa-fasea eta ebaluazio-fasea ezin dira gainjarri';
$string['phasesubmission'] = 'Bidalketa-fasea';
$string['pluginadministration'] = 'Tailerraren kudeaketa';
$string['pluginname'] = 'Tailerra';
$string['prepareexamples'] = 'Prestatu adibiderako bidalketak';
$string['previewassessmentform'] = 'Aurreikusi';
$string['privacy:metadata:aggregatedgradinggrade'] = 'Tailer-jardueran erabiltzaileak egindako ebaluazio guztien kalifikazioen batura';
$string['privacy:metadata:assessmentgrade'] = 'Ebaluazio honetan bidalketa honetarako iradokitako kalifikazioen batura';
$string['privacy:metadata:assessmentgradinggrade'] = 'Ebaluazio hau emateagatiko kalifikazioa';
$string['privacy:metadata:assessmentgradinggradeover'] = 'Ebaluazio hau emateagatiko kalifikazioarentzat eskuz baliogabetutako balioa';
$string['privacy:metadata:assessmentid'] = 'Ebaluazioaren IDa';
$string['privacy:metadata:authorid'] = 'Bidalketaren egilearen IDa';
$string['privacy:metadata:dimensiongrade'] = 'Emandako ebaluazio-dimentsioari emadako kalifikazioa';
$string['privacy:metadata:dimensionid'] = 'Ebaluazio-dimentsioaren IDa';
$string['privacy:metadata:example'] = 'Erregistro hau adibiderako bidalketa batekoa den edo ez';
$string['privacy:metadata:feedbackauthor'] = 'Egilearentzako feedbacka';
$string['privacy:metadata:feedbackauthorformat'] = 'Egilearentzako feedbackaren testu-formatua';
$string['privacy:metadata:feedbackreviewer'] = 'Ebaluazioa eman zuen erabiltzailearentzako feedbacka';
$string['privacy:metadata:feedbackreviewerformat'] = 'Ebaluazioa eman zuen erabiltzailearentzako feedbackaren testu-formatua';
$string['privacy:metadata:late'] = 'Bidalketa amaiera-data baino beranduago bidali den edo ez';
$string['privacy:metadata:peercomment'] = 'Bidalketa egin zuen erabiltzaileak emandako kalifikazioari egindako iruzkina';
$string['privacy:metadata:peercommentformat'] = 'Emandako kalifikazioari egindako iruzkinaren testu-formatua';
$string['privacy:metadata:preference:perpage'] = 'Erabiltzileak orri bakarrean ikusi nahi duen bidalketa-kopurua';
$string['privacy:metadata:published'] = 'Behin tailerra itxi ondoren bidalketa partaide guztiei argitaratu behar den edo ez';
$string['privacy:metadata:reviewerid'] = 'Ebaluazioa eman zuen erabiltzailearen IDa';
$string['privacy:metadata:strategy'] = 'Gordetako balioak interpretatuko dituen kalifikazio-estrategia pluginaren izena';
$string['privacy:metadata:submissioncontent'] = 'Bidalketaren edukia';
$string['privacy:metadata:submissioncontentformat'] = 'Bidalketaren edukiaren testu-formatua';
$string['privacy:metadata:submissiongrade'] = 'Bidalketaren kalifikazioen batura 0 eta 100 arteko zenbaki hamartar gisa idatzita';
$string['privacy:metadata:submissiongradeover'] = 'Eskuz baliogabetutako kalifikazioen baturaren balioa';
$string['privacy:metadata:submissionid'] = 'Bidalketaren IDa';
$string['privacy:metadata:submissiontitle'] = 'Bidalketaren izenburua';
$string['privacy:metadata:subsystem:corefiles'] = 'Tailerrak bidalketaren testuan txertatutako fitxategiak gordetzen ditu';
$string['privacy:metadata:subsystem:coreplagiarism'] = 'Tailerrak plagioaren prebentziorko sistemak berez onartzen ditu';
$string['privacy:metadata:timeaggregated'] = 'Kalifikazioen batura azkenengoz kalkulatu zeneko unea';
$string['privacy:metadata:timecreated'] = 'Erregistro hau datu-basean sortu zeneko unea';
$string['privacy:metadata:timemodified'] = 'Erregistro hau datu-basean azkenengoz aldatu zeneko unea';
$string['privacy:metadata:userid'] = 'Kalifikazioen batura kalkulatu zaion erabiltzailearen IDa';
$string['privacy:metadata:weight'] = 'Ebaluazioaren pisua';
$string['privacy:metadata:workshopaggregations'] = 'Ebaluazioaren kalifikazioen baturak gordetzen ditu';
$string['privacy:metadata:workshopassessments'] = 'Tailerreko bidalketen ebaluazioak nola esleitu zireneko informazioa gordetzen du';
$string['privacy:metadata:workshopgrades'] = 'Ebaluazio-formularioak kalifikazioekin eta iruzkinekin nola osatu zireneko informazioa gordetzen du';
$string['privacy:metadata:workshopid'] = 'Tailer-jardueraren IDa';
$string['privacy:metadata:workshopsubmissions'] = 'Tailerreko bidalketen inguruko informazioa gordetzen du';
$string['privacy:request:delete:content'] = 'Edukia ezabatua izan da (egilearen eskaeraren ondorioz edo iraungitu delako)';
$string['privacy:request:delete:title'] = '[Ezabatua]';
$string['publishedsubmissions'] = 'Argitaratutako bidalketak';
$string['publishsubmission'] = 'Argitaratu bidalketa';
$string['publishsubmission_help'] = 'Publikatutako bidalketak besteentzat eskuragarri egongo dira tailerra ixten denean';
$string['reassess'] = 'Berriro ebaluatu';
$string['receivedgrades'] = 'Jasotako kalifikazioak';
$string['recentassessments'] = 'Tailerraren ebaluazioak:';
$string['recentsubmissions'] = 'Tailerraren bidalketak:';
$string['resetassessments'] = 'Ezabatu ebaluazio guztiak';
$string['resetassessments_help'] = 'Esleitutako ebaluazioak ezabatzea aukera dezakezu bidalketei eragin gabe. Bidalketak ezabatzen badira inplizituki euren ebaluazioak ere ezabatuko dira, eta beraz aukera hau ez da kontuan hartuko. Kontuan izan honek adibiderako bidalketen ebaluazioak ere barne hartzen dituela.';
$string['resetphase'] = 'Aldatu ezarpenak zehazteko fasera';
$string['resetphase_help'] = 'Gaituz gero, tailer guztiak ezarpenak zehazteko fasera igaroko dira.';
$string['resetsubmissions'] = 'Ezabatu bidalketa guztiak';
$string['resetsubmissions_help'] = 'Bidalketa guztiak eta euren ebaluazioak ezabatuak izango dira. Honek ez die adibiderako bidalketei eragiten.';
$string['saveandclose'] = 'Gorde eta itxi';
$string['saveandcontinue'] = 'Gorde eta jarraitu editatzen';
$string['saveandpreview'] = 'Gorde eta aurreikusi';
$string['saveandshownext'] = 'Gorde eta erakutsi hurrengoa';
$string['search:activity'] = 'Tailerra - jardueraren informazioa';
$string['selfassessmentdisabled'] = 'Auto-ebaluazioa desgaituta';
$string['showingperpage'] = '{$a} elementu erakusten orriko';
$string['showingperpagechange'] = 'Aldatu...';
$string['someuserswosubmission'] = 'Gutxienez egileetako batek ez du lanik bidali';
$string['sortasc'] = 'Behetik gora ordenatu';
$string['sortdesc'] = 'Goitik behera ordenatu';
$string['strategy'] = 'Kalifikazio-estrategia';
$string['strategyhaschanged'] = 'Tailerraren kalifikazio-estrategia aldatu da formularioa editatzeko asmoz ireki zenetik.';
$string['strategy_help'] = 'Kalifikazioa estrategiak ebaluazio formularioa eta bidalketak kalifikatzeko metodoa zehazten ditu.

* Metatutako kalifikazioa - Iruzkinak eta kalifikazio bat ematen dira zehaztutako irizpide bakoitzean
* Iruzkinak - Iruzkinak ematen dira zehaztutako irizpide bakoitzean baina ez da kalifikaziorik ematen
* Errore-kopurua - Iruzkinak eta Bai/Ez ebaluazioa egiten da zehaztutako baieztapen bakoitzean
* Errubrika - Mailakatze-ebaluazioa egiten da zehaztutako irizpide bakoitzean';
$string['submission'] = 'Bidalketa';
$string['submissionattachment'] = 'Eranskina';
$string['submissionby'] = '{$a} -ren bidalketa';
$string['submissioncontent'] = 'Bidalketaren edukia';
$string['submissiondeleteconfirm'] = 'Ziur zaude hurrengo bidalketa ezabatu nahi duzula?';
$string['submissiondeleteconfirmassess'] = 'Ziur zaude hurrengo bidalketa ezabatu nahi duzula? Kontuan izan honek bidalketarekin lotutako {$a->count} ebaluazio ere ezabatuko dituela, eta honek berrikuslearen kalifikazioan eragina izan dezakela.';
$string['submissionend'] = 'Bidalketetarako amaiera-data';
$string['submissionendbeforestart'] = 'Bidalketetarako amaiera-data ezin da bidalketak egiteko hasiera baino lehenagokoa izan';
$string['submissionenddatetime'] = 'Bidalketetarako amaiera-data: {$a->daydatetime} ({$a->distanceday})';
$string['submissionendevent'] = '{$a} bidalketetarako amaiera-data';
$string['submissionendswitch'] = 'Igaro hurrengo fasera bidalketetarako amaiera-data iristean';
$string['submissionendswitch_help'] = 'Bidalketak egiteko azken eguna zehaztuta badago eta aukera hau markatuta badago, tailerra hurrengo fasera automatikoki igaroko da amaiera-data iristean.

Aukera hau gaituz gero, esleipen programatua konfiguratzea gomendatzen da. Bidalketak ez badira esleitzen ezin da ebaluaziorik egin ebaluazio-fasean egon arren.';
$string['submissiongrade'] = 'Bidalketaren kalifikazioa';
$string['submissiongrade_help'] = 'Ezarpen honek bidalitako lanetan lor daitekeen gehienezko kalifikazioa zehazten du.';
$string['submissiongradeof'] = 'Bidalketaren kalifikazioa ({$a}(e)tik)';
$string['submissionlastmodified'] = 'Azken aldaketa';
$string['submissionrequiredcontent'] = 'Testuren bat idatzi edo fitxategiren bat gehitu behar duzu.';
$string['submissionrequiredfile'] = 'Fitxategiren bat gehitu edo testuren bat idatzi behar duzu.';
$string['submissionsettings'] = 'Bidalketaren ezarpenak';
$string['submissionsreport'] = 'Tailerraren bidalketa-txostena';
$string['submissionstart'] = 'Bidalketetarako hasiera-data';
$string['submissionstartdatetime'] = 'Bidalketetarako hasiera-data: {$a->daydatetime} ({$a->distanceday})';
$string['submissionstartevent'] = '{$a} hasiko da bidalketa-fasea';
$string['submissiontitle'] = 'Izenburua';
$string['submissiontypedisabled'] = 'Bidalketa mota hau desgatiu da tailer honetan.';
$string['submissiontypefileavailable'] = 'Fitxategi-eransketa <span class="accesshide">eskuragarria</span>';
$string['submissiontypefilerequired'] = '<span class="accesshide">Fitxategi-eransketa </span> Nahitaezkoa';
$string['submissiontypes'] = 'Bidalketa-motak';
$string['submissiontypetextavailable'] = 'On-line testua<span class="accesshide"> eskuragarri</span>';
$string['submissiontypetextrequired'] = '<span class="accesshide">On-line testua </span>beharrezkoa';
$string['submittednotsubmitted'] = 'Bidalita ({$a->submitted}) / bidali gabe ({$a->notsubmitted})';
$string['subplugintype_workshopallocation'] = 'Bidalketak esleitzeko metodoa';
$string['subplugintype_workshopallocation_plural'] = 'Bidalketak esleitzeko metodoak';
$string['subplugintype_workshopeval'] = 'Ebaluazioen kalifikatze-metodoa';
$string['subplugintype_workshopeval_plural'] = 'Ebaluazioen kalifikatze-metodoa';
$string['subplugintype_workshopform'] = 'Kalifikazio-estrategia';
$string['subplugintype_workshopform_plural'] = 'Kalifikazio-estrategiak';
$string['switchingphase'] = 'Fasea aldatzen';
$string['switchphase'] = 'Aldatu fasea';
$string['switchphase10'] = 'Aldatu ezarpenak zehazteko fasera';
$string['switchphase10info'] = 'Tailerra <strong>Ezarpenak zehazteko fasera</strong> eramango duzu. Fase honetan erabiltzaileek ezin dituzte aldatu euren bidalketak edo ebaluazioak.Tailerraren ezarpenak, ebaluazio-formularioetan ezarritako kalifikazio-estrategiak eta ebaluazio-formularioak aldatzeko erabil dezakete irakasleek fase hau.';
$string['switchphase20'] = 'Aldatu bidalketa-fasera';
$string['switchphase20info'] = 'Tailerra <strong>Bidalketa-fasera</strong> eramango duzu. Fase honetan ikasleek lanak bidal ditzakete (sarbide-kontrolerako epeen barruan, ezarpen hori ezarrita badago). Irakasleek aurkezpenak eslei ditzakete berrikusketarako.';
$string['switchphase30'] = 'Aldatu ebaluazio-fasera';
$string['switchphase30auto'] = 'Tailerra ebaluazio-fasera automatikoki igaroko da {$a->daydatetime} ({$a->distanceday}) iristean';
$string['switchphase30info'] = 'Tailerra <strong>Ebaluazio-fasera</strong> eramango duzu. Fase honetan ebaluatzaileek esleitu zaizkien lanak ebalua ditzakete (sarbide-kontrolerako epeen barruan, ezarpen hori ezarrita badago).';
$string['switchphase40'] = 'Aldatu ebaluazioak kalifikatzeko fasera';
$string['switchphase40info'] = 'Tailerra <strong>Kalifikazioa ebaluatzeko fasera</strong> eramango duzu. Fase honetan ikasleek ezin dituzte beren bidalketa edo ebaluazioak aldatu. Irakasleek ebaluazio-tresnak erabil ditzakete azken kalifikazioak kalkulatzeko eta ebaluatzaileei feedbacka emateko.';
$string['switchphase50'] = 'Itxi tailerra';
$string['switchphase50info'] = 'Tailerra itxi egingo duzu. Horren ondorioz, kalkulatutako kalifikazioak kalifikazio-liburuan agertuko dira. Ikasleek beren bidalketak eta ebaluazioak ikus ditzakete.';
$string['switchphaseauto'] = 'Fase-aldaketa programatu egin da';
$string['switchphasenext'] = 'Aldatu hurrengo fasera';
$string['taskassesspeers'] = 'Ebaluatu kideak';
$string['taskassesspeersdetails'] = 'denera: {$a->total}<br />bidali gabe: {$a->todo}';
$string['taskassessself'] = 'Ebaluatu zeure burua';
$string['taskconclusion'] = 'Eman itxiera bat jarduerari';
$string['taskdone'] = 'Egindako lana';
$string['taskfail'] = 'Huts egindako lana';
$string['taskinfo'] = 'Lanaren informazioa';
$string['taskinstructauthors'] = 'Eman bidalketa egiteko argibideak';
$string['taskinstructreviewers'] = 'Eman ebaluazioa egiteko argibideak';
$string['taskintro'] = 'Zehaztu tailerraren deskribapena';
$string['tasksubmit'] = 'Bidali zure lana';
$string['tasktodo'] = 'Egin beharreko lana';
$string['toolbox'] = 'Tailerraren tresna-kutxa';
$string['undersetup'] = 'Tailerra ez da oraindik abian jarri. Itxaron, mesedez, hurrengo fasera igaro arte.';
$string['useexamples'] = 'Erabili adibideak';
$string['useexamples_desc'] = 'Ebaluazioa praktikatzeko adibideak eskainiko dira';
$string['useexamples_help'] = 'Gaituz gero, erabiltzaileek adibiderako bidalketen ebaluazio bat edo gehiagorekin proba dezakete eta beren ebaluazioa erreferentzia gisako beste batekin alderatu ahal dute. Kalifikazio hau ez da ebaluazioan kontuan hartuko.';
$string['usepeerassessment'] = 'Erabili parekoen arteko ebaluazioa';
$string['usepeerassessment_desc'] = 'Ikasleek beste batzuen lana ebalua dezakete';
$string['usepeerassessment_help'] = 'Gaituz gero, erabiltzaile bat izenda daiteke beste batzuen ebaluazioa egiteko. Kalifikazio bat jasoko du ebaluazioa egiteko, bere aurkezpenerako kalifikazioaz gain.';
$string['userdatecreated'] = 'noiz bidalia: <span>{$a}</span>';
$string['userdatemodified'] = 'noiz aldatua: <span>{$a}</span>';
$string['userplan'] = 'Tailerraren planifikazioa';
$string['userplanaccessibilityskip'] = 'Egin salto oraingo lanetara';
$string['userplanaccessibilitytitle'] = 'Tailerraren kronologia {$a} faserekin';
$string['userplancurrentphase'] = 'Oraingo fasea';
$string['userplan_help'] = 'Tailerraren planifikazioak jardueraren faseak erakusten ditu eta fase bakoitzaren lanak zerrendatzen ditu. Uneko fasea nabarmenduta dago eta lanen osaketa marka batez adierazten da.';
$string['useselfassessment'] = 'Erabili auto-ebaluazioa';
$string['useselfassessment_desc'] = 'Ikasleek beren lana ebalua dezakete';
$string['useselfassessment_help'] = 'Gaituz gero, erabiltzaile bat izenda daiteke bere aurkezpena kalifikatzeko. Kalifikazio bat jasoko du ebaluazioa egiteko, bere aurkezpenerako kalifikazioaz gain.';
$string['viewworkshopsummary'] = 'Ikusi tailerraren laburpena';
$string['weightinfo'] = 'Pisua: {$a}';
$string['withoutsubmission'] = 'Bidalketarik esleitu ez zaion ebaluatzailea';
$string['workshop:addinstance'] = 'Gehitu tailer berria';
$string['workshop:allocate'] = 'Esleitu bidalketak ebaluazioarako';
$string['workshop:deletesubmissions'] = 'Ezabatu bidalketak';
$string['workshop:editdimensions'] = 'Editatu ebaluazio-formularioa';
$string['workshop:exportsubmissions'] = 'Esportatu bidaketak';
$string['workshop:ignoredeadlines'] = 'Ez hartu kontuan denbora-mugak';
$string['workshop:manageexamples'] = 'Kudeatu adibiderako bidalketak';
$string['workshopname'] = 'Tailerraren izena';
$string['workshop:overridegrades'] = 'Gainidatzi kalkulaturiko kalifikazioak';
$string['workshop:peerassess'] = 'Ebaluatu kideak';
$string['workshop:publishsubmissions'] = 'Argitaratu bidalketak';
$string['workshop:submit'] = 'Bidali';
$string['workshop:switchphase'] = 'Aldatu fasea';
$string['workshop:view'] = 'Ikusi tailerra';
$string['workshop:viewallassessments'] = 'Ikusi ebaluazio guztiak';
$string['workshop:viewallsubmissions'] = 'Ikusi bidalketa guztiak';
$string['workshop:viewauthornames'] = 'Ikusi egileen izenak';
$string['workshop:viewauthorpublished'] = 'Ikusi argitaratutako bidaldeten egileak';
$string['workshop:viewpublishedsubmissions'] = 'Ikusi argitaratutako bidalketak';
$string['workshop:viewreviewernames'] = 'Ikusi ebaluatzaileen izenak';
$string['yourassessmentfor'] = '{$a}-(r)ako zure ebaluazioa';
$string['yourgrades'] = 'Zure kalifikazioak';
$string['yoursubmission'] = 'Zure bidalketak';
