<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'backup', language 'ar', branch 'MOODLE_38_STABLE'
 *
 * @package   backup
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['asyncbackupcomplete'] = 'اكتمال عملية النسخ الاحتياطي';
$string['asyncbackupcompletebutton'] = 'استمر';
$string['asyncbackupcompletedetail'] = 'اكتملت عملية النسخ الاحتياطي بنجاح. <br/> يمكنك الوصول إلى النسخة الاحتياطية على <a href="{$a}">صفحة الاستعادة.</a>';
$string['asyncbackuperror'] = 'فشلت عملية النسخ الاحتياطي';
$string['asyncbackuperrordetail'] = 'فشلت عملية النسخ الاحتياطي. من فضلك تواصل مع مسؤول النظام.';
$string['asyncbackuppending'] = 'عملية النسخ الاحتياطي معلقة';
$string['asyncbackupprocessing'] = 'النسخ الاحتياطي قيد التقدم';
$string['asyncbadexecution'] = 'تنفيذ تحكم النسخ الاحتياطي غير صالح. إنه {$a} ويجب أن يكون 2.';
$string['asynccheckprogress'] = 'يمكنك التحقق من التقدم في أي وقت على <a href="{$a}">صفحة الاستعادة.</a>.';
$string['asyncemailenable'] = 'تمكين إشعارات الرسائل';
$string['asyncemailenabledetail'] = 'في حالة التمكين ، سيتلقى المستخدمون رسالة عند اكتمال النسخ الاحتياطي أو الاستعادة غير المتزامنة.';
$string['asyncgeneralsettings'] = 'النسخ الاحتياطي غير متزامن / استعادة';
$string['asyncmessagebody'] = 'الرسالة';
$string['asyncmessagebodydefault'] = 'مرحبا {user_firstname},<br/>
 عمليتك {operation} (رقم : {backupid})اكتملت بنجاح . <br/>
<br/>يمكنك الوصول إليها من هنا: {link}.';
$string['asyncmessagebodydetail'] = 'رسالة للإرسال عند اكتمال النسخ الاحتياطي أو الاستعادة غير المتزامنة.';
$string['asyncmessagesubject'] = 'الموضوع';
$string['asyncmessagesubjectdefault'] = 'اكمل Moodle تنفيذ {operation} بنجاح';
$string['asyncmessagesubjectdetail'] = 'موضوع الرسالة';
$string['asyncnowait'] = 'لا تحتاج إلى الانتظار هنا ، حيث ستستمر العملية في الخلفية.';
$string['asyncprocesspending'] = 'العملية معلقة';
$string['asyncrestorecomplete'] = 'اكتملت عملية الاستعادة';
$string['asyncrestorecompletebutton'] = 'استمر';
$string['asyncrestorecompletedetail'] = 'اكتملت عملية الاستعادة بنجاح. النقر فوق "استمر" سينقلك إلى <a href="{$a}">المادة ,, العنصر المستعاد.</a>';
$string['asyncrestoreerror'] = 'فشلت عملية الاستعادة';
$string['asyncrestoreerrordetail'] = 'فشلت عملية الاستعادة. من فضلك تواصل مع مسؤول النظام.';
$string['asyncrestoreinprogress'] = 'الاستعادة في تقدم';
$string['asyncrestoreinprogress_help'] = 'يتم عرض استعادة المادة غير المتزامنة قيد التقدم هنا.';
$string['asyncrestorepending'] = 'عملية الاستعادة معلقة';
$string['asyncrestoreprocessing'] = 'الاستعادة قيد التقدم';
$string['asyncreturn'] = 'العودة إلى المادة';
$string['autoactivedescription'] = 'إختر ما إذا أردتَ استعمال الحفظ الاحتياطي التلقائي أو لا. إذا تم اختيار الحفظ الاحتياطي اليدوي، فالحفظ الاحتياطي التلقائي لن يكون ممكناً إلا من خلال النص البرمجي لواجهة سطر الأوامر. يمكن تنفيذ ذلك إما يدوياً أو من خلال مشغل الوظائف الدورية.';
$string['autoactivedisabled'] = 'معطل';
$string['autoactiveenabled'] = 'مفعل';
$string['autoactivemanual'] = 'يدوي';
$string['automatedbackupschedule'] = 'مجدول';
$string['automatedbackupschedulehelp'] = 'إختر أيام الأسبوع التي يتم فيها تشغيل الحفظ الاحتياطي التلقائي.';
$string['automatedbackupsinactive'] = 'لم يتم تمكين الحفظ الاحتياطي التلقائي من قِبَل مشرف الموقع';
$string['automatedbackupstatus'] = 'حالة الحفظ الاحتياطي التلقائي';
$string['automateddeletedays'] = 'حذف نُسخ الحفظ الاحتياطي الأقدم من';
$string['automatedmaxkept'] = 'أقصى عدد من نُسخ الحفظ الاحتياطي يتم الإبقاء عليها';
$string['automatedmaxkepthelp'] = 'هذا يحدد العدد الأقصى من نسخ الحفظ الاحتياطي التلقائي الأخيرة التي سيتم الإبقاء عليها لكل مساق. سيتم حذف النسخ الأقدم تلقائياً.';
$string['automatedminkept'] = 'أقل عدد من نُسخ الحفظ الاحتياطي يتم الإبقاء عليها';
$string['automatedminkepthelp'] = 'إذا تم حذف الحفظ الاحتياطي الأقدم من عدد الأيام المُحدَّدة، فإنه يمكن لمساق غير نشط أن يصير بلا حفظ احتياطي. لمنع ذلك، ينبغي تحديد أقل عدد من الحفظ الاحتياطي الذي يُحتفظ به.';
$string['automatedsettings'] = 'إعدادات الحفظ الاحتياطي التلقائي';
$string['automatedsetup'] = 'تهيئة الحفظ الاحتياطي التلقائي';
$string['automatedstorage'] = 'مخزن الحفظ الاحتياطي التلقائي';
$string['automatedstoragehelp'] = 'إختر الموضع الذي تريد استعماله لتخزين نسخ الحفظ الاحتياطي المنشأة تلقائياً.';
$string['backupactivity'] = 'نسخة احتياطية للنشاط: {$a}';
$string['backupcourse'] = 'الحفظ الاحتياطي للمساق: {$a}';
$string['backupcoursedetails'] = 'تفاصيل المقرر';
$string['backupcoursesection'] = 'القسم: {$a}';
$string['backupcoursesections'] = 'أقسام المقرر';
$string['backupdate'] = 'التاريخ مأخوذ';
$string['backupdetails'] = 'تفاصيل النسخة الاحتياطية';
$string['backupdetailsnonstandardinfo'] = 'الملف المُحدَّد ليس بالشكل القياسي المقبول لملف حفظ إحتياطي لمودل. ستحاول عملية الاستعادة تحويل الملف إلى الشكل القياسي للحفظ الاحتياطي ومن ثم استعادته.';
$string['backupformat'] = 'تنسيق';
$string['backupformatimscc1'] = 'لفيفة IMS عامة 1.0';
$string['backupformatimscc11'] = 'لفيفة IMS عامة 1.1';
$string['backupformatmoodle1'] = 'مودل 1';
$string['backupformatmoodle2'] = 'مودل 2';
$string['backupformatunknown'] = 'تنسيق غير معروف';
$string['backuplog'] = 'المعلومات التقنية والتحذيرات';
$string['backupmode'] = 'نسق';
$string['backupmode10'] = 'عام';
$string['backupmode20'] = 'إستيراد';
$string['backupmode30'] = 'محور';
$string['backupmode40'] = 'نفس الموقع';
$string['backupmode50'] = 'مُؤتمت';
$string['backupmode60'] = 'تم التحويل';
$string['backupmode70'] = 'غير متزامن';
$string['backupsection'] = 'الحفظ الاحتياطي لمقطع المساق: {$a}';
$string['backupsettings'] = 'إعدادات الحفظ الاحتياطي';
$string['backupsitedetails'] = 'تفاصيل الموقع';
$string['backupstage16action'] = 'استمرار';
$string['backupstage1action'] = 'التالي';
$string['backupstage2action'] = 'التالي';
$string['backupstage4action'] = 'تنفيذ الحفظ الاحتياطي';
$string['backupstage8action'] = 'استمرار';
$string['backuptype'] = 'نوع';
$string['backuptypeactivity'] = 'نشاط';
$string['backuptypecourse'] = 'مقرر دراسي';
$string['backuptypesection'] = 'قسم';
$string['backupversion'] = 'إصدار النسخة الاحتياطية';
$string['cannotfindassignablerole'] = 'دور {$a} في النسخة الاحتياطية لا يمكن تعيينه لأي من الأدوار المسموح لك بتعيينها.';
$string['choosefilefromactivitybackup'] = 'مساحة الحفظ الاحتياطي للنشاط';
$string['choosefilefromactivitybackup_help'] = 'عندما تستخدم نشاطات نسخ الاحتياط الإعدادات التلقائية, ملفات نسخ الاحتياط ستخزن هنا';
$string['choosefilefromautomatedbackup'] = 'نُسخ الحفظ الاحتياطي التلقائي';
$string['choosefilefromautomatedbackup_help'] = 'يحتوي على نُسخ الحفظ الاحتياطي المنشأة تلقائياً';
$string['choosefilefromcoursebackup'] = 'مساحة الحفظ الاحتياطي للمساق';
$string['choosefilefromcoursebackup_help'] = 'عندما تستخدم نشاطات نسخ الاحتياط الإعدادات التلقائية, ملفات نسخ الاحتياط ستخزن هنا';
$string['choosefilefromuserbackup'] = 'مساحة الحفظ الاحتياطي الخاصة بالمستخدم';
$string['choosefilefromuserbackup_help'] = 'يتم تخزين ملفات الحفظ الاحتياطي التي تم حفظها بلا معلومات المُستخدمين هنا.';
$string['configgeneralactivities'] = 'يحدد الوضع الافتراضي لتضمين الأنشطة في الحفظ الاحتياطي.';
$string['configgeneralanonymize'] = 'في حالة التمكين ستصبح المعلومات الخاصة المستخدمين مجهولة افتراضيا';
$string['configgeneralbadges'] = 'لتعيين الإعداد الافتراضي لتضمين الشارات في نسخة احتياطية.';
$string['configgeneralblocks'] = 'يضبط الوضع الافتراضي لتضمين الكتل في الحفظ الاحتياطي.';
$string['configgeneralcalendarevents'] = 'يضبط الافتراضي لتضمين أحداث التقويم في نسخة احتياطية.';
$string['configgeneralcomments'] = 'يحدد الوضع الافتراضي لتضمين التعليقات في الحفظ الاحتياطي.';
$string['configgeneralcompetencies'] = 'يضبط الوضع الافتراضي لتضمين الكفاءات في نسخة احتياطية.';
$string['configgeneralfiles'] = 'ضبط الوضع الافتراضي لتضمين الملفات في النسخة الاحتياطية.
يرجى ملاحظة الآتي: سيؤدي تعطيل هذا الإعداد إلى نُسخ إحتياطية تتضمن فقط مسارات للملفات.
هذه ليست مشكلة إذا تم استعادة النسخة الاحتياطية على نفس الموقع و لم يتم حذف الملفات وفقًا للإعداد "تنظيف سلة الملفات المحذوفة " (filescleanupperiod).';
$string['configgeneralfilters'] = 'يحدد الوضع الافتراضي لتضمين المرشحات في الحفظ الاحتياطي.';
$string['configgeneralgroups'] = 'يضبط الوضع الافتراضي لتضمين المجموعات والتجميعات في الحفظ الاحتياطي.';
$string['configgeneralhistories'] = 'يحدد الوضع الافتراضي لتضمين ماضي المستخدمين في الحفظ الاحتياطي.';
$string['configgenerallogs'] = 'في حالة التمكين، سيتم تضمن سجلات الوقوعات في الحفظ الاحتياطي إفتراضياً';
$string['configgeneralquestionbank'] = 'عند تمكينه، بنك الأسئلة سيتم تضمينه في الحفظ الاحتياطي إفتراضيأً. الرجاء ملاحظة: سيؤدي تعطيل هذا الإعداد إلى تعطيل الحفظ الاحتياطي للأنشطة التي تستعمل بنك الأسئلة، مثل الاختبار.';
$string['configgeneralroleassignments'] = 'في حالة التمكين سيتم تضمين تعيينات الأدوار في الحفظ الاحتياطي افتراضياً.';
$string['configgeneralusers'] = 'يحدد الوضع الافتراضي بشأن ما إذا كان ينبغي لتضمين المستخدمين في الحفظ الاحتياطي.';
$string['configgeneraluserscompletion'] = 'في حالة التمكين سيتم تضمين معلومات الإكمال للمستخدمين في الحفظ الاحتياطي افتراضياً.';
$string['config_keep_groups_and_groupings'] = 'افتراضيا إبقاء المجموعات والتجمعات الحالية.';
$string['config_keep_roles_and_enrolments'] = 'افتراضيا الحفاظ على الأدوار الحالية والتسجيلات.';
$string['configloglifetime'] = 'يحدد هذا المدة الزمنية التي تريد الاحتفاظ فيها بمعلومات سجلات وقوعات الحفظ الاحتياطي. يتم حذف السجلات الأقدم من هذا العمر تلقائياً. من المستحسن الحفاظ على هذه القيمة صغيرة، لأن معلومات سجلات الحفظ الاحتياطي يمكن أن تكون ضخمة.';
$string['config_overwrite_conf'] = 'يسمح للمستخدم بالكتابة عن تكوين المساق';
$string['config_overwrite_course_fullname'] = 'بشكل افتراضي، الاسم الكامل للمساق يتم استبداله مع الاسم الموجود في ملف النسخة الاحتياطية. يتطلب هذا أن يتم وضع شارة بجانب “استبدال اعدادات المساق" و أن يكون لدى المستخدم الحالي القدرة على تغيير الاسم الكامل للمساق (moodle/course:changefullname)';
$string['config_overwrite_course_shortname'] = 'بشكل افتراضي، الاسم القصير للمساق يتم استبداله مع الاسم الموجود في ملف النسخة الاحتياطية. يتطلب هذا أن يتم وضع شارة بجانب “استبدال اعدادات المساق" و أن يكون لدى المستخدم الحالي القدرة على تغيير الاسم القصير للمساق (moodle/course:changeshortname)';
$string['config_overwrite_course_startdate'] = 'بشكل افتراضي، تاريخ بداية المساق يتم استبداله بالتاريخ المأخوذ من ملف الحفظ الاحتياطي. يتطلب هذا أن يتم التأشير على "استبدال إعدادات المساق" وأن يكون لدى المستخدم الحالي الإمكانية على تغيير تاريخ بدء المساق (moodle/restore:rolldates) عند الاستعادة';
$string['configrestoreactivities'] = 'يضبط الوضع الافتراضي لاستعادة الأنشطة.';
$string['configrestorebadges'] = 'يضبط الوضع الافتراضي لاستعادة الشارات.';
$string['configrestoreblocks'] = 'يضبط الوضع الافتراضي لاستعادة الكتل.';
$string['configrestorecalendarevents'] = 'يضبط الوضع الافتراضي لاستعادة أحداث التقويم.';
$string['configrestorecomments'] = 'يضبط الوضع الافتراضي لاستعادة التعليقات.';
$string['configrestorecompetencies'] = 'يضبط الوضع الافتراضي لاستعادة الكفاءات.';
$string['configrestoreenrolments'] = 'يضبط الوضع الافتراضي لاستعادة طرق التسجيل.';
$string['configrestorefilters'] = 'يضبط الوضع الافتراضي لاستعادة المرشحات.';
$string['configrestoregroups'] = 'يضبط الوضع الافتراضي لاستعادة المجموعات والتجميعات إذا تم تضمينها في الحفظ الاحتياطي.';
$string['configrestorehistories'] = 'لتعيين الإعداد الافتراضي لاستعادة سجل المستخدم إذا تم تضمينه في النسخة الاحتياطية.';
$string['configrestorelogs'] = 'إذا تم تمكين السجلات التي تم تمكينها بشكل افتراضي إذا تم تضمينها في النسخة الاحتياطية.';
$string['configrestoreroleassignments'] = 'إذا تم تمكينه من خلال تعيين الأدوار الافتراضية سيتم استعادتها إذا كانت مدرجة في النسخة الاحتياطية.';
$string['configrestoreusers'] = 'يضبط الإعدادات الافتراضية لإحتمالية استعادة المستخدمين إذا تم تضمينهم في النسخة الاحتياطية.';
$string['configrestoreuserscompletion'] = 'إذا تم تمكينها فإن معلومات الاكتمال للمستخدم بشكل افتراضي إذا تم تضمينها في النسخة الاحتياطية.';
$string['confirmcancel'] = 'إلغاء الحفظ الاحتياطي';
$string['confirmcancelimport'] = 'إلغاء الاستيراد';
$string['confirmcancelno'] = 'إبقى';
$string['confirmcancelquestion'] = 'هلأنت متأكد بأنك ترغب في القيام بعملية الإلغاء؟
جميع المعلومات التي أدخلتها ستفقد.';
$string['confirmcancelrestore'] = 'إلغاء الاستعادة';
$string['confirmcancelyes'] = 'إلغاء';
$string['confirmnewcoursecontinue'] = 'تنبيه المساق الجديد';
$string['confirmnewcoursecontinuequestion'] = 'سيتم إنشاء مساق مؤقت (مخفي) من قِبل عملية استعادة المساق. لإيقاف الاستعادة، أنقر على الإلغاء. لا تغلق المتصفح في أثناء الاستعادة.';
$string['coursecategory'] = 'الفئة التي سيتم إسترجاع المقرر الدراسي إليها';
$string['courseid'] = 'المعرف الأصلي';
$string['coursesettings'] = 'إعدادات المقرر';
$string['coursetitle'] = 'العنوان';
$string['currentstage1'] = 'الإعدادات المبدئية';
$string['currentstage16'] = 'إكتمل';
$string['currentstage2'] = 'إعدادات المخطط';
$string['currentstage4'] = 'التأكيد والاستعراض';
$string['currentstage8'] = 'تنفيذ الحفظ الاحتياطي';
$string['enableasyncbackup'] = 'تمكين النسخ الاحتياطية غير المتزامنة';
$string['enableasyncbackup_help'] = 'في حالة التمكين ، سيتم إجراء جميع عمليات النسخ الاحتياطي و الاستعادة بشكل غير متزامن.
هذا لا يؤثر على الستيراد و التصدير، حيث تسمح عمليات النسخ الاحتياطي و الاستعادة غير المتزامنة للمستخدمين بإجراء عمليات أخرى أثناء عملية النسخ الاحتياطي أو الاستعادة.';
$string['enterasearch'] = 'ادخل للبحث';
$string['error_block_for_module_not_found'] = 'تم العثور على كتلة يتيمة للمساق. هذه الكتلة لن تضمّن في النسخة الاحتياطية.';
$string['errorcopyingbackupfile'] = 'فَشِل نسخ ملف الحفظ الاحتياطي إلى المجلد المؤقت قبل الاستعادة.';
$string['error_course_module_not_found'] = 'تم العثور على كتلة يتيمة (id: {$a->bid}) لنموذج المساق (id: {$a->mid}). هذه الكتلة لن تضمّن في النسخة الاحتياطية.';
$string['errorfilenamemustbezip'] = 'يجب أن يكون الملف المدخل عبارة عن ملف مضغوط بإمتداد (mbz.)';
$string['errorfilenamerequired'] = 'يجب ان تدخل اسم ملف صحيح لنسخة الحفظ الاحتياطي';
$string['errorfilenametoolong'] = 'يجب أن يكون طول اسم الملف أقل من 255 حرفًا.';
$string['errorinvalidformat'] = 'صيغة الحفظ الاحتياطي غير معروفة';
$string['errorinvalidformatinfo'] = 'الملف المحدد غير صالح كملف مودل للحفظ الاحتياطي ولا يمكن استعادته.';
$string['errorminbackup20version'] = 'تم إنشاء ملف الحفظ الاحتياطي هذا بإصدار تطويري من الحفظ الاحتياطي لمودل ({$a->backup}). الحد الأدنى المطلوب هو {$a->min}. لا يمكن استعادته.';
$string['errorrestorefrontpagebackup'] = 'يمكنك استعادة الحفظ الاحتياطي للصفحة الأمامية إلى الصفحة الأمامية حصراً';
$string['executionsuccess'] = 'تم بنجاح إنشاء ملف الحفظ الاحتياطي.';
$string['failed'] = 'فَشِل الحفظ الاحتياطي';
$string['filealiasesrestorefailures'] = 'فشل استعادة الاسماء المستعارة';
$string['filealiasesrestorefailures_help'] = 'الأسماء المستعارة عبارة عن روابط رمزية لملفات أخرى، بما في ذلك تلك المخزنة في المستودعات الخارجية. في بعض الحالات، لا يمكن لمودل استعادتها - على سبيل المثال عند استعادة النسخة الاحتياطية في موقع آخر أو عند عدم وجود الملف المرجعي.

يمكن العثور على مزيد من التفاصيل والسبب الفعلي للفشل في ملف سجل وقوعات الاستعادة.';
$string['filealiasesrestorefailuresinfo'] = 'تعذرت استعادة بعض الأسماء المستعارة المضمنة في ملف النسخة الاحتياطية. تحتوي القائمة التالية على مواقعهم المتوقعة والملف المصدري الذي كانوا يشيرون إليه في الموقع الأصلي.';
$string['filename'] = 'إسم الملف';
$string['filereferencesincluded'] = 'يتم تضمين مراجع الملفات التي تشير إلى المحتويات الخارجية في ملف الحفظ الاحتياطي. لن تعمل هذه الماجع إذا تمت استعادة النسخة الاحتياطية على موقع مختلف.';
$string['filereferencesnotsamesite'] = 'ملف الحفظ الاحتياطي هو من موقع مختلف، لذلك لا يمكن استعادة مراجع الملفات.';
$string['filereferencessamesite'] = 'ملف الحفظ الاحتياطي هو من هذا الموقع، لذلك يمكن استعادة مراجع الملفات.';
$string['generalactivities'] = 'ضمن الأنشطة';
$string['generalanonymize'] = 'معلومات غير مشخصنة';
$string['generalbackdefaults'] = 'إفتراضيات الحفظ الاحتياطي العامة';
$string['generalbadges'] = 'تضمين الشارات';
$string['generalblocks'] = 'تضمين الكتل';
$string['generalcalendarevents'] = 'تضمين أحداث التقويم';
$string['generalcomments'] = 'تضمين التعليقات';
$string['generalcompetencies'] = 'تضمين الكفاءات';
$string['generalenrolments'] = 'تضمين طرق التسجيل';
$string['generalfiles'] = 'ضمّن الملفات';
$string['generalfilters'] = 'تضمين المرشحات';
$string['generalgradehistories'] = 'تضمين التاريخ';
$string['generalgroups'] = 'تضمين المجموعات والتجميعات';
$string['generalhistories'] = 'تضمين السوابق التاريخية';
$string['generallogs'] = 'تضمين سجلات الوقوعات';
$string['generalquestionbank'] = 'تضمين بنك الأسئلة';
$string['generalrestoredefaults'] = 'افتراضات الاستعادة العامة';
$string['generalrestoresettings'] = 'إعدادات الاستعادة العامة';
$string['generalroleassignments'] = 'تضمين تعيينات الأدوار';
$string['generalsettings'] = 'إعدادات الحفظ الاحتياطي العامة';
$string['generalusers'] = 'تضمين المستخدمين';
$string['generaluserscompletion'] = 'تضمين معلومات المستخدمين التكميلية';
$string['hidetypes'] = 'إخفاء خيارات النوع';
$string['importbackupstage16action'] = 'إستمرار';
$string['importbackupstage1action'] = 'التالي';
$string['importbackupstage2action'] = 'التالي';
$string['importbackupstage4action'] = 'تنفيذ الاستيراد';
$string['importbackupstage8action'] = 'إستمرار';
$string['importcurrentstage0'] = 'إختيار المقرر';
$string['importcurrentstage1'] = 'الإعدادات الأولية';
$string['importcurrentstage16'] = 'إكتمل';
$string['importcurrentstage2'] = 'إعدادات المخطط';
$string['importcurrentstage4'] = 'التأكيد والاستعراض';
$string['importcurrentstage8'] = 'تنفيذ الاستيراد';
$string['importfile'] = 'استيراد ملف الحفظ الاحتياطي';
$string['importgeneralduplicateadminallowed'] = 'السماح بحل المشرف للتعارض';
$string['importgeneralduplicateadminallowed_desc'] = 'إذا كان لدى الموقع حساب باسم المستخدم "admin”، فإن محاولة استعادة ملف نسخة احتياطية يحتوي على حساب باسم المستخدم "admin" يمكن أن يسبب تعارضًا. إذا تم تمكين هذا الإعداد، فسيتم حل التعارض عن طريق تغيير اسم المستخدم في ملف النسخة الاحتياطية إلى "admin_xyz".';
$string['importgeneralmaxresults'] = 'أقصى عدد من المساقات المدرجة للاستيراد';
$string['importgeneralmaxresults_desc'] = 'يتحكم هذا في عدد المساقات المدرجة أثناء الخطوة الأولى من عملية الاستيراد';
$string['importgeneralsettings'] = 'الافتراضيات العامة للاستيراد';
$string['importrootsettings'] = 'الإعدادات الاستيراد';
$string['importsettings'] = 'إعدادات الاستيراد العامة';
$string['importsuccess'] = 'إكتمل الاستيراد. أنقر على استمرار للرجوع إلى المساق';
$string['includeactivities'] = 'ضمن:';
$string['includeditems'] = 'البنود المتضمنة:';
$string['includefilereferences'] = 'مراجع الملف إلى محتويات خارجية';
$string['includesection'] = 'قسم {$a}';
$string['includeuserinfo'] = 'بيانات المستخدم';
$string['inprogress'] = 'النسخ الاحتياطي في التقدم';
$string['jumptofinalstep'] = 'القفز الى الخطوة النهائية';
$string['keep'] = 'إحتفظ به';
$string['locked'] = 'مغلق';
$string['lockedbyconfig'] = 'تم قفل هذا الإعداد بواسطة إعدادات الحفظ الاحتياطي الافتراضية';
$string['lockedbyhierarchy'] = 'مؤمن بواسطة التبِعات';
$string['lockedbypermission'] = 'لا تمتلك الصلاحيات الكافية لتغيير هذا الإعداد';
$string['loglifetime'] = 'الحفاظ على السجلات حتى';
$string['managefiles'] = 'إدارة ملفات الحفظ الاحتياطي';
$string['mergerestoredefaults'] = 'استعادة الإعدادات الافتراضية عند الدمج في مساق أخر';
$string['missingfilesinpool'] = 'تعذر حفظ بعض الملفات أثناء الحفظ الاحتياطي، وبالتالي لن يكون من الممكن استعادتها.';
$string['module'] = 'وحدة';
$string['moodleversion'] = 'إصدار مودل';
$string['morecoursesearchresults'] = 'تم العثور على أكثر من {$a} مساق (مساقات)، يتم عرض أول {$a} من النتائج';
$string['moreresults'] = 'يوجد نتائج كثيرة، الرجاء ادخال بحث أكثر دقة';
$string['nomatchingcourses'] = 'لا توجد مساقات لعرضها';
$string['norestoreoptions'] = 'لا يوجد تصنيفات أو مقررات لتستطيع القيام بعملية الإستراجاع إليها';
$string['originalwwwroot'] = 'رابط النسخة الاحتياطية';
$string['overwrite'] = 'استبدل';
$string['pendingasyncdeletedetail'] = 'تحتوي هذه المادة على نسخة احتياطية غير متزامنة معلقة.
لا يمكن حذف المواد حتى انتهاء النسخ الاحتياطي.';
$string['pendingasyncdetail'] = 'النسخ الاحتياطية غير المتزامنة تسمح فقط للمستخدم أن يكون نسخة احتياطية معلقة واحدة لمورد في وقت واحد.
لا يمكن وضع نسخ احتياطية متعددة غير متزامنة لنفس المورد في قائمة الانتظار ، لأن هذا قد ينتج عنه نسخ احتياطية متعددة مع نفس المحتوى.';
$string['pendingasyncedit'] = 'هناك نسخة احتياطية غير متزامنة معلقة لهذه المادة. يرجى عدم تعديل هذه الدورة حتى اكتمال النسخ الاحتياطي.';
$string['pendingasyncerror'] = 'النسخ الاحتياطي معلق لهذا المصادر';
$string['preparingdata'] = 'اعداد البيانات';
$string['preparingui'] = 'التحضير لعرض الصفحة';
$string['previousstage'] = 'السابق';
$string['privacy:metadata:backup_controllers'] = 'قائمة عمليات النسخ الاحتياطي';
$string['privacy:metadata:backup_controllers:itemid'] = 'مُعرَّف المساق';
$string['privacy:metadata:backup_controllers:operation'] = 'العملية التي أُنجرت، مثلاً: الاستعادة';
$string['privacy:metadata:backup_controllers:timecreated'] = 'الوقت الذي تم فيه إنشاء الإجراء';
$string['privacy:metadata:backup_controllers:timemodified'] = 'الوقت الذي تم فيه تعديل الإجراء';
$string['privacy:metadata:backup_controllers:type'] = 'نوعية الفقرة التي يجري العمل عليها، مثلاً: نشاط';
$string['privacy:metadata:backup:detailsofarchive'] = 'يمكن أن يحتوي هذا الأرشيف على العديد من بيانات المستخدم المتعلقة بالمساق، مثل العلامات إنضمامات المستخدم وبيانات النشاطات.';
$string['privacy:metadata:backup:externalpurpose'] = 'الغرض من هذا الأرشيف هو تخزين المعلومات المتعلقة بالمساقات، والتي يمكن استعادتها في المستقبل.';
$string['qcategory2coursefallback'] = 'صنف الأسئلة "{$a->name}”، الموجود في الأصل ضمن سياق الصنف النظام/المساق في ملف الحفظ الاحتياطي، سيتم إنشاؤه في سياق المساق عند الاستعادة';
$string['qcategorycannotberestored'] = 'لا يمكن إنشاء فئة الأسئلة "{$a->name}" بواسطة الاستعادة';
$string['question2coursefallback'] = 'صنف الأسئلة "{$a->name}”، الموجود في الأصل ضمن سياق الصنف النظام/المساق في ملف الحفظ الاحتياطي، سيتم إنشاؤه في سياق المساق عند الاستعادة';
$string['questionegorycannotberestored'] = 'لا يمكن إنشاء الأسئلة "{$a->name}" بواسطة الاستعادة';
$string['recyclebin_desc'] = 'لاحظ أن تلك الإعدادات سيتم استعمالها أيضاً مع سلة المحذوفات.';
$string['replacerestoredefaults'] = 'استعادة الإعدادات الافتراضية عند الاستعادة في مساق أخر عند حذف المحتويات';
$string['restoreactivity'] = 'إسترجاع النشاط';
$string['restorecourse'] = 'إسترجاع المقرر';
$string['restorecoursesettings'] = 'إعدادات المقرر';
$string['restoreexecutionsuccess'] = 'تم استرجاع المساق بنجاح، النقر على زر الاستمرار أدناه سيأخذك لمعاينة المساق الذي قمت باسترجاعه.';
$string['restorefileweremissing'] = 'تعذرت استعادة بعض الملفات لأنها كانت مفقودة في النسخة الاحتياطية.';
$string['restorenewcoursefullname'] = 'اسم المقرر الجديد';
$string['restorenewcourseshortname'] = 'مختصر اسم المقرر الجديد';
$string['restorenewcoursestartdate'] = 'تاريخ بدء جديد';
$string['restorerolemappings'] = 'استرجع تخطيط الدور';
$string['restorerootsettings'] = 'إسترجاع الإعدادات';
$string['restoresection'] = 'إسترجاع القسم';
$string['restorestage1'] = 'التأكيد';
$string['restorestage16'] = 'المراجعة';
$string['restorestage16action'] = 'تنفيذ الاسترجاع';
$string['restorestage1action'] = 'التالي';
$string['restorestage2'] = 'الوجهة';
$string['restorestage2action'] = 'التالي';
$string['restorestage32'] = 'العملية';
$string['restorestage32action'] = 'استمرار';
$string['restorestage4'] = 'الإعدادات';
$string['restorestage4action'] = 'التالي';
$string['restorestage64'] = 'إكمال';
$string['restorestage64action'] = 'استمرار';
$string['restorestage8'] = 'مخطط';
$string['restorestage8action'] = 'التالي';
$string['restoretarget'] = 'إرجاع الهدف';
$string['restoretocourse'] = 'إستعادة المقرر:';
$string['restoretocurrentcourse'] = 'إستعادة لهذا المقرر';
$string['restoretocurrentcourseadding'] = 'دمج المساق الاحتياطي مع هذا المساق';
$string['restoretocurrentcoursedeleting'] = 'احذف محتويات هذا المقرر تم قم بإسترجاعه';
$string['restoretoexistingcourse'] = 'الاسترجاع إلى مساق موجود';
$string['restoretoexistingcourseadding'] = 'دمج المساق الاحتياطي مع المساق الموجود';
$string['restoretoexistingcoursedeleting'] = 'حذف محتويات المساق الموجود ثم القيام بالاسترجاع';
$string['restoretonewcourse'] = 'الاسترجاع كمساق جديد';
$string['restoringcourse'] = 'عملية إسترجاع المقرر قيد التنفيذ';
$string['restoringcourseshortname'] = 'إسترجاع';
$string['rootenrolmanual'] = 'استرجاع كتسجيل يدوي';
$string['rootsettingactivities'] = 'ضمن الأنشطة';
$string['rootsettinganonymize'] = 'عدم شخصنة معلومات المستخدمين';
$string['rootsettingbadges'] = 'تضمين الشارات';
$string['rootsettingblocks'] = 'تضمين الكتل';
$string['rootsettingcalendarevents'] = 'تضمين أحداث التقويم';
$string['rootsettingcomments'] = 'تضمين التعليقات';
$string['rootsettingcompetencies'] = 'تضمين الكفاءات';
$string['rootsettingcustomfield'] = 'تضمين الحقول المخصصة';
$string['rootsettingenrolments'] = 'تضمين طرق الانضمام';
$string['rootsettingenrolments_always'] = 'نعم دائما';
$string['rootsettingenrolments_never'] = 'لا ، استعد المستخدمين كأنها تسجيلات اليدوية';
$string['rootsettingenrolments_withusers'] = 'نعم ، ولكن فقط إذا تم تضمين المستخدمين';
$string['rootsettingfiles'] = 'تضمين الملفات';
$string['rootsettingfilters'] = 'تضمين المرشحات';
$string['rootsettinggradehistories'] = 'تضمين ماضي العلامات';
$string['rootsettinggroups'] = 'تضمين المجموعات والتجميعات';
$string['rootsettingimscc1'] = 'تحويل لفيفة IMS العامة إلى1.0';
$string['rootsettingimscc11'] = 'تحويل لفيفة IMS العامة إلى1.1';
$string['rootsettinglogs'] = 'تضمن سجلات وقوعات المساق';
$string['rootsettingquestionbank'] = 'تضمين بنك الأسئلة';
$string['rootsettingroleassignments'] = 'تضمن تعيينات أدوار المستخدمين';
$string['rootsettings'] = 'إعدادات الحفظ الاحتياطي';
$string['rootsettingusers'] = 'تضمين المستخدمين المنضمين';
$string['rootsettinguserscompletion'] = 'تضمين تفاصيل الإكمال للمستخدمين';
$string['samesitenotification'] = 'تم إنشاء هذه النسخة الاحتياطية بمسارات الملفات فقط، و ليست الملفات نفسها. ستعمل الاستعادة على هذه المسارات فقط.';
$string['sectionactivities'] = 'الأنشطة';
$string['sectioninc'] = 'تم تضمينها في الحفظ الاحتياطي (بدون معلومات المستخدمين)';
$string['sectionincanduser'] = 'تم التضمين في الحفظ الاحتياطي مع معلومات المستخدم';
$string['selectacategory'] = 'إختر التصنيف';
$string['selectacourse'] = 'إختر المساق';
$string['setting_course_fullname'] = 'اسم المساق';
$string['setting_course_shortname'] = 'الاسم المختصر للمساق';
$string['setting_course_startdate'] = 'تاريخ بدء المساق';
$string['setting_keep_groups_and_groupings'] = 'الاحتفاظ بالمجموعات والتجمُّعات الحالية';
$string['setting_keep_roles_and_enrolments'] = 'الاحتفاظ بالأدوار والتسجيلات الحالية';
$string['setting_overwrite_conf'] = 'اسبدال اعدادات المساق';
$string['setting_overwrite_course_fullname'] = 'اسبدال الاسم الكامل للمساق';
$string['setting_overwrite_course_shortname'] = 'اسبدال الاسم المختصر للمساق';
$string['setting_overwrite_course_startdate'] = 'استبدال تاريخ بدء المساق';
$string['showtypes'] = 'إظهار خيارات الأنواع';
$string['sitecourseformatwarning'] = 'هنا النسخة الاحتياطية للصفحة الأولى، لاحظ أن هذه النسخة لا يمكن استردادها إلا من  الصفحة الأولى';
$string['skiphidden'] = 'تخطى المساقات المخفية';
$string['skiphiddenhelp'] = 'إختر إما تخطي المساقات المخفية أو عدم تخطيها';
$string['skipmodifdays'] = 'تخطى المساقات التي لم يتم تعديلها منذ';
$string['skipmodifdayshelp'] = 'إختر تخطي المساقات التي لم يتم تعديلها منذ عدد معين من الأيام';
$string['skipmodifprev'] = 'تخطى المساقات التي لم تتغير منذ الحفظ الاحتياطي السابق';
$string['skipmodifprevhelp'] = 'إختر فيما إذا كان ينبغي تخطي المساقات التي لم يتم تعديلها منذ الحفظ الاحتياطي التلقائي الأخير. هذا يتطلب تمكين سجل الوقوعات.';
$string['status'] = 'الحالة';
$string['storagecourseandexternal'] = 'منطقة ملفات الحفظ الاحتياطي للمساق والمجلد المحدد';
$string['storagecourseonly'] = 'منطقة ملفات الحفظ الاحتياطي للمساق';
$string['storageexternalonly'] = 'المجلد المحدد للحفظ الاحتياطي التلقائي';
$string['successful'] = 'نجح الحفظ الاحتياطي';
$string['successfulrestore'] = 'استعادة ناجحة';
$string['timetaken'] = 'الوقت المستغرق';
$string['title'] = 'عنوان';
$string['totalcategorysearchresults'] = 'مجموع التصنيفات : {$a}';
$string['totalcoursesearchresults'] = 'إجمالي المساقات: {$a}';
$string['undefinedrolemapping'] = 'تعيين الأدوار غير معرّف لنموذج \'{$a}\'.';
$string['unnamedsection'] = 'قسم غير مُسمَّى';
$string['userinfo'] = 'معلومات المُستخدم';
