<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'message', language 'ar', version '4.1'.
 *
 * @package     message
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['acceptandaddcontact'] = 'إقبل وأضف إلى جهات الاتصال';
$string['addcontact'] = 'إضافة جهة اتصال';
$string['addcontactconfirm'] = 'هل أنت متأكد من رغبتك في إضافة {$a} إلى جهات اتصالك؟';
$string['addtofavourites'] = 'ضع نجمة على المحادثة';
$string['addtoyourcontacts'] = 'أضف إلى جهات الاتصال';
$string['addtoyourcontactsandmessage'] = 'أضف إلى جهات الاتصال وراسل';
$string['ago'] = '{$a} مضى';
$string['allusers'] = 'كل الرسائل من جميع المستخدمين';
$string['backto'] = 'عودة إلى {$a}';
$string['backupmessageshelp'] = 'لو مُكِّن، سيتم تضمين الرسائل الفورية في الحفظ الاحتياطي التلقائي لـ SITE';
$string['blockcontact'] = 'حظر جهة الاتصال';
$string['blockedusers'] = 'المستخدمون المحظورون';
$string['blocknoncontacts'] = 'امنع المستخدمين الذين ليسوا في قائمة اتصالاتي من مراسلتي';
$string['blockuser'] = 'حظر المستخدم';
$string['blockuserconfirm'] = 'هل أنت متأكد من رغبتك في حظر {$a}؟';
$string['blockuserconfirmbutton'] = 'كتلة';
$string['cancelselection'] = 'إلغاء تحديد الرسالة';
$string['cantblockuser'] = 'لا يمكنك حظر {$a} لأن لديهم دور بصلاحية مراسلة كل المستخدمين.';
$string['contactableprivacy'] = 'إقبل الرسائل من:';
$string['contactableprivacy_coursemember'] = 'جهات اتصالي وأي أحد في مقرراتي';
$string['contactableprivacy_onlycontacts'] = 'جهات اتصالي فقط';
$string['contactableprivacy_site'] = 'أي أحد في الموقع';
$string['contactblocked'] = 'تم حظر جهة الاتصال';
$string['contactrequests'] = 'طلبات الاتصال';
$string['contactrequestsent'] = 'طلب الاتصال أُرسل';
$string['contacts'] = 'جهات اتصال';
$string['conversationactions'] = 'قائمة إجراءات المحادثة';
$string['decline'] = 'أرفض';
$string['defaultmessageoutputs'] = 'إعدادات الاشعارات';
$string['defaults'] = 'الافتراضيات';
$string['deleteallconfirm'] = 'هل أنت متأكد من رغبتك في حذف هذه المحادثة بالكامل؟ هذا لن يحذفها من جهة أطرافها الأخرى.';
$string['deleteallmessages'] = 'حذف جميع الرسائل';
$string['deleteallselfconfirm'] = 'هل أنت متأكد من رغبتك في حذف هذه المحادثة الشخصية بالكامل؟';
$string['deleteconversation'] = 'إحذف المحادثة';
$string['deleteforeveryone'] = 'إحذفها عندي وعند الآخرين';
$string['deleteforeveryoneselectedmessagesconfirm'] = 'هل أنت متأكد من رغبتك في حذف الرسائل المحددة؟';
$string['deleteselectedmessages'] = 'حذف الرسائل المختارة';
$string['deleteselectedmessagesconfirm'] = 'هل أنت متأكد من رغبتك في حذف الرسائل المحددة؟ هذا لن يحذفها من جهة أطرافها الأخرى.';
$string['deleteselectedmessagesconfirmselfconversation'] = 'هل أنت متأكد من رغبتك في حذف الرسائل الشخصية المحددة؟';
$string['disableall'] = 'تعطيل الاشعارات';
$string['disabled'] = 'المحادثات غير مفعّلة على هذا الموقع';
$string['disallowed'] = 'مقفل';
$string['editmessages'] = 'تعديل الرسائل';
$string['emailtagline'] = 'هذه نسخة من رسالة أرسلت لك من الموقع {$a->sitename}. لترد عليها، إذهب إلى <a href="{$a->url}">{$a->url}</a>.';
$string['enabled'] = 'تم تفعيله';
$string['errorcallingprocessor'] = 'خطأ عند استدعاء الناتج المُعرَّف';
$string['errorconversationdoesnotexist'] = 'المحادثة غير موجودة';
$string['errormessagetoolong'] = 'الرسالة تزيد على الحد الأقصى المسموح به.';
$string['errortranslatingdefault'] = 'خطأ عند ترجمة الإعداد الافتراضي المقدم من قبل الإضافة. يجري استعمال إفتراضات النظام بدلاً منه.';
$string['eventgroupmessagesent'] = 'رسالة إلى مجموعة تم إرسالها';
$string['eventmessagecontactadded'] = 'جهة اتصال تمت إضافتها';
$string['eventmessagecontactremoved'] = 'جهة اتصال تم حذفها';
$string['eventmessagedeleted'] = 'رسالة تم حذفها';
$string['eventmessagesent'] = 'رسالة تم إرسالها';
$string['eventmessageuserblocked'] = 'مستخدم تم حظره';
$string['eventmessageuserunblocked'] = 'مستخدم تم إلغاء حظره';
$string['eventmessageviewed'] = 'رسالة تمت معاينتها';
$string['eventnotificationsent'] = 'إشعار تم إرساله';
$string['eventnotificationviewed'] = 'إشعار تمت معاينته';
$string['forced'] = 'مغلق';
$string['forcedmessage'] = 'مفتوح';
$string['groupconversations'] = 'المجموعة';
$string['groupinfo'] = 'معلومات المجموعة';
$string['guestnoeditmessage'] = 'لا يمكن للمستخدم الضيف تعديل خيارات المحادثة';
$string['guestnoeditmessageother'] = 'لا يمكن للمستخدم الضيف تغيير خيارات المحادثة لمستخدم آخر';
$string['hidemessagewindow'] = 'إخفاء نافذة الرسالة';
$string['hidenotificationwindow'] = 'إخفاء نافذة الاشعارات';
$string['individualconversations'] = 'خاصة';
$string['info'] = 'معلومات المستخدم';
$string['isnotinyourcontacts'] = '{$a} ليس ضمن جهات اتصالك';
$string['loadmore'] = 'تحميل المزيد';
$string['loggedin'] = 'متواجد';
$string['loggedin_help'] = 'إعداد طريقة استلامك للاشعارات عند دخولك إلى مودل';
$string['loggedindescription'] = 'عند تسجيل دخولك إلى مودل';
$string['loggedoff'] = 'غير متصل';
$string['loggedoff_help'] = 'حدد كيف تريد استلام الاشعارات عندما لا تكون متواجداً في مودل';
$string['loggedoffdescription'] = 'عندما لا تكون متواجداً في مودل';
$string['managemessageoutputs'] = 'التفضيلات الافتراضية للإشعارات';
$string['message'] = 'الرسالة';
$string['messagecontactrequest'] = '{$a->user} يلتمس إضافته كجهة اتصال. قم بزيارة صفحة <a href="{$a->url}">طلبات الاتصال</a> للاستجابة لهذا الطلب';
$string['messagecontactrequestsubject'] = '{$a->sitename}: طلب اتصال من {$a->user}';
$string['messagecontentaudio'] = 'صوت';
$string['messagecontentimage'] = 'صورة';
$string['messagecontentmultimediageneral'] = 'وسائط أخرى';
$string['messagecontentvideo'] = 'فيديو';
$string['messagedrawerviewcontact'] = 'تفاصيل المستخدم {$a}';
$string['messagedrawerviewcontacts'] = 'مراسلة جهات الاتصال';
$string['messagedrawerviewconversation'] = 'المحادثة مع {$a}';
$string['messagedrawerviewgroupinfo'] = 'تفاصيل المجموعة {$a}';
$string['messagedrawerviewoverview'] = 'المراسلات بنظرة عامة';
$string['messagedrawerviewsearch'] = 'نتائج البحث في المراسلات عن {$a}';
$string['messagedrawerviewsettings'] = 'إعدادات المراسلة';
$string['messageoutputs'] = 'إضافات الإشعارات';
$string['messagepreferences'] = 'تفضيلات المراسلة';
$string['messages'] = 'الرسائل';
$string['messagesselected:'] = 'المراسلات المحددة:';
$string['messagetextrequired'] = 'يرجى إدخال نص الرسالة';
$string['messagingdatahasnotbeenmigrated'] = 'مراسلاتك غير متاحة مؤقتاً بسبب الترقية في البنية التحتية لنظام المراسلة. لطفاً، انتظر إكتمال عملية ترحيلها.';
$string['muteconversation'] = 'كتم';
$string['mutedconversation'] = 'محادثة مكتومة';
$string['newmessage'] = 'رسالة جديدة';
$string['newmessagesearch'] = 'إختر أو ابحث عن جهة اتصال لإرسال الرسالة الجديدة.';
$string['newonlymsg'] = 'عرض الجديد فقط';
$string['nocontactrequests'] = 'لا طلبات اتصال';
$string['nocontacts'] = 'لا توجد جهات اتصال';
$string['nocontactsgetstarted'] = 'لا جهات اتصال';
$string['nofavourites'] = 'لا محادثات معلمة بنجمة';
$string['noframesjs'] = 'استعمل واجهة أسهل';
$string['nogroupconversations'] = 'لا محادثات جماعية';
$string['noindividualconversations'] = 'لا محادثات خاصة';
$string['nomessagesfound'] = 'لم يتم العثور على إي رسالة';
$string['noncontacts'] = 'من غير جهات الاتصال';
$string['nonotifications'] = 'ليس لديك اشعارات';
$string['noparticipants'] = 'لا مشاركين';
$string['noreply'] = 'لا ترد على هذه الرسالة';
$string['notificationdatahasnotbeenmigrated'] = 'إشعاراتك غير متاحة مؤقتاً بسبب الترقية في البنية التحتية لنظام الإشعارات. لطفاً، انتظر إكتمال عملية ترحيلها.';
$string['notificationimage'] = 'صورة الاشعار';
$string['notificationpreferences'] = 'تفضيلات الإشعارات';
$string['notifications'] = 'الإشعارات';
$string['notificationwindow'] = 'نافذة الاشعار';
$string['notincontacts'] = 'أنت بحاجة إلى إضافة {$a} إلى جهات اتصالك لتتمكن من مراسلتهم.';
$string['notincontactsheading'] = '{$a} ليس ضمن جهات اتصالك';
$string['numparticipants'] = '{$a} مشاركين';
$string['off'] = 'متوقف';
$string['offline'] = 'غير متصل بالأنترنت';
$string['on'] = 'شغال';
$string['online'] = 'متصل بالإنترنت';
$string['otherparticipants'] = 'المشاركون الآخرون';
$string['outputnotavailable'] = 'غير متاح';
$string['page-message-x'] = 'صفحات أي رسالة';
$string['participants'] = 'المشاركون';
$string['pendingcontactrequests'] = 'هناك {$a} طلبات اتصال معلقة';
$string['permitted'] = 'مسموح به';
$string['privacy'] = 'الخصوصية';
$string['privacy:export:conversationprefix'] = 'المحادثة:';
$string['privacy:metadata:core_favourites'] = 'المحادثة المعلمة بنجمة من قبل المستخدم';
$string['privacy:metadata:message_contact_requests'] = 'قائمة طلبات المراسلة';
$string['privacy:metadata:message_contact_requests:requesteduserid'] = 'مُعرَّف المستخدم الذي تلقى طلب المراسلة';
$string['privacy:metadata:message_contact_requests:timecreated'] = 'وقت إنشاء طلب المراسلة';
$string['privacy:metadata:message_contact_requests:userid'] = 'مُعرَّف المستخدم الذي أرسل طلب المراسلة';
$string['privacy:metadata:message_contacts'] = 'قائمة جهات الاتصال';
$string['privacy:metadata:message_contacts:contactid'] = 'مُعرَّف المستخدم الذي يعتبر جهة اتصال';
$string['privacy:metadata:message_contacts:timecreated'] = 'وقت إنشاء جهة الاتصال';
$string['privacy:metadata:message_contacts:userid'] = 'مُعرَّف المستخدم الذي نحن نعاين قائمة جهات اتصاله';
$string['privacy:metadata:message_conversation_actions'] = 'قائمة إجراءات محادثات المستخدم';
$string['privacy:metadata:message_conversation_actions:action'] = 'الإجراء الذي تم اتخاذه';
$string['privacy:metadata:message_conversation_actions:conversationid'] = 'مُعرَّف المحادثة التي يعود إليها هذا الإجراء';
$string['privacy:metadata:message_conversation_actions:timecreated'] = 'وقت إنشاء الإجراء';
$string['privacy:metadata:message_conversation_actions:userid'] = 'مُعرَّف المستخدم الذي قام بالإجراء';
$string['privacy:metadata:message_conversation_members'] = 'قائمة المستخدمين في المحادثة';
$string['privacy:metadata:message_conversation_members:conversationid'] = 'مُعرَّف المحادثة';
$string['privacy:metadata:message_conversation_members:timecreated'] = 'وقت إنشاء العضو';
$string['privacy:metadata:message_conversation_members:userid'] = 'مُعرَّف المستخدم ضمن المحادثة';
$string['privacy:metadata:message_user_actions'] = 'قائمة إجراءات مراسلات المستخدم';
$string['privacy:metadata:message_user_actions:action'] = 'الإجراء الذي تم اتخاذه';
$string['privacy:metadata:message_user_actions:messageid'] = 'مُعرَّف الرسالة التي يعود إليها هذا الإجراء';
$string['privacy:metadata:message_user_actions:timecreated'] = 'وقت إنشاء الإجراء';
$string['privacy:metadata:message_user_actions:userid'] = 'مُعرَّف المستخدم الذي اتخذ الإجراء';
$string['privacy:metadata:message_users_blocked'] = 'قائمة المستخدمين المحظورين';
$string['privacy:metadata:message_users_blocked:blockeduserid'] = 'مُعرَّف المستخدم الذي تم حظره';
$string['privacy:metadata:message_users_blocked:timecreated'] = 'وقت إنشاء إجراء الحظر';
$string['privacy:metadata:message_users_blocked:userid'] = 'مُعرَّف المستخدم الذي أجرى الحظر';
$string['privacy:metadata:messages'] = 'المراسلات';
$string['privacy:metadata:messages:conversationid'] = 'مُعرَّف المحادثة';
$string['privacy:metadata:messages:customdata'] = 'بيانات مخصصة، عادة ما تضم المعرفات الداخلية ورابط عمومي لصورة المرسل (فرداً أو مجموعة)';
$string['privacy:metadata:messages:fullmessage'] = 'المراسلة الكاملة';
$string['privacy:metadata:messages:fullmessageformat'] = 'تنسيق المراسلة الكاملة';
$string['privacy:metadata:messages:fullmessagehtml'] = 'تنسيق HTML للمراسلة الكاملة';
$string['privacy:metadata:messages:smallmessage'] = 'نسخة مصغرة من المراسلة';
$string['privacy:metadata:messages:subject'] = 'موضوع المراسلة';
$string['privacy:metadata:messages:timecreated'] = 'وقت إنشاء المراسلة';
$string['privacy:metadata:messages:useridfrom'] = 'مُعرَّف المستخدم الذي أرسل الرسالة';
$string['privacy:metadata:notifications'] = 'الإشعارات';
$string['privacy:metadata:notifications:component'] = 'المكون المسؤول عن إرسال الإشعار';
$string['privacy:metadata:notifications:contexturl'] = 'الرابط المتعلق بهذا الإشعار';
$string['privacy:metadata:notifications:contexturlname'] = 'اسم السياق';
$string['privacy:metadata:notifications:customdata'] = 'بيانات مخصصة، عادة ما تضم المعرفات الداخلية ورابط عمومي لصورة المرسل (إن وجد)';
$string['privacy:metadata:notifications:eventtype'] = 'نوع الحدث';
$string['privacy:metadata:notifications:fullmessage'] = 'الإشعار الكامل';
$string['privacy:metadata:notifications:fullmessageformat'] = 'تنسيق الإشعار';
$string['privacy:metadata:notifications:fullmessagehtml'] = 'ترميز HTML للإشعار';
$string['privacy:metadata:notifications:smallmessage'] = 'الرسالة المصغرة للإشعار';
$string['privacy:metadata:notifications:subject'] = 'موضوع الإشعار';
$string['privacy:metadata:notifications:timecreated'] = 'وقت إنشاء الإشعار';
$string['privacy:metadata:notifications:timeread'] = 'وقت قراءة الإشعار';
$string['privacy:metadata:notifications:useridfrom'] = 'مُعرَّف المستخدم الذي أرسل الإشعار';
$string['privacy:metadata:notifications:useridto'] = 'مُعرَّف المستخدم الذي تلقى الإشعار';
$string['privacy:metadata:preference:core_message_settings'] = 'الإعدادات المتعلقة بالمراسلة';
$string['privacy:request:preference:set'] = 'قيمة الإعداد \'{$a->name}\' كانت \'{$a->value}\'';
$string['privacy_desc'] = 'بإمكانك تقييد من تسمح له بمراسلتك';
$string['processorsettings'] = 'اعدادات المعالج';
$string['providerenabled'] = 'إرسال حالة تمكين "{$a}"';
$string['providerprocesorisdisallowed'] = '"{$a->provider}" عند "{$a->processor}" مقفل';
$string['providerprocesorislocked'] = '"{$a->provider}" عند "{$a->processor}" مفتوح';
$string['removecontact'] = 'ازل جهة الاتصال';
$string['removecontactconfirm'] = 'هل أنت متأكد من رغبتك في إزالة {$a} من جهات اتصالك؟';
$string['removecoursefilter'] = 'أزل المرشح من المساق {$a}';
$string['removefromfavourites'] = 'إرفع النجمة عن المحادثة';
$string['removefromyourcontacts'] = 'إحذف من جهات اتصالك';
$string['requirecontacttomessage'] = 'أنت بحاجة إلى مطالبة {$a} لإضافتك إلى جهات اتصالهم لتتمكن من مراسلتهم.';
$string['requiresconfiguration'] = 'يتطلب التهيئة';
$string['searchcombined'] = 'البحث عن الأشخاص والرسائل';
$string['searchforuser'] = 'البحث عن مستخدم';
$string['searchforuserorcourse'] = 'ابحث عن مستخدم أو مساق';
$string['searchmessages'] = 'البحث في الرسائل';
$string['seeall'] = 'مشاهدة الكل';
$string['selectmessagestodelete'] = 'إختر رسائل لحذفها';
$string['selectnotificationtoview'] = 'إختر من قائمة الاشعارات لعرض تفاصيل أكثر';
$string['selfconversation'] = 'الحيز الشخصي';
$string['selfconversationdefaultmessage'] = 'إحفظ مسودات المراسلات، الروابط، الملاحظات... إلخ. لاستعمالها لاحقاً.';
$string['send'] = 'ارسال';
$string['sendbulkmessage'] = 'أرسل الرسالة إلى {$a} شخص';
$string['sendbulkmessagesent'] = 'الرسالة أُرسلت إلى {$a} شخص';
$string['sendbulkmessagesentsingle'] = 'تم ارسال الرسالة إلى شخص واحد';
$string['sendbulkmessagesingle'] = 'ارسل إلى شخص واحد';
$string['sendcontactrequest'] = 'أرسل طلب مراسلة';
$string['sender'] = '{$a}:';
$string['sendingvia'] = 'يجري إرسال "{$a->provider}" بواسطة "{$a->processor}"';
$string['sendingviaenabled'] = 'إرسال حالة تمكين "{$a->provider}" بواسطة "{$a->processor}"';
$string['sendingvialocked'] = 'إرسال حالة تأمين "{$a->provider}" بواسطة "{$a->processor}"';
$string['sendingviawhen'] = 'يجري إرسال "{$a->provider}" بواسطة "{$a->processor}" عند {$a->state}';
$string['sendmessage'] = 'أرسل الرسالة';
$string['sendmessageto'] = 'أرسل رسالة إلى {$a}';
$string['sendmessagetopopup'] = 'أرسل رسالة إلى {$a} - نافذة جديدة';
$string['settings'] = 'إعدادات';
$string['showmessagewindownonew'] = 'أظهر نافذة المراسلة بدون المراسلات الجديدة';
$string['showmessagewindowwithcount'] = 'أظهر نافذة المراسلة مع {$a} مراسلات جديدة';
$string['shownotificationwindownonew'] = 'أظهر نافذة الإشعارات بدون الإشعارات الجديدة';
$string['shownotificationwindowwithcount'] = 'أظهر نافذة الإشعارات مع {$a} إشعارات جديدة';
$string['togglemessagemenu'] = 'تبديل دُرج المراسلة';
$string['togglenotificationmenu'] = 'تبديل قائمة الإشعارات';
$string['totalconversations'] = '{$a} محادثات إجمالاً';
$string['touserdoesntexist'] = 'لا يمكنك إرسال رسالة إلى المستخدم ذي المُعرَّف ({$a}) الذي لا وجود له.';
$string['unabletomessage'] = 'لستَ قادراً على مراسلة هذا المستخدم';
$string['unblock'] = 'إرفع الحظر';
$string['unblockcontact'] = 'إزالة الحجب عن هذا الشخص';
$string['unblockuser'] = 'إرفع حظر المستخدم';
$string['unblockuserconfirm'] = 'هل أنت متأكد من رغبتك في رفع الحظر عن {$a}؟';
$string['unknownuser'] = 'مستخدم مجهول';
$string['unmuteconversation'] = 'إزالة الكتم';
$string['unreadconversations'] = 'هناك {$a} من المحادثات غير مقروءة';
$string['unreadmessages'] = 'هناك {$a} من المراسلات غير مقروءة';
$string['unreadnewgroupconversationmessage'] = 'رسالة جديدة من {$a->name} ضمن {$a->conversationname}';
$string['unreadnewmessage'] = 'رسالة جديدة من {$a}';
$string['unreadnotification'] = 'الإشعارات غير المقروءة: {$a}';
$string['unreadnotifications'] = 'هناك {$a} من الإشعارات غير مقروءة';
$string['useentertosend'] = 'استعمل مفتاح الرجوع للإرسال';
$string['usercantbemessaged'] = 'لا يمكنك مراسلة هذا المستخدم بسبب تفضيلات المراسلة لديه. حاول إضافته إلى جهات اتصالك.';
$string['userwouldliketocontactyou'] = '{$a} يود التواصل معك';
$string['viewfullnotification'] = 'معاينة الإشعار الكامل';
$string['viewmessageswith'] = 'معاينة المراسلات مع {$a}';
$string['viewnotificationresource'] = 'إذهب إلى: {$a}';
$string['viewunreadmessageswith'] = 'معاينة المراسلات غير المقروءة مع {$a}';
$string['wouldliketocontactyou'] = 'يرغب بالتواصل معك';
$string['writeamessage'] = 'أُكتب رسالة...';
$string['you'] = 'أنت:';
$string['youhaveblockeduser'] = 'لقد قمتَ بحظر هذا المستخدم.';
$string['yourcontactrequestpending'] = 'طلبك للمراسلة معلق مع {$a}';
