<?php

// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'hub', language 'eu', branch 'MOODLE_34_STABLE'
 *
 * @package   hub
 * @copyright 1999 onwards Martin Dougiamas  {@link http://moodle.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['addscreenshots'] = 'Gehitu pantaila-argazkia';
$string['advertise'] = 'Partekatu ikastaro hau jendea matrikulatzeko';
$string['advertised'] = 'Jendea matrikulatzeko iragarrita';
$string['advertiseon'] = 'Partekatu ikastaro hau {$a}-n';
$string['advertiseonhub'] = 'Eman ikastaro honen berri jendea matrikulatzeko';
$string['advertiseonmoodleorg'] = 'Eman ikastaro honen berri moodle.org-n';
$string['advertisepublication_help'] = 'Ikastaro hau Moodle.net gunean zerrendatuko da jendea matrikulatu eta parte hartu dezakeen ikastaro gisa. Gunean e-posta bidezko autentifikazioa gaituta egon beharko litzateke eta zure ikastaroan ere auto-matrikulazioa gaitu beharko zenuke.';
$string['all'] = 'Guztiak';
$string['allowglobalsearch'] = 'Argitaratu bilgune hau eta baimendu ikastaro guztien bilaketa orokorra';
$string['allowpublicsearch'] = 'Argitaratu bilgune hau jendea matrikulatu ahal izateko';
$string['audience'] = 'Publikoa';
$string['audienceadmins'] = 'Moodle kudeatzaileak';
$string['audienceeducators'] = 'Irakasleak';
$string['audience_help'] = 'Aukeratu ikastaro honentzako hartzaileak';
$string['audiencestudents'] = 'Ikasleak';
$string['badgesnumber'] = 'Domina-kopurua: ({$a})';
$string['badurlformat'] = 'Okerreko URL formatua';
$string['cannotsearchcommunity'] = 'Sentitzen dugu, ez duzu baimenik orri hau ikusteko';
$string['community'] = 'Komunitatea';
$string['communityremoved'] = 'Ikastaro hau zure zerrendatik ezabatu da';
$string['completeregistration'] = 'Osatu Moodle.net-eko erregistroa';
$string['confirmregistration'] = 'Baieztatu erregistroa';
$string['contactable'] = 'Kanpokoentzako kontaktua';
$string['contactable_help'] = 'Bai aukeratuz gero, bilgunean zure e-posta helbidea erakutsiko da.';
$string['contactemail'] = 'Kontakturako e-posta';
$string['contactname'] = 'Kontakturako izena';
$string['contactphone'] = 'Telefonoa';
$string['contactphone_help'] = 'Telefono-zenbakiak ikastaroen bilguneko kudeatzaileak baino ez ditu ikusiko eta ez dira publikoak';
$string['continue'] = 'Jarraitu';
$string['contributornames'] = 'Beste kolaboratzaile batzuk';
$string['contributornames_help'] = 'Eremu hau ikastaroa sortzen lagundu duten pertsonak zerrendatzeko erabil dezakezu.';
$string['coursemap'] = 'Ikastaroaren mapa';
$string['coursename'] = 'Izena';
$string['courseprivate'] = 'Pribatua';
$string['coursepublic'] = 'Publikoa';
$string['coursepublished'] = 'Ikastaro hau ondo argitaratu da hemen: \'{$a}\'.';
$string['courseshortname'] = 'Izen laburra';
$string['courseshortname_help'] = 'Idatz ezazu izen laburra zure ikastarorako. Ez du zertan bkarra izan.';
$string['coursesnumber'] = 'Ikastaro-kopurua: ({$a})';
$string['courseunpublished'] = '{$a->courseshortname} ikastaroa dagoeneko ez dago argitaratuta hemen: {$a->hubname}';
$string['courseurl'] = 'Ikastaroaren URLa';
$string['courseurl_help'] = 'Ikastaroaren URLa da. URL hau bilaketa baten emaitzean esteka gisa agertuko da.';
$string['creatorname'] = 'Sortzailea';
$string['creatorname_help'] = 'Sortzailea ikastaro-sortzailea da.';
$string['creatornotes'] = 'Sortzailearen oharrak';
$string['creatornotes_help'] = 'Sortzailearen oharrek ikastaroaren erabilerari buruzko gida osatzen dute irakasleentzat.';
$string['deletescreenshots'] = 'Ezabatu pantaila-argazki hauek';
$string['deletescreenshots_help'] = 'Ezabatu une honetan igota dauden pantaila-argazki guztiak.';
$string['demourl'] = 'Demoaren URLa';
$string['demourl_help'] = 'Idatzi zure demostrazio-ikastaroaren URL helbidea. Modu lehenetsian ikastaroaren URLa da. Demostrazio-ikastaroaren URLa bilaketa-emaitzetan esteka gisa agertuko da.';
$string['description'] = 'Deskribapena';
$string['description_help'] = 'Deskribapen-testu hau Moodle.net guneko ikastaro-zerrendan erakutsiko da.';
$string['detectednotexistingpublication'] = '{$a->hubname} dagoeneko existitzen ez den ikastaroa zerrendatzen ari da. Abisatu {$a->hubname}-ko kudeatzaileari {$a->id} argitalpen-zenbakia ezabatu behar duela.';
$string['downloadable'] = 'Jaits daiteke';
$string['educationallevel'] = 'Hezkuntza-maila';
$string['educationallevel_help'] = 'Aukeratu ikastaro honetarako hezkuntza-maila egokiena.';
$string['edulevelassociation'] = 'Elkartea';
$string['edulevelcorporate'] = 'Enpresa';
$string['edulevelgovernment'] = 'Gobernua';
$string['edulevelother'] = 'Bestelakoa';
$string['edulevelprimary'] = 'Lehen hezkuntza';
$string['edulevelsecondary'] = 'Bigarren hezkuntza';
$string['eduleveltertiary'] = 'Hirugarren hezkuntza';
$string['emailalert'] = 'E-posta bidezko jakinarazpenak';
$string['emailalert_help'] = 'Hau gaituz gero, bilgune-kudeatzaileak e-postak bidaliko dizkizu segurtasun-abisuak eta bestelako albiste garrantzitsu batzuk emateko.';
$string['enrollable'] = 'Matrikulatzeko modukoa';
$string['errorbadimageheightwidth'] = 'Irudiak gehienez ere tamaina hau izan behar du: {$a->width} X {$a->height}';
$string['errorcourseinfo'] = 'Errorea gertatu da {$a} ikastarotik metadatuak eskuratzean. Mesedez, saia zaitez orri hau freskatzen ikastaroaren datuak berriz eskuratzeko. Bestela, erregistroaren prozesuarekin jarrai dezakezu hurrengo lehenetsitako metadatuekin.';
$string['errorcoursepublish'] = 'Errorea gertatu da ({$a}) ikastaroa argitaratu bitartean. Mesedez, saiatu berriz beranduago.';
$string['errorcoursewronglypublished'] = 'Moodle.net guneak errorea izan du ikastaroa argitaratzean. Mesedez, saiatu berriz beranduago.';
$string['errorcron'] = 'Errorea gertatu da "{$a->hubname}" -(e)k erregistroa eguneratu bitartean: ({$a->errormessage})';
$string['errorcronnoxmlrpc'] = 'XML-RPC gaituta egon behar da erregistroa eguneratu ahal izateko.';
$string['errorhublisting'] = 'Errorea gertatu da Moodle-tik ikastaro-bilguneen zerrenda berreskuratzean. Mesedez, saiatu berriz beranduago. ({$a})';
$string['errorlangnotrecognized'] = 'Eman duzun hizkuntza-kodea ez du Moodle-k ezagutzen. > Mesedez, jar zaitez harremanetan {$a} -(r)ekin.';
$string['errorotherhubsnotsupported'] = 'Orria hau ezin da erabili erregistratzeko aurrerantzean Moodle.net ez beste guneetan.';
$string['errorregistration'] = 'Errorea gertatu da erregistroa egin bitartean. Mesedez, saiatu berriz beranduago. ({$a})';
$string['errorregistrationupdate'] = 'Errorea gertatu da erregistroa eguneratzean ({$a})';
$string['errorunpublishcourses'] = 'Ezusteko errore bat dela eta, ikastaroak ezin izan dira Moodle.net-etik ezabatu. Saia zaitez beranduago (gomendatua) edo jarri harremanetan Moodle.net-eko kudeatzailearekin.';
$string['errorws'] = '{$a}';
$string['errorwstokenreset'] = '{$a}. Gune honetako erregistro-tokena berrabiarazi da. Zure gunea berriro erregistra dezakezu.';
$string['existingscreenshotnumber'] = '{$a} pantaila-argazki existitzen dira. Pantaila-argazki hauek orri honetan ikusi ahalko dituzu, behin Moodle.net-eko kudeatzaileak zure ikastaroa gaitzen duenean.';
$string['existingscreenshots'] = 'Dauden pantaila-argazkiak';
$string['forceunregister'] = 'Bai, garbitu erregistro-datuak';
$string['forceunregisterconfirmation'] = 'Zure guneak ezin du {$a}-raino heldu. Bilgune hau behin-behiean ez-eskuragarri egon daiteke. Erregistroa lokalki ezabatu nahi duzula ziur eduki ezean, mesedez utzi eta saia zaitez beranduago.';
$string['geolocation'] = 'Geokokapena';
$string['geolocation_help'] = 'Etorkizunean agian kokapenean oinarritutako bilaketak eskainiko ditugu. Zure ikastaroaren kokapena zehaztu nahi baduzu sartu hemen latitude/longitudea (adibidez: -31.947884,115.871285). Datu hau lortzeko modu bat Google Maps izan daiteke.';
$string['hub'] = 'Bilgunea';
$string['imageurl'] = 'Irudiaren URLa';
$string['imageurl_help'] = 'Irudi hau bilgunean erakutsiko da. Irudia bilgunean uneoro izan behar da eskura. Irudiak gehienez ere tamaina hau izan behar du: {$a->width} X {$a->height}';
$string['information'] = 'Informazioa';
$string['issuedbadgesnumber'] = 'Emandako domina-kopurua ({$a})';
$string['language'] = 'Hizkuntza';
$string['language_help'] = 'Ikastaro honen hizkuntza nagusia.';
$string['lasttimechecked'] = 'Egiaztatu zeneko azken aldia';
$string['licence'] = 'Lizentzia';
$string['licence_help'] = 'Aukeratu ikastaroa partekatzeko lizentzia.';
$string['logourl'] = 'Logoaren URLa';
$string['mobilenotificationsenabled'] = 'Mobile jakinarazpenak gaitu dira ({$a})';
$string['mobileservicesenabled'] = 'Mobile zerbitzuak gaitu dira ({$a})';
$string['modulenumberaverage'] = 'Ikastaroaren batezbesteko modulu-kopurua ({$a})';
$string['moodleorg'] = 'Moodle';
$string['mustselectsubject'] = 'Gaia aukeratu behar duzu';
$string['name'] = 'Izena';
$string['name_help'] = 'Izen hau ikastaro-zerrendan erakutsiko da.';
$string['neverchecked'] = 'Egiaztatu gabea';
$string['next'] = 'Hurrengoa';
$string['no'] = 'Ez';
$string['nocheckstatusfromunreghub'] = 'Gune hau ez dago bilgunean erregistratuta eta horregatik izan da egoera egiaztatu.';
$string['nohubselected'] = 'Ez da bilgunea aukeratu';
$string['none'] = 'Bat ere ez';
$string['nosearch'] = 'Ez argitaratu bilgunerik edo ikastarorik';
$string['notregisteredonhub'] = 'Guneko kudeatzaileak gunea Moodle.net webgunean erregistratu behar du zuk ikastaroa argitaratu ahal izateko.';
$string['notregisteredonmoodleorg'] = 'Zure kudeatzaileak gunea moodle.org-n erregistratu behar du.';
$string['operation'] = 'Ekintzak';
$string['orenterprivatehub'] = 'Bestela, idatzi bilgune pribatu baten URLa:';
$string['participantnumberaverage'] = 'Partaideen batez besteko kopurua: ({$a})';
$string['policyagreed'] = 'Pribatutasun oharra eta datu-prozesatzearen onespena';
$string['policyagreeddesc'] = 'Onartzen dut Moodle.net webguneko <a href="{$a}" target="_blank">Pribatutasun oharra eta datu-prozesatzearen onespena</a>';
$string['postaladdress'] = 'Helbidea';
$string['postaladdress_help'] = 'Gune honen posta-helbidea, edo guneak errepresentatzen duen erakundearena.';
$string['postsnumber'] = 'Mezu-kopurua: ({$a})';
$string['previousregistrationdeleted'] = 'Aurretiko erregistroa ezabatua izan da {$a} gunetik. Erregistro-prozesua berriz has dezakezu. Eskerrik asko.';
$string['prioritise'] = 'Lehenetsi';
$string['privacy'] = 'Pribatutasuna';
$string['privacy_help'] = 'Bilguneak erregistratutako guneen zerrenda erakutsi ahal du. Horrela izanez gero, aukeran duzu zerrendan agertu ala ez.';
$string['private'] = 'Pribatua';
$string['privatehuburl'] = 'Bilgune pribatuaren URLa';
$string['publicationinfo'] = 'Ikastaro-argitalpenaren informazioa';
$string['publichub'] = 'Bilgune publikoa';
$string['publish'] = 'Partekatu';
$string['publishcourse'] = 'Partekatu {$a}';
$string['publishcourseon'] = 'Partekatu hemen: {$a}';
$string['publishedon'] = 'Ikastaro-partekatzeak';
$string['publisheremail'] = 'Editorearen e-posta';
$string['publisheremail_help'] = 'Editorearen e-posta helbideak aukera emateko dio bilguneko kudeatzaileari argitara emandako ikastaroak izan dezakeen edozein aldaketaz editorea ohartarazteko.';
$string['publishername'] = 'Editorea';
$string['publishername_help'] = 'Editorea ikastaroa ofizialki argitaratu duen pertsona edo erakundea da. Ikastaroa beste pertsona baten ordez argiratzen ez bazaude, editorea zeu zara.';
$string['publishon'] = 'Partekatu hemen:';
$string['publishonspecifichub'] = 'Argitaratu beste bilgune batean';
$string['questionsnumber'] = 'Galdera-kopurua: ({$a})';
$string['readvertiseon'] = 'Eguneratu abisuak hemen: {$a}';
$string['registeredactiveuserdevices'] = 'Jakinarazpenak jasotzen ari diren erregistratutako gailu mugikorrak duen erabiltzaile aktiboen kopurua ({$a})';
$string['registeredcourses'] = 'Erregistratutako ikastaroak';
$string['registeredmoodleorg'] = 'Moodle ({$a})';
$string['registeredon'] = 'Non dago erregistratuta zure gunea';
$string['registeredsites'] = 'Erregistratutako guneak';
$string['registereduserdevices'] = 'Erregistratutako gailu mugikorrak duen erabiltzaile-kopurua ({$a})';
$string['registermoochtips'] = 'Erregistratu zure Moodle gunea segurtasun-abisuak jasotzeko eta Moodle.net-era sartzeko, gure plataforma ikastaroak partekatzeko';
$string['registersite'] = 'Erregistratu hemen: {$a}';
$string['registerwith'] = 'Erregistratu bilgune batean';
$string['registrationconfirmed'] = 'Gunearen erregistroa baieztatuta';
$string['registrationconfirmedon'] = 'Eskerrik asko zure gunea erregistratzeagatik. Erregistroaren informazioa eguneratuta mantenduko da \'Gunearen erregistroa\' programatutako zereginaren bitartez.';
$string['registrationinfo'] = 'Erregistroaren informazioa';
$string['registrationupdated'] = 'Erregistroa eguneratu da.';
$string['registrationupdatedfailed'] = 'Erregistroaren eguneraketak huts egin du.';
$string['removefromhub'] = 'Ezabatu Moodle.net-etik';
$string['renewregistration'] = 'Berriztu erregistroa';
$string['resourcesnumber'] = 'Baliabide-kopurua: ({$a})';
$string['restartregistration'] = 'Berrabiarazi erregistroa';
$string['roleassignmentsnumber'] = 'Rol esleipen-kopurua ({$a})';
$string['screenshots'] = 'Pantaila-argazkiak';
$string['screenshots_help'] = 'Ikastaroaren edozein pantaila-argazki bilaketaren emaitzetan erakutsiko da.';
$string['search'] = 'Bilatu';
$string['selecthub'] = 'Aukeratu bilgunea';
$string['selecthubforadvertise'] = 'Aukeratu iragartzeko bilgunea';
$string['selecthubforsharing'] = 'Aukeratu bilgunea igotzeko';
$string['selecthubinfo'] = 'Komunitate-bilgunea ikastaro-zerrenda bat duen zerbitzaria da. Zure Moodle gunea erregistratuta dagoen bilguneetan bakarrik izango duzu ikastaroak argitaratzeko modua. Jarraian azaltzen diren bilguneen artean ez badago zeuk nahi duzun bilgunea, jar zaitez harremanetan zure guneko kudeatzailearekin.';
$string['sendfollowinginfo'] = 'Informazio gehiago';
$string['sendfollowinginfo_help'] = 'Informazio hau estatistika orokorrak hornitzeko baino ez da erabiliko. Ez da gunearen inongo zerrendatan argitaratuko.';
$string['sendingcourse'] = 'Ikastaroa bidaltzen';
$string['sendingsize'] = 'Mesedez, itxaron; ikastaroa igotzen ari da ({$a->total}Mb)...';
$string['sent'] = '...amaituta';
$string['settings'] = 'Ezarpenak';
$string['settingsupdated'] = 'Ezarpenak eguneratu dira.';
$string['share'] = 'Partekatu ikastaro hau jendeak jaisteko';
$string['shared'] = 'Jendeak deskargatzeko partekatuta';
$string['shareon'] = 'Igo ikastaro hau hona: {$a}';
$string['shareonhub'] = 'Igo ikastaro hau bilgune batera';
$string['sharepublication_help'] = 'Ikastaro honen segurtasun-kopia bat Moodle.net webgunean eskuragarri egongo da jendeak bere guneetan berreskuratu eta erabili dezan.';
$string['siteadmin'] = 'Kudeatzailea';
$string['siteadmin_help'] = 'Guneko kudeatzailearen izen osoa.';
$string['sitecommnews'] = 'Moodle-ko berri eta ezaugarrien eguneratzeak';
$string['sitecommnews_help'] = 'Bolumen txikiko gure e-posta zerrendara harpidetu zaitezke Moodle komunitateko gertakizunen buletina jasotzeko.';
$string['sitecommnewsno'] = 'Ez, ez dut Moodle HQ-tik ezein e-postarik jaso nahi';
$string['sitecommnewsyes'] = 'Bai, mesedez, Moodle-ko berritasunen ohiko buletina jaso nahi dut.';
$string['sitecountry'] = 'Herrialdea';
$string['sitecountry_help'] = 'Zein herrialdetakoa den zure erakunde edo instituzioa.';
$string['sitecreated'] = 'Gunea sortuta';
$string['sitedesc'] = 'Deskribapena';
$string['sitedesc_help'] = 'Eman Moodle erabiltzen duzun moduaren inguruko informazio pixka bat.';
$string['siteemail'] = 'Kudeatzailearen e-posta helbidea';
$string['siteemail_help'] = 'e-posta helbide bat beharrezkoa da Moodle HQ-k behar izanez gero zurekin harremanetan jarri ahal izateko. Zuk behean baimentzen dituzun erabileretako ere erabil daiteke. Lanpostuaren helbide generikoa erabiltzea gomendatzen da (adibidez: kudeatzailea@adibidea.eus), eta ez helbide pertsonala.';
$string['sitegeolocation'] = 'Geolokalizazioa';
$string['sitegeolocation_help'] = 'Etorkizunean agian kokapenean oinarritutako bilaketak eskainiko ditugu bilguneetan. Zure gunearen kokapena zehaztu nahi baduzu, sartu hemen latitude/longitudea (adibidez: -31.947884,115.871285). Datu hau lortzeko modu bat Google Maps izan daiteke.';
$string['sitelang'] = 'Hizkuntza';
$string['sitelang_help'] = 'Zein da zure Moodle gunearen hizkuntza nagusia?';
$string['sitename'] = 'Izena';
$string['sitename_help'] = 'Gunearen izena guneen zerrendan agertuko da, bilguneak onartzen badu.';
$string['sitephone'] = 'Telefonoa';
$string['sitephone_help'] = 'Zure telefono-zenbakiak bilguneko kudeatzaileak baino ez du ikusiko.';
$string['siteprivacy'] = 'Gunearen zerrendatzea';
$string['siteprivacy_help'] = 'Zure gunea erregistratutako guneen zerrendan publikoki erakustea aukera dezakezu, zure gunerako estekarekin edo estekarik gabe.';
$string['siteprivacylinked'] = 'Erakutsi nire gunearen izena eta esteka';
$string['siteprivacynotpublished'] = 'Ez argitaratu gune hau';
$string['siteprivacypublished'] = 'Gunearen izena baino ez erakutsi';
$string['siteregconfcomment'] = 'Zure guneak azken konfirmazio bat behar du {$a}-(e)n (SPAMa ekiditzeko {$a}-(e)n)';
$string['siteregistrationcontact'] = 'Erakutsi kontakturako formularioa';
$string['siteregistrationcontact_help'] = 'Baimena emanez gero, Moodle komunitateko jendeak (kontu bat izan behar dutenak) zurekin harremanetan jarri ahal dira gure Moodle komunitateko gunearen formulario baten bidez. Hala ere, ezingo dute zure e-posta helbidea ikusi.';
$string['siteregistrationemail'] = 'Segurtasun eta kontu tekniko garrantzitsuen inguruko jakinarazpenak.';
$string['siteregistrationemail_help'] = 'Bolumen txikiko gure e-posta zerrendara harpidetu zaitezke berri garrantzitsuak jasotzeko (segurtasun kontuak edo bertsio berriak).';
$string['siteregistrationupdated'] = 'Gunearen erregistroa eguneratu da';
$string['siterelease'] = 'Moodle-ren bertsioa';
$string['siterelease_help'] = 'Gune honen Moodle-ren ezaugarriak';
$string['sitereleasenum'] = 'Moodle-ren bertsioa ({$a})';
$string['siteupdatedcron'] = 'Gunearen erregistroa "{$a}"-(e)n eguneratu da';
$string['siteupdatesend'] = 'Bilguneetako erregistroaren eguneraketa amaituta.';
$string['siteupdatesstart'] = 'Bilguneetako erregistroaren eguneraketa hasi da...';
$string['siteurl'] = 'Gunearen URLa';
$string['siteurl_help'] = 'URL hau gunearen helbidea da. Pribatutasun-ezerpenek jendeak guneko helbidea ikustea baimenduz gero, URL hau erabiliko da horretarako.';
$string['siteversion'] = 'Moodle bertsioa';
$string['siteversion_help'] = 'Gune honen Moodle-ren bertsioa.';
$string['skipregistration'] = 'Alde batera utzi';
$string['specifichubregistrationdetail'] = 'Zeure gunea beste bilgune batzuetan ere erregistra dezakezu';
$string['statistics'] = 'Pribatutasun-estatistikak';
$string['status'] = 'Zerrendatzearen egoera';
$string['statuspublished'] = 'Zerrendatuta';
$string['statusunpublished'] = 'Zerrendatu gabe';
$string['subject'] = 'Gaia';
$string['subject_help'] = 'Aukeratu ikastaroaren gai nagusia.';
$string['tags'] = 'Etiketak';
$string['tags_help'] = 'Etiketek zure ikastaroa hobeto sailkatzen laguntzen dute eta horren bilaketa errazten. Mesedez, erabili hitz errazak eta esanguratsuak komaz banatuta. Adibidez, matematika, algebra, geometria';
$string['trustme'] = 'Fidatu';
$string['type'] = 'Partekatuta';
$string['unknownstatus'] = 'Ezezaguna';
$string['unlistedurl'] = 'Zerrendatu gabeko bilguneen URLa';
$string['unprioritise'] = 'Ez lehenetsi';
$string['unpublish'] = 'Utzi partekatzeari';
$string['unpublishalladvertisedcourses'] = 'Ezabatu Moodle.net-en jendea matrikulatzeko partekatutako ikastaro guztiak';
$string['unpublishalluploadedcourses'] = 'Ezabatu Moodle.net-en jendeak deskargatzeko partekatutako ikastaro guztiak';
$string['unpublishconfirmation'] = 'Ziur al zaude "{$a->courseshortname}" ikastaroa "{$a->hubname}"-tik ezabatu nahi duzula?';
$string['unpublishcourse'] = 'Utzi partekatzeari: {$a}';
$string['unregister'] = 'Ezabatu erregistroa';
$string['unregisterconfirmation'] = 'Gune honen erregistroa {$a} ikastaro-bilgunetik ezabatuko duzu honela. Behin deskonektatuta ez duzu bertan utzitako inongo ikastarorik kudeatzeko aukerarik izango. Ziur al zaude erregistroa ezabatu nahi duzula?';
$string['unregisterexplained'] = '{$a} URLa duen gunea Moodle.net-en erregistratuta badago, bere erregistroa etengo da.';
$string['unregisterfrom'] = 'Ezabatu {$a}-ren erregistroa';
$string['unregistrationerror'] = 'Errorea gertatu da gunea Moodle.net-eko erregistroa ezabatzen saiatu denean: {$a}';
$string['untrustme'] = 'Ez da konfiantzazkoa';
$string['update'] = 'Eguneratu';
$string['updatesite'] = 'Eguneratu erregistroa hemen: {$a}';
$string['updatestatus'] = 'Egiaztatu orain.';
$string['uploaded'] = 'Eguneratuta';
$string['url'] = 'bilgunearen URLa';
$string['urlalreadyregistered'] = 'Badirudi zure gunea Moodle.net-en dagoeneko erregistratuta dagoela, eta horrek zerbait gaizki joan dela esan nahi du. Mesedez jarri harremanetan Moodle.net-eko kudeatzailearekin zure erregistroa berrabiarazi dezan zu berriz saiatu ahal izateko.';
$string['usedifferentemail'] = 'Erabili beste e-posta bat';
$string['usersnumber'] = 'Erabiltzaile-kopurua: ({$a})';
$string['warning'] = 'KONTUZ';
$string['wrongtoken'] = 'Erregistroak huts egin du arrazoi ezezagun batzuk medio (sarea?). Mesedez, berriz saiatu zaitez.';
$string['wrongurlformat'] = 'Okerreko URL formatua';
$string['xmlrpcdisabledcommunity'] = 'XML-RPC luzapena ez dago gaituta zerbitzarian. Ezin duzu ikastarorik bilatu ezta jaitsi ere.';
$string['xmlrpcdisabledpublish'] = 'XML-RPC luzapena ez dago gaituta zerbitzarian, eta beraz ezin duzu ikastarorik argitaratu ezta argitaratutakoak kudeatu ere.';
$string['xmlrpcdisabledregistration'] = 'XML-RPC luzapena ez dago gaituta zerbitzarian. Gaitu arte, ezin izango duzu erregistroa ezabatu ezta eguneratu ere.';
