<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'block_homework', language 'el', version '4.1'.
 *
 * @package     block_homework
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['achievementactivity'] = 'Δραστηριότητα';
$string['achievementcomments'] = 'Σχόλια';
$string['achievementpoints'] = 'Πόντοι';
$string['achievementreporter'] = 'Αναφορά από';
$string['achievementtype'] = 'Τύπος επιτεύγματος';
$string['actions'] = 'Ενέργειες';
$string['activity'] = 'Δραστηριότητα';
$string['activity_help'] = 'Μπορείτε να δημιουργήσετε μια νέα δραστηριότητα ή να κλωνοποιήσετε/αντιγράψετε μια υπάρχουσα';
$string['addfiles'] = 'Προσθήκη αρχείου/-ων';
$string['addfiles_help'] = 'Ανέβασμα τυχόν αρχείου/-ων που σχετίζονται με την ανάθεση εργασίας για το σπίτι';
$string['addingachievementfor'] = 'Προσθήκη επιτεύγματος για';
$string['addingbehaviourfor'] = 'Προσθήκη συμπεριφοράς για';
$string['additional'] = 'Επιπρόσθετο';
$string['addsubmission'] = 'Προσθήκη υποβολής';
$string['alldone'] = 'Έγιναν όλα';
$string['allorfiltered'] = 'Παρακαλούμε, επιλέξτε Όλα ή Φιλτραρισμένα, πριν κάνετε κλικ στην Εξαγωγή';
$string['allowshowdescription'] = 'Να επιτρέπεται στους χρήστες να ενεργοποιούν την Εμφάνιση περιγραφής';
$string['allowshowdescription_help'] = 'Εάν οι χρήστες μπορούν να ενεργοποιούν την ρύθμιση Εμφάνιση περιγραφής';
$string['allxselected'] = 'Και τα {0} επιλεγμένα';
$string['anystaffmember'] = '(Οποιοδήποτε μέλος του προσωπικού)';
$string['assignment'] = 'Ανάθεση';
$string['assignmentmarked'] = 'Η ανάθεση εργασίας για το σπίτι βαθμολογήθηκε με επιτυχία.';
$string['assignmentmarkedasdone'] = 'Η ανάθεση εργασίας για το σπίτι βαθμολογήθηκε ως ολοκληρωμένη.';
$string['assignmentnotifications'] = 'Ειδοποιήσεις ανάθεσης';
$string['assignmentsaved'] = 'Η ανάθεση εργασίας για το σπίτι αποθηκεύτηκε με επιτυχία.';
$string['assignmentsgraded'] = 'Οι αναθέσεις βαθμολογήθηκαν';
$string['available'] = 'Διαθέσιμο';
$string['availablefrom'] = 'Διαθέσιμη από';
$string['basics'] = 'Βασικά';
$string['behaviouractiontaken'] = 'Λήφθηκε ενέργεια';
$string['behaviouractivity'] = 'Δραστηριότητα';
$string['behaviourcomments'] = 'Σχόλια';
$string['behaviourpoints'] = 'Πόντοι';
$string['behaviourreporter'] = 'Αναφορά από';
$string['behaviourstatus'] = 'Κατάσταση';
$string['behaviourtype'] = 'Τύπος συμπεριφοράς';
$string['cancel'] = 'Άκυρο';
$string['changecourse'] = 'Αλλαγή';
$string['child'] = 'Απόγονος';
$string['clone_'] = 'Κλώνος';
$string['cloneexistingactivity'] = 'Κλωνοποίηση υπάρχουσας δραστηριότητας...';
$string['community'] = 'Κοινότητα';
$string['completed'] = 'Ολοκληρωμένο';
$string['copyof_'] = 'Αντίγραφο από';
$string['correcthighlightederrors'] = 'Διόρθωση του/των φωτο-επισημασμένων σφαλμάτων πριν την αποθήκευση';
$string['course'] = 'Μάθημα';
$string['createdby'] = 'Δημιουργήθηκε από';
$string['createnewassignmentactivity'] = 'Νέα ανάθεση εργασίας για το σπίτι';
$string['date'] = 'Ημερομηνία';
$string['dateavailable'] = 'Ημερομηνία διαθέσιμο';
$string['defaultnotifyparents'] = 'Προεπιλογή ρύθμισης για ειδοποίηση γονέων';
$string['defaultnotifyparents_help'] = 'Εάν η προεπιλογή ρύθμισης για ειδοποίηση γονέων θα είναι ενεργοποιημένη ή απενεργοποιημένη από προεπιλογή';
$string['defaultshowdescription'] = 'Προεπιλεγμένη ρύθμιση για την εμφάνιση περιγραφής';
$string['defaultshowdescription_help'] = 'Εάν η ρύθμιση εμφάνισης περιγραφής είναι ενεργοποιημένη ή απενεργοποιημένη από προεπιλογή';
$string['deletehomeworkitem'] = 'Διαγραφή εργασίας για το σπίτι';
$string['description'] = 'Περιγραφή';
$string['description_help'] = 'Μια λεπτομερής περιγραφή της ανάθεσης εργασίας για το σπίτι';
$string['details'] = 'Λεπτομέρειες';
$string['due'] = 'Οφείλεται';
$string['due_help'] = 'Η ημερομηνία κατά την οποία η εργασία για το σπίτι θα πρέπει να υποβληθεί';
$string['duedate'] = 'Οφειλόμενη ημερομηνία';
$string['duedateinvalid'] = 'Η οφειλόμενη ημερομηνία πρέπει να είναι μετά την ημερομηνία διαθεσιμότητας';
$string['dueon'] = 'Οφείλεται στις';
$string['dueondate'] = '{$a}';
$string['dueonlc'] = 'οφείλεται στις';
$string['duration'] = 'Διάρκεια';
$string['duration_10'] = '10 λεπτά';
$string['duration_120'] = '2 ώρες';
$string['duration_180'] = '3 ώρες';
$string['duration_20'] = '20 λεπτά';
$string['duration_240'] = '4 ώρες';
$string['duration_30'] = '30 λεπτά';
$string['duration_360'] = '6 ώρες+';
$string['duration_60'] = '1 ώρα';
$string['duration_help'] = 'Η αναμενόμενη διάρκεια';
$string['duration_notspecified'] = 'Δεν καθορίστηκε';
$string['durationnotspecified'] = '(δεν καθορίστηκε διάρκεια)';
$string['edithomework'] = 'Επεξεργασία εργασίας για το σπίτι';
$string['edithomeworkitem'] = 'Επεξεργασία εργασίας για το σπίτι';
$string['email'] = 'Διεύθυνση ηλε.ταχυδρομείου';
$string['export'] = 'Εξαγωγή';
$string['exportall'] = 'Εξαγωγή Όλων';
$string['exportfiltered'] = 'Η εξαγωγή φιλτραρίστηκε';
$string['failedtoaddachievementfor'] = 'Αποτυχία προσθήκης επιτεύγματος για';
$string['failedtoaddbehaviourfor'] = 'Αποτυχία προσθήκης συμπεριφοράς για';
$string['failedtofetchdata'] = 'Αποτυχία κλήσης/λήψης δεδομένων';
$string['failedtosetmarkfor'] = 'Αποτυχία ορισμού επισήμανσης για';
$string['feedback'] = 'Ανατροφοδότηση';
$string['files'] = 'Αρχεία';
$string['formgroup'] = 'Δημιουργία ομάδας';
$string['from'] = 'Από';
$string['grade'] = 'Βαθμός';
$string['graded'] = 'Βαθμολογήθηκε';
$string['gradedsubmissions'] = 'Βαθμολογημένες υποβολές';
$string['gradenotapplicable'] = 'Δ/Υ - μη συμμετέχοντας';
$string['gradingassignmentfor'] = 'Βαθμολόγηση ανάθεσης για';
$string['gradingscalelink'] = '<a href="{$a}" target="_blank">Μπορείτε να δημιουργήσετε κλίμακες βαθμολόγησης κάνοντας κλικ εδώ</a>';
$string['gradingtype'] = 'Κλίμακα βαθμολόγησης';
$string['group'] = 'Ομάδα';
$string['groupgrades'] = 'Βαθμοί ομάδας';
$string['groupmembergrades'] = 'Βαθμοί μελών ομάδας';
$string['homework:addinstance'] = 'Προσθήκη ενός μπλοκ Εργασίας για το σπίτι';
$string['homework:myaddinstance'] = 'Προσθήκη ενός μπλοκ Εργασίας για το σπίτι στην αρχική μου σελίδα';
$string['homework:viewreports'] = 'Εμφάνιση αναφορών Εργασίας για το σπίτι';
$string['invalidcmid'] = 'Μη έγκυρο αναγνωριστικο αρθρώματος μαθήματος';
$string['invalidcourse'] = 'Μη έγκυρο αναγνωριστικο μαθήματος';
$string['invaliddatesupplied'] = 'Δόθηκε μη έγκυρη ημερομηνία';
$string['invalidgroupsupplied'] = 'Δόθηκε μη έγκυρη ομάδα';
$string['invalidstudentsupplied'] = 'Δόθηκε μη έγκυρος μαθητής';
$string['inxdays'] = '{$a} ημέρες';
$string['issued'] = 'Εκδόθηκε';
$string['learnernotificationerror'] = 'Σφάλμα κατά την ειδοποίηση εκπαιδευόμενων: {$a}';
$string['listview'] = 'Εμφάνιση λίστας';
$string['loadingdata'] = 'Φόρτωση δεδομένων...';
$string['lognotifications'] = 'Καταγραφές ειδοποιήσεων';
$string['lognotifications_help'] = 'Καταγραφές μηνυμάτων (ηλε.ταχυδρομείου) ειδοποίησης και συμπερίληψή τους στην οθόνη αναφορών';
$string['mark'] = 'Βαθμός';
$string['markanotherassignment'] = 'Βαθμολόγηση κι άλλης ανάθεσης';
$string['markanotherassignment_title'] = 'Δραστηριότητα βαθμολόγησης κι άλλης ανάθεσης';
$string['markdone'] = 'Επισήμανση ως ολοκληρωμένου';
$string['markeddone'] = 'Επισημάνθηκε ως ολοκληρωμένο';
$string['markhomework'] = 'Βαθμολόγηση εργασίας (για το σπίτι)';
$string['marking'] = 'Βαθμολόγηση';
$string['maxageemployee'] = 'Μέγιστο ημερών για εμφάνιση καθυστερημένων αναθέσεων για (υπαλλήλους)';
$string['maxageemployee_help'] = 'Ο αριθμός των ημερών μέσα στον οποίο οι καθυστερημένες εργασίες πρέπει να αναφέρονται στο μπλοκ (προβολή δασκάλου/διαχειριστή)';
$string['messageprovider:new_assignment'] = 'Ειδοποίηση για νέες αναθέσεις εργασιών στο σπίτι';
$string['messagesendfailed'] = 'Αποτυχία αποστολής μηνύματος Moodle';
$string['name'] = 'Όνομα';
$string['newassignmentnotificationmessage'] = 'Μήνυμα ειδοποίησης νέας ανάθεσης';
$string['newhomework'] = 'Νέα εργασία για το σπίτι';
$string['noassignmentsfound'] = 'Δεν βρέθηκε καμία ανάθεση';
$string['nogroupmembersfound'] = 'Δεν βρέθηκαν καθόλου μέλη ομάδας';
$string['nogrouprestriction'] = 'Καθόλου περιορισμοί κατά ομάδα/-ες';
$string['nogroups'] = 'Δεν υπάρχει καμία ομάδα στα μαθήματά σας';
$string['nohomework'] = 'Δεν βρέθηκε καμία εργασία για το σπίτι';
$string['nonotificationsfound'] = 'Δεν βρέθηκε καμία ειδοποίηση';
$string['noonlinesubmissionrequired'] = 'Δεν απαιτείται καμία υποβολή εντός σύνδεσης';
$string['noonlinesubs'] = 'Στην τάξη';
$string['nopermission'] = 'Λυπούμαστε, αλλά δεν έχετε δικαίωμα να χρησιμοποιήσετε αυτή τη σελίδα';
$string['nosubjectspecified'] = 'Δεν καθορίστηκε κανένα θέμα ({$a})';
$string['notapplicable'] = 'Δ/Υ';
$string['notesforlearners'] = 'Σώμα μηνύματος';
$string['notesforlearnerssubject'] = 'Γραμμή θέματος';
$string['notesforparents'] = 'Σώμα μηνύματος';
$string['notesforparentssubject'] = 'Γραμμή θέματος';
$string['notgraded'] = 'Μη βαθμολογημένη';
$string['nothingdone'] = 'Δεν έγινε τίποτα';
$string['nothingdonefull'] = 'Κανένας βαθμός δεν προστέθηκε ούτε τροποποιήθηκε· τίποτα προς αποθήκευση!';
$string['notificationslog'] = 'Καταγραφές ειδοποιήσεων';
$string['notifylearners'] = 'Να ειδοποιηθούν οι εκπαιδευόμενοι';
$string['notifylearnersmessagesubject'] = 'Έχετε μια νέα ανάθεση';
$string['notifyother'] = 'Ειδοποίηση τρίτου μέρους';
$string['notifyotheremail'] = 'Διεύθυνση ηλε.ταχυδρομείου τρίτου';
$string['notifyotheremail_help'] = 'Εισαγάγετε τη διεύθυνση ηλε.ταχυδρομείου του τρίτου μέρους εδώ';
$string['notifyparents'] = 'Ειδοποίηση γονέων';
$string['notimetable'] = 'Κανένα δεδομένο χρονοδιαγράμματος διαθέσιμο';
$string['notselected'] = '[Μη επιλεγμένο]';
$string['notspecified'] = 'Μη καθορισμένο';
$string['notsubmitted'] = 'Δεν έχει υποβληθεί';
$string['nottracked'] = 'Δεν παρακολουθείται';
$string['nouserrestriction'] = 'Κανένας περιορισμός κατά χρήστη/-ες';
$string['off'] = 'Όχι';
$string['ok'] = 'ΟΚ';
$string['okbutton'] = 'ΟΚ';
$string['on'] = 'Ναι';
$string['onallcourses'] = '(όλα τα μαθήματα)';
$string['oncourse'] = '({$a} μάθημα)';
$string['onehour'] = '1 ώρα';
$string['onlinefilesubs'] = 'Ανέβασμα αρχείου';
$string['onlinetextorfilesubs'] = 'Κείμενο εντός σύνδεσης ή ανέβασμα αρχείου';
$string['onlinetextsubs'] = 'Κείμενο εντός σύνδεσης';
$string['oops'] = 'Ώχ...';
$string['pageerror'] = 'Λυπούμαστε, συνέβη κάποιο προβληματάκι: {$a}';
$string['parentalnotificationerror'] = 'Σφάλμα κατά την ειδοποίηση γονέων: {$a}';
$string['parentview'] = ', Εμφάνιση γονέα';
$string['participants'] = 'Συμμετέχοντες';
$string['pleaseselect'] = '[Παρακαλούμε επιλέξτε]';
$string['pleaseselectastudent'] = 'Παρακαλούμε επιλέξτε ένα μαθητή';
$string['pluginname'] = 'Εργασία στο σπίτι';
$string['plusfiles'] = '(υποβολή έξτρα αρχείου)';
$string['pointsoutof100'] = 'Πόντοι (στους 100)';
$string['poweredby'] = 'Ανάπτυξη από Overnet Data';
$string['poweredbyurl'] = 'http://www.overnetdata.com/products/edulink-homework-moodle-block/edulink-homework';
$string['read'] = 'Ανάγνωση';
$string['requiredfield'] = 'Απαιτούμενο πεδίο';
$string['requirerestriction'] = 'Απαιτείται περιορισμός';
$string['requirerestriction_help'] = 'Επιτρέπεται δημιουργία ανάθεσης μόνο εάν είναι περιορισμένη σε συγκεκριμένη ομάδα/-ες ή χρήστη/-ες';
$string['restrictions'] = 'Περιορισμοί';
$string['restricttogroups'] = 'Περιορισμός σε ομάδες';
$string['restricttousers'] = 'Περιορισμός σε χρήστες';
$string['returntocourse'] = 'Επιστροφή στο μάθημα';
$string['returntocourse_title'] = 'Επιστροφή στο μάθημα στο οποίο ανήκει αυτή η εργασία για το σπίτι';
$string['save'] = 'Αποθήκευση';
$string['saving'] = 'Αποθήκευση...';
$string['savingachievement'] = 'Αποθήκευση επιτεύγματος...';
$string['savingbehaviour'] = 'Αποθήκευση συμπεριφοράς...';
$string['savinggrades'] = 'Αποθήκευση βαθμών...';
$string['section'] = 'Ενότητα';
$string['section_help'] = 'Η ενότητα ή το θέμα μέσα στο μάθημα, όπου θα προστεθεί η δραστηριότητα Ανάθεσης εργασίας στο σπίτι.';
$string['selectcourse'] = 'Επιλογή μαθήματος';
$string['sendnotifications'] = 'Αποστολή ειδοποιήσεων εργασίας για το σπίτι';
$string['sent'] = 'Απεσταλμένα';
$string['setanotherassignment'] = 'Ορισμός μιας άλλης ανάθεσης εργασίας για το σπίτι';
$string['setanotherassignment_title'] = 'Προσθήκη μιας άλλης δραστηριότητας ανάθεσης';
$string['setby'] = 'Ορίστηκε από';
$string['sethomework'] = 'Ορισμός Εργασίας για το σπίτι';
$string['showdescription'] = 'Εμφάνιση περιγραφής στο μάθημα';
$string['showdescription_help'] = 'Αν θα εμφανιστεί η περιγραφή στην σελίδα του μαθήματος';
$string['staffmember'] = 'Μέλος του προσωπικού';
$string['staffstatistics'] = 'Στατιστικά προσωπικού';
$string['staffusage'] = 'Χρήση προσωπικού';
$string['status'] = 'Κατάσταση';
$string['student'] = 'Μαθητής';
$string['studentgrades'] = 'Βαθμοί μαθητή';
$string['studentview'] = ', Εμφάνιση για μαθητή';
$string['subject'] = 'Θέμα';
$string['subject_help'] = 'Αυτό χρησιμοποιείται στην ενότητα αναφοράς αυτού του μπλοκ';
$string['subjectsandstaff'] = 'Τομείς μαθημάτων και προσωπικό';
$string['submission'] = 'Υποβολή';
$string['submissions'] = 'Υποβολές';
$string['submissions_help'] = 'Πώς περιμένετε αυτή την εργασία για το σπίτι να υποβληθεί; Στην τάξη ή εντός σύνδεσης ως κείμενο ή ως ανεβασμένο αρχείο;';
$string['submissionsdefault'] = 'Προεπιλογή για υποβολές';
$string['submissionsdefault_help'] = 'Προεπιλογή για πεδίο υποβολής όταν δημιουργείται νέα ανάθεση';
$string['submissionsgraded'] = 'Οι υποβολές βαθμολογήθηκαν';
$string['submissionsvsparticipants'] = 'Υποβολές';
$string['teacherview'] = ', Εμφάνιση για διδάσκοντα';
$string['thereishomeworkdue'] = 'Υπάρχει οφειλόμενη εργασία για το σπίτι για αυτό το μάθημα';
$string['thereishomeworkset'] = 'Έχει οριστεί εργασία για το σπίτι για αυτό το μάθημα';
$string['thishomeworkisdone'] = 'Αυτή η εργασία για το σπίτι έχει ολοκληρωθεί';
$string['thishomeworkisdue'] = 'Αυτή η εργασία είναι οφειλόμενη';
$string['thishomeworkisset'] = 'Αυτή η εργασία έχει οριστεί';
$string['timetableview'] = 'Εμφάνιση χρονοδιαγράμματος';
$string['to'] = 'Προς';
$string['today'] = 'σήμερα';
$string['tomorrow'] = 'αύριο';
$string['tryagain'] = 'Προσπαθήστε ξανά';
$string['tryagain_title'] = 'Δοκιμάστε να προσθέσετε μια άλλη ανάθεση εργασίας για το σπίτι';
$string['ungradedsubmissions'] = 'Μη βαθμολογημένες υποβολές';
$string['unsupportedblindmarking'] = 'Τυφλή βαθμολόγηση';
$string['unsupportedmarkingallocation'] = 'Εκχώρηση βαθμολόγησης';
$string['unsupportedmarkingworkflow'] = 'Ροή εργασίας βαθμολόγησης';
$string['unsupportedteamsubmission'] = 'Ανάθεση ομαδικών εργασιών';
$string['userview'] = ', Εμφάνιση για χρήστη';
$string['valuerange'] = 'Η τιμή πρέπει να είναι στο διάστημα';
$string['versionx'] = 'Έκδοση {$a}';
$string['viewhomework'] = 'Εμφάνιση όλων των εργασιών για το σπίτι';
$string['viewhomeworkitem'] = 'Εμφάνιση ανάθεσης εργασίας για το σπίτι';
$string['viewhomeworkreports'] = 'Αναφορές εργασιών για το σπίτι';
$string['viewreports'] = 'Εμφάνιση αναφορών';
$string['xdaysago'] = '{$a} ημέρες πριν';
$string['xhours'] = '{$a} ώρες';
$string['xminutes'] = '{$a} λεπτά';
$string['year'] = 'Έτος';
$string['yesterday'] = 'χτες';
