<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'calendar', language 'el', version '4.5'.
 *
 * @package     calendar
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['activityevent'] = 'Γεγονός δραστηριότητας';
$string['addevent'] = 'Προσθήκη γεγονότων';
$string['advancedoptions'] = 'Για προχωρημένους';
$string['allday'] = 'Ολοήμερο';
$string['annually'] = 'Ετησίως';
$string['calendar'] = 'Ημερολόγιο';
$string['calendarexporturl'] = 'Διεύθυνση URL ημερολογίου';
$string['calendarheading'] = 'Ημερολόγιο {$a}';
$string['calendarpreferences'] = 'Προτιμήσεις ημερολογίου';
$string['calendartypes'] = 'Τύποι ημερολογίου';
$string['calendarurlcopiedtoclipboard'] = 'Η διεύθυνση URL ημερολογίου αντιγράφηκε στο πρόχειρο';
$string['category'] = 'Κατηγορία';
$string['categoryevent'] = 'Γεγονότα κατηγορίας';
$string['categoryevents'] = 'Γεγονότα κατηγορίας';
$string['clickhide'] = 'πατήστε για απόκρυψη';
$string['clickshow'] = 'πατήστε για εμφάνιση';
$string['colactions'] = 'Ενέργειες';
$string['colcalendar'] = 'Ημερολόγιο';
$string['collastupdated'] = 'Τελευταία ενημέρωση';
$string['colpoll'] = 'Διάστημα ανανέωσης';
$string['commontasks'] = 'Διεργασίες';
$string['confirmeventdelete'] = 'Θέλετε σίγουρα να διαγράψετε αυτό το γεγονός «{$a}»;';
$string['confirmeventseriesdelete'] = 'Το γεγονός «{$a->name}» είναι μέρος μιας σειράς γεγονότων. Θέλετε να διαγράψετε μόνο αυτό το γεγονός ή και τα {$a->count} γεγονότα της σειράς;';
$string['confirmsubscriptiondelete'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τη εγγραφή στο ημερολόγιο "{$a}";';
$string['copycalendarurl'] = 'Αντιγραφή διεύθυνσης URL ημερολογίου';
$string['copyurl'] = 'Αντιγραφή διεύθυνσης URL';
$string['course'] = 'Μάθημα';
$string['coursecalendar'] = 'Ημερολόγιο {$a}';
$string['courseevent'] = 'Γεγονός μαθήματος';
$string['courseevents'] = 'Γεγονότα μαθήματος';
$string['courses'] = 'Μαθήματα';
$string['customexport'] = 'Προσαρμοσμένο εύρος ({$a->timestart} - {$a->timeend})';
$string['daily'] = 'Καθημερινά';
$string['day'] = 'Ημέρα';
$string['dayeventsmany'] = '{$a->num} γεγονότα, {$a->day}';
$string['dayeventsnone'] = 'Κανένα γεγονός, {$a}';
$string['dayeventsone'] = '1 γεγονός, {$a}';
$string['daynext'] = 'Επόμενη ημέρα';
$string['dayprev'] = 'Προηγούμενη ημέρα';
$string['dayviewfor'] = 'Ημερήσια προβολή για:';
$string['dayviewtitle'] = 'Ημερήσια προβολή: {$a}';
$string['daywithnoevents'] = 'Δεν υπάρχουν γεγονότα για αυτή την ημέρα.';
$string['default'] = 'Προεπιλογή';
$string['deleteallevents'] = 'Διαγραφή όλων των γεγονότων';
$string['deleteevent'] = 'Διαγραφή γεγονότος';
$string['deleteevents'] = 'Διαγραφή γεγονότων';
$string['deleteoneevent'] = 'Διαγραφή αυτού του γεγονότος';
$string['detailedmonthviewfor'] = 'Λεπτομερής μηνιαία προβολή για:';
$string['detailedmonthviewtitle'] = 'Λεπτομερής μηνιαία προβολή: {$a}';
$string['durationminutes'] = 'Διάρκεια σε λεπτά';
$string['durationnone'] = 'Χωρίς διάρκεια';
$string['durationuntil'] = 'Μέχρι';
$string['editevent'] = 'Επεξεργασία γεγονότος';
$string['erroraddingevent'] = 'Αποτυχία προσθήκης του γεγονότος';
$string['errorbadsubscription'] = 'Αδυναμία εύρεσης δήλωσης εγγραφής στο ημερολόγιο';
$string['errorbeforecoursestart'] = 'Δεν είναι δυνατός ο ορισμός του γεγονότος προγενέστερα της ημερομηνίας έναρξης του μαθήματος';
$string['errorcannotimport'] = 'Δεν είναι δυνατός ο ορισμός μιας δήλωσης εγγραφής στο ημερολόγιο αυτή τη στιγμή.';
$string['errorhasuntilandcount'] = 'Σε έναν κανόνα επανάληψης, μπορεί να εμφανιστεί είτε το UNTIL είτε το COUNT, αλλά ΔΕΝ ΠΡΕΠΕΙ να εμφανιστούν ΜΑΖΙ στον ίδιο κανόνα επανάληψης.';
$string['errorinvalidbydayprefix'] = 'Οι ακέραιες τιμές που προηγούνται των κανόνων BYDAY (ανά ημέρα) μπορούν να εμφανιστούν μόνο για έναν επαναλαμβανόμενο κανόνα MONTHLY (μηνιαίως) ή YEARLY (ετησίως).';
$string['errorinvalidbydaysuffix'] = 'Έγκυρες τιμές για την ημέρα της εβδομάδας ως μέρος του κανόνα BYDAY είναι οι εξής: MO, TU, WE, TH, FR, SA και SU.';
$string['errorinvalidbyhour'] = 'Έγκυρες τιμές για τον κανόνα BYHOUR είναι από 1 έως 23.';
$string['errorinvalidbyminute'] = 'Έγκυρες τιμές για τον κανόνα BYMINUTE είναι από 1 έως 59.';
$string['errorinvalidbymonth'] = 'Έγκυρες τιμές για τον κανόνα BYMONTH είναι από 1 έως 12.';
$string['errorinvalidbymonthday'] = 'Έγκυρες τιμές για τον κανόνα BYMONTHDAY είναι από 1 έως 31 και από -31 έως -1.';
$string['errorinvalidbysecond'] = 'Έγκυρες τιμές για τον κανόνα BYSECOND είναι από 1 έως 59.';
$string['errorinvalidbysetpos'] = 'Έγκυρες τιμές για τον κανόνα BYSETPOS είναι από 1 έως 366 και από -366 έως -1.';
$string['errorinvalidbyweekno'] = 'Έγκυρες τιμές για τον κανόνα BYWEEKNO είναι από 1 έως 53 και από -53 έως -1.';
$string['errorinvalidbyyearday'] = 'Έγκυρες τιμές για τον κανόνα BYYEARDAY (ανά ημέρα του έτους) είναι από 1 έως 366 και από -366 έως -1.';
$string['errorinvaliddate'] = 'Μη έγκυρη ημερομηνία';
$string['errorinvalidicalurl'] = 'Η συγκεκριμένη διεύθυνση URL iCal είναι άκυρη.';
$string['errorinvalidinterval'] = 'Η τιμή για τον κανόνα INTERVAL πρέπει να είναι ένας θετικός ακέραιος.';
$string['errorinvalidminutes'] = 'Προσδιορίστε την διάρκεια σε λεπτά δίνοντας έναν αριθμό από το 1 ως το 999.';
$string['errorinvalidrepeats'] = 'Προσδιορίστε το πλήθος των γεγονότων δίνοντας έναν αριθμό από το 1 ως το 99.';
$string['errormustbeusedwithotherbyrule'] = 'Ο κανόνας BYSETPOS πρέπει να χρησιμοποιείται μόνο σε συνδυασμό με άλλο τμήμα κανόνα BYxxx.';
$string['errornodescription'] = 'Η περιγραφή απαιτείται';
$string['errornoeventname'] = 'Το όνομα απαιτείται';
$string['errornonyearlyfreqwithbyweekno'] = 'Ο κανόνας BYWEEKNO (ανά αριθμό εβδομάδας) ισχύει μόνο για τους YEARLY (ετήσιους) κανόνες.';
$string['errorrequiredurlorfile'] = 'Είτε μια διεύθυνση URL ή ένα αρχείο είναι υποχρεωτικό για να εισαγάγετε ένα ημερολόγιο.';
$string['errorrrule'] = 'Ο κανόνας επανάληψης περασμένων μοιάζει λανθασμένος.';
$string['errorrruleday'] = 'Ο κανόνας επανάληψης έχει μια μη έγκυρη παράμετρο ημέρας.';
$string['errorrrulefreq'] = 'Ο κανόνας επανάληψης έχει μια μη έγκυρη παράμετρο συχνότητας';
$string['eventcalendareventcreated'] = 'Το γεγονός ημερολογίου δημιουργήθηκε';
$string['eventcalendareventdeleted'] = 'Το γεγονός ημερολογίου διαγράφηκε';
$string['eventcalendareventupdated'] = 'Το γεγονός ημερολογίου ενημερώθηκε';
$string['eventdate'] = 'Ημερομηνία';
$string['eventdescription'] = 'Περιγραφή';
$string['eventduration'] = 'Διάρκεια';
$string['eventendtime'] = 'Ώρα λήξης';
$string['eventendtimewrapped'] = '{$a} (Ώρα λήξης)';
$string['eventinstanttime'] = 'Ώρα';
$string['eventkind'] = 'Τύπος του γεγονότος';
$string['eventname'] = 'Τίτλος γεγονότος';
$string['eventnameandcategory'] = '{$a->κατηγορία}: {$a->όνομα}';
$string['eventnameandcourse'] = '{$a->course}: {$a->name}';
$string['eventnamelocation'] = '{$a->name} τοποθεσία: {$a->location}';
$string['eventnone'] = 'Κανένα γεγονός';
$string['eventrepeat'] = 'Επαναλήψεις';
$string['events'] = 'Γεγονότα';
$string['eventsall'] = 'Όλα τα γεγονότα';
$string['eventsdeleted'] = '{$a} γεγονότα διαγράφηκαν';
$string['eventsfor'] = '{$a} γεγονότα';
$string['eventsimported'] = '{$a} γεγονότα εισήχθησαν';
$string['eventskey'] = 'Υπόμνημα γεγονότων';
$string['eventsource'] = 'Προέλευση γεγονότος';
$string['eventspersonal'] = 'Τα προσωπικά μου γεγονότα';
$string['eventsrelatedtocategories'] = 'Γεγονότα σχετικά με κατηγορίες';
$string['eventsrelatedtocourses'] = 'Γεγονότα σχετικά με μαθήματα';
$string['eventsrelatedtogroups'] = 'Γεγονότα σχετικά με ομάδες';
$string['eventsskipped'] = '{$a} γεγονότα παραλείφθηκαν';
$string['eventstarttime'] = 'Ώρα έναρξης';
$string['eventstoexport'] = 'Γεγονότα για εξαγωγή';
$string['eventsubscriptioncreated'] = 'Η δήλωση εγγραφής στο ημερολόγιο δημιουργήθηκε';
$string['eventsubscriptiondeleted'] = 'Η δήλωση εγγραφής στο ημερολόγιο διαγράφηκε';
$string['eventsubscriptioneditwarning'] = 'Αυτό το γεγονός ημερολογίου αποτελεί μέρος μιας δήλωσης εγγραφής. Οποιεσδήποτε αλλαγές κάνετε σε αυτό το γεγονός θα χαθούν αν η δήλωση εγγραφής διαγραφεί.';
$string['eventsubscriptionupdated'] = 'Η δήλωση εγγραφής στο ημερολόγιο ενημερώθηκε';
$string['eventsupdated'] = '{$a} γεγονότα ενημερώθηκαν';
$string['eventtime'] = 'Ώρα';
$string['eventtype'] = 'Τύπος γεγονότος';
$string['eventtypecategory'] = 'γεγ. κατηγορίας';
$string['eventtypecourse'] = 'γεγ. μαθήματος';
$string['eventtypegroup'] = 'γεγ. ομάδας';
$string['eventtypemodule'] = 'γεγ. αρθρώματος';
$string['eventtypeother'] = 'άλλα';
$string['eventtypesite'] = 'γεγ. ιστοτόπου';
$string['eventtypeuser'] = 'γεγ. χρήστη';
$string['eventview'] = 'Λεπτομέρειες γεγονότος';
$string['expired'] = 'Έληξε';
$string['explain_site_timeformat'] = 'Μπορείτε να επιλέξετε να προβάλλονται οι ώρες σε 12ωρη ή 24ωρη μορφή. Αν επιλέξετε «προεπιλογή», τότε η μορφή θα επιλεγεί αυτόματα με βάση τη γλώσσα που ορίσατε ως προεπιλεγμένη. Κάθε χρήστης μπορεί πάντως να παρακάμψει/αλλάξει τη ρύθμιση αυτή για τον εαυτό του.';
$string['export'] = 'Εξαγωγή';
$string['exportbutton'] = 'Εξαγωγή';
$string['exportcalendar'] = 'Εξαγωγή ημερολογίου';
$string['exporthelp'] = '<p>Η διεύθυνση URL του ημερολογίου παρέχει έναν δυναμικό σύνδεσμο για την εισαγωγή συμβάντων σε άλλα ημερολόγια. Τυχόν νέα, τροποποιημένα ή διαγραμμένα συμβάντα στο ημερολόγιο προέλευσης <strong>θα</strong> θα αντικατοπτρίζονται στα άλλα ημερολόγια.</p>
<p>Η εξαγωγή ημερολογίου σάς επιτρέπει να δημιουργήσετε ένα αντίγραφο ασφαλείας των συμβάντων, το οποίο ενδέχεται να εισαχθεί σε άλλα ημερολόγια. Οι ενημερώσεις που γίνονται στο ημερολόγιο προέλευσης <strong>δεν</strong> θα αντικατοπτρίζονται στα άλλα ημερολόγια.</p>';
$string['forcecalendartype'] = 'Υποχρεωτικό ημερολόγιο';
$string['fri'] = 'Παρ';
$string['friday'] = 'Παρασκευή';
$string['fullcalendar'] = 'Πλήρες ημερολόγιο';
$string['generateurlbutton'] = 'Διεύθυνση URL ημερολογίου';
$string['gotoactivity'] = 'Πηγαίνετε στη δραστηριότητα';
$string['gotocalendar'] = 'Μετάβαση στο ημερολόγιο';
$string['group'] = 'Ομάδα συμμετεχόντων';
$string['groupevent'] = 'Ομαδικό γεγονός';
$string['groupevents'] = 'Ομαδικά γεγονότα';
$string['hideeventtype'] = 'Κρύψε {$a}';
$string['hourly'] = 'Ωριαία';
$string['importcalendar'] = 'Εισαγωγή ημερολογίου';
$string['importcalendarexternal'] = 'Εισαγωγή εξωτερικού ημερολογίου;';
$string['importcalendarfrom'] = 'Εισαγωγή από';
$string['importcalendarheading'] = 'Εισαγωγή ημερολογίου...';
$string['importfromfile'] = 'Αρχείο ημερολογίου (.ics)';
$string['importfromurl'] = 'Διεύθυνση URL ημερολογίου';
$string['invalideventtype'] = 'Ο τύπος γεγονότος που έχετε επιλέξει δεν είναι έγκυρος.';
$string['invalidtimedurationminutes'] = 'Η διάρκεια σε λεπτά που έχετε εισάγει δεν είναι έγκυρη. Παρακαλούμε εισάγετε την διάρκεια σε λεπτά μεγαλύτερη από 0 ή επιλέξτε Όχι διάρκεια.';
$string['invalidtimedurationuntil'] = 'Η ημερομηνία και η ώρα που επιλέξατε για διάρκεια έως είναι προγενέστερη από την ώρα έναρξης του γεγονότος. Παρακαλούμε διορθώστε πριν προχωρήσετε.';
$string['iwanttoexport'] = 'Εξαγωγή';
$string['less'] = 'Λιγότερα';
$string['managesubscriptions'] = 'Εισαγωγή ή εξαγωγή ημερολογίων';
$string['manyevents'] = '{$a} γεγονότα';
$string['mon'] = 'Δευ';
$string['monday'] = 'Δευτέρα';
$string['monthly'] = 'Μηνιαία';
$string['monthnext'] = 'Επόμενος μήνας';
$string['monthprev'] = 'Προηγούμενος μήνας';
$string['monththis'] = 'Τρέχων μήνας';
$string['more'] = 'Περισσότερα';
$string['moreevents'] = '{$a} περισσότερα';
$string['namewithsource'] = '{$a->name} ({$a->source})';
$string['never'] = 'Ποτέ';
$string['newevent'] = 'Νέο γεγονός';
$string['nocalendarsubscriptions'] = 'Δεν έχεις καμία δήλωση εγγραφής σε ημερολόγιο';
$string['notitle'] = 'χωρίς τίτλο';
$string['noupcomingevents'] = 'Κανένα επικείμενο γεγονός';
$string['oneevent'] = '1 γεγονός';
$string['pollinterval'] = 'Διάστημα ενημέρωσης';
$string['pollinterval_help'] = 'Πόσο συχνά θα θέλατε το ημερολόγιο να ενημερώνεται με νέα γεγονότα.';
$string['pref_lookahead'] = 'Πριν από πόσες ημέρες θεωρείται επικείμενο ένα γεγονός;';
$string['pref_lookahead_help'] = 'Καθορίζει τον (μέγιστο) αριθμό ημερών (από σήμερα) στο μέλλον μέσα στις οποίες ξεκινά ένα γεγονός προκειμένου να θεωρηθεί επικείμενο. Γεγονότα που ξεκινούν πέρα από αυτό δεν θα εμφανίζονται ως επικείμενα. Παρακαλούμε σημειώστε ότι <strong>δεν υπάρχει καμία εγγύηση</strong> ότι όλα τα γεγονότα που ξεκινούν σε αυτό το χρονικό πλαίσιο θα εμφανιστούν. Αν υπάρχουν πάρα πολλά (πάνω από την προτίμηση «Μέγιστος αριθμός επικείμενων γεγονότων»), τότε τα πιο μακρινά γεγονότα δεν θα εμφανίζονται.';
$string['pref_maxevents'] = 'Μέγιστος αριθμός επικείμενων γεγονότων';
$string['pref_maxevents_help'] = 'Ορίζεται ο μέγιστος αριθμός επικείμενων γεγονότων που μπορούν να εμφανιστούν. Αν επιλέξετε μεγάλο αριθμό γεγονότων, τότε υπάρχει περίπτωση να χρησιμοποιηθεί μεγάλο μέρος της οθόνης σας για την εμφάνισή τους.';
$string['pref_persistflt'] = 'Απομνημόνευση ρυθμίσεων φίλτρου';
$string['pref_persistflt_help'] = 'Εάν ενεργοποιηθεί, τότε το Moodle θα θυμάται τις τελευταίες ρυθμίσεις φίλτρου γεγονότων σας και θα τις επαναφέρει αυτόματα κάθε φορά που θα συνδέεστε.';
$string['pref_startwday'] = 'Πρώτη μέρα εβδομάδας';
$string['pref_startwday_help'] = 'Οι εβδομάδες στο ημερολόγιο θα εμφανίζονται αρχής γενομένης από την ημέρα που θα επιλέξετε εδώ.';
$string['pref_timeformat'] = 'Μορφή εμφάνισης ώρας';
$string['pref_timeformat_help'] = 'Μπορείτε να επιλέξετε να βλέπετε την ώρα σε 12ωρη ή 24ωρη μορφή. Αν επιλέξετε «προεπιλογή», τότε η μορφή θα επιλεγεί αυτόματα ανάλογα με τη γλώσσα που χρησιμοποιείτε στον ιστότοπο.';
$string['preferences'] = 'Προτιμήσεις';
$string['preferences_available'] = 'Οι προσωπικές σας προτιμήσεις';
$string['preferredcalendar'] = 'Προτεινόμενο ημερολόγιο';
$string['privacy:metadata:calendar:event'] = 'Το στοιχείο λογισμικού ημερολογίου μπορεί να αποθηκεύσει λεπτομέρειες γεγονότος ημερολογίου χρήστη στο βασικό υποσύστημα (πυρήνα).';
$string['privacy:metadata:calendar:event:description'] = 'Περιγραφή του γεγονότος ημερολογίου.';
$string['privacy:metadata:calendar:event:eventtype'] = 'Ο τύπος γεγονότος του γεγονότος ημερολογίου.';
$string['privacy:metadata:calendar:event:name'] = 'Το όνομα του γεγονότος ημερολογίου.';
$string['privacy:metadata:calendar:event:timeduration'] = 'Η διάρκεια του γεγονότος ημερολογίου.';
$string['privacy:metadata:calendar:event:timestart'] = 'Η ώρα έναρξης του γεγονότος ημερολογίου.';
$string['privacy:metadata:calendar:event_subscriptions'] = 'Το στοιχείο λογισμικού Ημερολόγιο μπορεί να αποθηκεύσει τις λεπτομέρειες των δηλώσεων εγγραφής χρήστη ημερολογίου μέσα στο υποσύστημα πυρήνα.';
$string['privacy:metadata:calendar:event_subscriptions:eventtype'] = 'Ο τύπος γεγονότος της δήλωσης εγγραφής ημερολογίου.';
$string['privacy:metadata:calendar:event_subscriptions:name'] = 'Το όνομα της δήλωσης εγγραφής ημερολογίου.';
$string['privacy:metadata:calendar:event_subscriptions:url'] = 'Η διεύθυνση URL της δήλωσης εγγραφής ημερολογίου.';
$string['privacy:metadata:calendar:preferences:calendar_savedflt'] = 'Η προτίμηση του χρήστη στις ρυθμίσεις του τύπου εμφάνισης γεγονότος ημερολογίου.';
$string['recentupcoming'] = 'Πρόσφατα και επόμενες 60 ημέρες';
$string['repeatedevents'] = 'Επαναλαμβανόμενα γεγονότα';
$string['repeateditall'] = 'Εφαρμογή αλλαγών σε όλα τα γεγονότα ({$a}) σε αυτή την επαναλαμβανόμενη σειρά';
$string['repeateditthis'] = 'Εφαρμογή αλλαγών σε αυτό το γεγονός μόνο';
$string['repeatevent'] = 'Επανάληψη γεγονότος';
$string['repeatnone'] = 'Χωρίς επαναλήψεις';
$string['repeatweeksl'] = 'Εβδομαδιαία επανάληψη, γενική δημιουργία';
$string['repeatweeksr'] = 'γεγονότων';
$string['requiresaction'] = 'Το {$a} απαιτεί ενέργεια';
$string['sat'] = 'Σαβ';
$string['saturday'] = 'Σάββατο';
$string['showeventtype'] = 'Δείξε {$a}';
$string['shown'] = 'εμφανίζονται';
$string['site'] = 'Ιστότοπος';
$string['siteevent'] = 'Γεγονός ιστοτόπου';
$string['siteevents'] = 'Γεγονότα ιστοτόπου';
$string['spanningevents'] = 'Γεγονότα σε εξέλιξη';
$string['subscriptionname'] = 'Όνομα ημερολογίου';
$string['subscriptionremoved'] = 'Η δήλωσης εγγραφής στο ημερολόγιο {$a} αφαιρέθηκε';
$string['subscriptions'] = 'Δηλώσεις εγγραφής';
$string['subscriptionsource'] = 'Προέλευση γεγονότος: {$a}';
$string['subscriptionupdated'] = 'Η δήλωσης εγγραφής στο ημερολόγιο {$a} ενημερώθηκε';
$string['sun'] = 'Κυρ';
$string['sunday'] = 'Κυριακή';
$string['thu'] = 'Πεμ';
$string['thursday'] = 'Πέμπτη';
$string['timeformat_12'] = '12ωρη (πμ/μμ)';
$string['timeformat_24'] = '24ωρη';
$string['timeperiod'] = 'Χρονική περίοδος';
$string['today'] = 'Σήμερα';
$string['todayplustitle'] = 'Σήμερα {$a}';
$string['tomorrow'] = 'Αύριο';
$string['tt_deleteevent'] = 'Διαγραφή γεγονότος';
$string['tt_editevent'] = 'Επεξεργασία γεγονότος';
$string['tue'] = 'Τρι';
$string['tuesday'] = 'Τρίτη';
$string['typecategory'] = 'Γεγονός κατηγορίας';
$string['typeclose'] = 'Κλείσιμο γεγονότος';
$string['typecourse'] = 'Γεγονός μαθήματος';
$string['typedue'] = 'Γεγονός που λήγει';
$string['typegradingdue'] = 'Γεγονός λήξης βαθμολόγησης';
$string['typegroup'] = 'Ομαδικό γεγονός';
$string['typeopen'] = 'Ανοιχτό γεγονός';
$string['typesite'] = 'Γεγονός ιστοτόπου';
$string['typeuser'] = 'Γεγονός χρήστη';
$string['upcomingevents'] = 'Επικείμενα γεγονότα';
$string['upcomingeventsfor'] = 'Επικείμενα γεγονότα για:';
$string['urlforical'] = 'Διεύθυνση URL ημερολογίου για εξαγωγή σε μορφή iCalendar';
$string['user'] = 'Χρήστης';
$string['userevent'] = 'Γεγονός χρήστη';
$string['userevents'] = 'Γεγονότα χρήστη';
$string['viewupcomingactivitiesdue'] = 'Εμφάνιση των επερχόμενων λήξεων οφειλόμενων δραστηριοτήτων';
$string['wed'] = 'Τετ';
$string['wednesday'] = 'Τετάρτη';
$string['weekly'] = 'Εβδομαδιαία';
$string['weeknext'] = 'Επόμενη εβδομάδα';
$string['weekthis'] = 'Τρέχουσα εβδομάδα';
$string['when'] = 'Όταν';
$string['whendate'] = 'Πότε: {$a}';
$string['yesterday'] = 'Χθες';
$string['youcandeleteallrepeats'] = 'Αυτό το γεγονός αποτελεί μέρος μιας επαναλαμβανόμενης σειράς γεγονότων. Μπορείτε να διαγράψετε αυτό το γεγονός μόνο του, ή και τα {$a} γεγονότα της σειράς μονομιάς.';
$string['yoursubscriptions'] = 'Εισαχθέντα ημερολόγια';
