<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'congrea', language 'el', version '4.5'.
 *
 * @package     congrea
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['absent'] = 'Απών:';
$string['action'] = 'Ενέργεια';
$string['addmultiplesessions'] = 'Επανάληψη αυτής της συνόδου';
$string['addsessions'] = 'Προσθήκη συνόδου';
$string['afterkeysavemsg'] = 'Επιτυχής προπαροχή και αποθήκευση API και μυστικών κλειδιών Congrea';
$string['allsessions'] = 'Όλες οι επερχόμενες σύνοδοι';
$string['alreadyhave'] = 'Έχετε ήδη ρυθμίσει το κλειδί και το μυστικό API.';
$string['apikey'] = 'Το κλειδί API σας είναι';
$string['askQuestion'] = 'Ερώτηση & Απάντηση';
$string['askQuestion_help'] = 'Εάν ενεργοποιηθεί, επιτρέψτε στον παρουσιαστή και στους μαθητές να χρησιμοποιούν τη δυνατότητα «Ερώτηση»';
$string['attendance'] = 'Παρουσία';
$string['attendeerecording'] = 'Εγγραφή μαθητών';
$string['attendencereport'] = 'Αναφορά παρουσιών';
$string['audio'] = 'Ήχος';
$string['audiolatency'] = 'Λανθάνουσα καθυστέρηση ήχου';
$string['audiotest'] = 'Δοκιμή ήχου';
$string['blankduration'] = 'Μη έγκυρη είσοδος!';
$string['cgallowoverride'] = 'Να επιτρέπεται παράκαμψη';
$string['cgallowoverride_help'] = 'Εάν ενεργοποιηθεί, επιτρέπει οι ρυθμίσεις να παρακάμπτονται από τις ρυθμίσεις δραστηριότητας μέσα από το μάθημα.';
$string['cgapi'] = 'Κλειδί API Congrea';
$string['cgapid'] = 'Δώστε το κλειδί API Congrea';
$string['cgrecording'] = 'Εγγραφή συνόδου';
$string['cgrecording_help'] = 'Εάν ενεργοποιηθεί, επιτρέπει αυτόματη εγγραφή των Congrea συνόδων σας για αυτή την δραστηριότητα.';
$string['cgrecordingd'] = 'Εάν ενεργοποιηθεί, μπορεί να επιτραπεί αυτόματη εγγραφή συνόδου στις δραστηριότητες Congrea.';
$string['cgsecret'] = 'Μυστικό κλειδί Congrea';
$string['cgsecretd'] = 'Δώστε το μυστικό κλειδί Congrea';
$string['cgsecretdv'] = 'Μυστικό κλειδί:';
$string['closenotset'] = 'Πρέπει να καθορίσετε μια ημερομηνία τέλους.';
$string['closesameopen'] = 'Η ώρα ανοίγματος και κλεισίματος της συνόδου δεν πρέπει να είναι η ίδια';
$string['closetime'] = 'Σύνοδοι που έκλεισαν';
$string['colorpicker'] = 'Επιλογέας προσαρμοσμένου χρώματος';
$string['colorpickerd'] = 'Επιλογή προσαρμοσμένου χρώματος';
$string['conflictsdate'] = 'Μη διαθέσιμη χρονοθυρίδα';
$string['congrea'] = 'Congrea';
$string['congrea:addinstance'] = 'Προσθήκη ενός νέου Congrea';
$string['congrea:attendance'] = 'Αναφορά παρακολούθησης/απουσιών';
$string['congrea:playrecording'] = 'Αναπαραγωγή εγγραφής';
$string['congrea:pollreport'] = 'Αναφορά ψηφοφορίας Congrea';
$string['congrea:quizreport'] = 'Αναφορά κουίζ Congrea';
$string['congrea:recordingdelete'] = 'Διαγραφή εγγραφής';
$string['congrea:view'] = 'Εμφάνιση Congrea';
$string['congreadocument'] = 'Αυτό το έχετε ήδη κατεβάσει';
$string['congreafieldset'] = 'Προσαρμοσμένο παράδειγμα σετ πεδίων';
$string['congreagenerald'] = 'Κλειδί API Congrea';
$string['congreaname'] = 'Όνομα Congrea';
$string['congreaname_help'] = 'Αυτή είναι μια αίθουσα διδασκαλίας πραγματικού χρόνου εντός σύνδεσης, που επιτρέπει στους συμμετέχοντες να αλληλεπιδρούν μεταξύ τους και παρέχει εργαλεία ασύγχρονης επικοινωνίας όπως ασπροπίνακα, γραπτή συνομιλία και κοινή χρήση οθόνης.';
$string['congreapoll'] = 'Ερώτηση ψηφοφορίας Congrea';
$string['congrearecseeting'] = 'Εγγραφή Congrea';
$string['correct'] = 'Σωστά';
$string['coursesactivity'] = 'Δραστηριότητα μαθημάτων (Γεγονότα κατά μάθημα)';
$string['customsetting'] = 'Προσαρμοσμένες ρυθμίσεις';
$string['dateandtime'] = 'Ημερομηνία και ώρα';
$string['datetimelist'] = 'Ημερομηνία και ώρα της πρώτης συνόδου';
$string['deletebtn'] = 'Διαγραφή';
$string['deletepolloption'] = 'Αποτυχία λειτουργίας διαγραφής';
$string['deleterecordingfile'] = 'Είστε σίγουρος ότι θέλετε να διαγραφεί το αρχείο εγγραφής<br />«{$a}»;';
$string['deleteschedule'] = 'Σίγουρα διαγραφή;';
$string['disable'] = 'Απενεργοποίηση';
$string['disableAudio'] = 'Απενεργοποίηση ήχου';
$string['disablespeaker'] = 'Σίγαση';
$string['displaymode'] = 'Κατάσταση εμφάνισης';
$string['domain'] = 'Διεύθυνση URL τομέα';
$string['downloadsession'] = 'Παρακαλούμε, περιμένετε όσο η εγγραφή κατεβαίνει.';
$string['editbtn'] = 'Τροποποίηση';
$string['editingschedule'] = 'Επεξεργασία μιας χρονοπρογραμματισμένης συνόδου';
$string['editingsession'] = 'Τροποποιήσεις χρονοπρογράμματος:';
$string['email'] = 'Διεύθυνση ηλε.ταχυδρομείου';
$string['email_help'] = 'Δώστε την διεύθυνση ηλε.ταχυδρομείου σας.';
$string['enable'] = 'Ενεργοποίηση';
$string['enableAudio'] = 'Κατάρτηση σίγασης';
$string['enablerecording'] = 'Εγγραφή συνόδου';
$string['enablespeaker'] = 'Ενεργοποίηση ήχου';
$string['enrolteacher'] = 'Εγγραφή ενός διδάσκοντος σε αυτό το μάθημα';
$string['errordurationlimit'] = 'Έχετε εισαγάγει μη έγκυρη διάρκεια περιόδου σύνδεσης. Θα πρέπει να είναι περισσότερο από 10 λεπτά και λιγότερο από 24 ώρες.';
$string['errortimeduration'] = 'Έχετε εισαγάγει μη έγκυρη διάρκεια περιόδου σύνδεσης. Θα πρέπει να είναι περισσότερο από 10 λεπτά και λιγότερο από 24 ώρες.';
$string['esessiondate'] = 'Έχετε εισαγάγει μη έγκυρη ημερομηνία ή ώρα.';
$string['event'] = 'Γεγονός';
$string['eventsbymonth'] = 'Γεγονότα κατά μήνα ({$a})';
$string['eventsmosttriggered'] = 'Πιο συχνά προκληθέντα γεγονότα';
$string['exittime'] = 'Χρόνος εξόδου';
$string['filename'] = 'ΌνομαΑρχείου';
$string['filter'] = 'Επιλογή φίλτρου';
$string['filter_help'] = 'Επιλογή φίλτρου';
$string['firstname'] = 'Όνομα (βαπτιστικό)';
$string['firstname_help'] = 'Δώστε το μικρό σας όνομα.';
$string['from'] = 'από:';
$string['fromsessiondate'] = 'Ώρα έναρξης συνόδου';
$string['fromsessiondate_help'] = 'Επιλογή ημερομηνίας και ώρας της συνόδου.';
$string['generalsection'] = 'Γενικές ρυθμίσεις';
$string['generate'] = 'Δημιουργία';
$string['grade'] = 'Βαθμός';
$string['gradenotsaved'] = 'Ο βαθμός δεν αποθηκεύτηκε';
$string['graphic:view'] = 'Εμφάνιση γραφικής αναφοράς γεγονότων';
$string['headingschedules'] = 'Χρονοπρογράμματα';
$string['hours'] = 'ώρ';
$string['hourssetting'] = 'Έχετε εισαγάγει μη έγκυρη ημερομηνία ή ώρα. Βεβαιωθείτε ότι η συνολική διάρκεια της συνόδου δεν θα ξεπεράσει τις 10 ώρες.';
$string['indvprogress'] = 'Τρέχουσα εργασία';
$string['infinitesession'] = 'Σύνοδος με ανοιχτό τέλος';
$string['invalidcoursemodule'] = 'Μη έγκυρο άρθρωμα μαθήματος.';
$string['invaliddata'] = 'Μη έγκυρη ημερομηνία.';
$string['jointime'] = 'Χρόνος ένταξης';
$string['keyis'] = 'Κλειδί API:';
$string['lastname'] = 'Επώνυμο';
$string['lastname_help'] = 'Δώστε το επώνυμό σας.';
$string['legacysession'] = 'Σύνοδος παλαιού τύπου';
$string['livepresenter'] = 'Παρουσιαστής: {$a->firstname} {$a->lastname}';
$string['menu'] = 'Γραφική αναφορά γεγονότων';
$string['mins'] = 'λεπτά';
$string['missingdomain'] = 'Λείπει το όνομα τομέα';
$string['missingprivacy'] = 'Απαιτείται αποδοχή της Πολιτικής Προστασίας Προσωπικών Δεδομένων.';
$string['missingterms'] = 'Απαιτείται αποδοχή των Όρων της Υπηρεσίας.';
$string['modulename'] = 'Congrea';
$string['name'] = 'Όνομα';
$string['newsessionadded'] = 'Δημιουργείται νέο χρονοπρόγραμμα στον πίνακα.';
$string['next30sessions'] = 'Επόμενες 30 σύνοδοι';
$string['next7sessions'] = 'Επόμενες 7 σύνοδοι';
$string['next90sessions'] = 'Επόμενες 90 σύνοδοι';
$string['noattempt'] = 'Δεν δοκιμάστηκε από κανένα χρήστη';
$string['nofetchplandetails'] = 'Αδυναμία κλήσης/λήψης λεπτομερειών του σχεδίου σας. Παρακαλούμε, δοκιμάστε ξανά!';
$string['nopolldata'] = 'Κανένα δεδομένο προς αποθήκευση';
$string['noquestionsinquiz'] = 'Δεν υπάρχουν ερωτήσεις σε αυτό το κουίζ.';
$string['noquizattempt'] = 'Δεν δοκιμάστηκε από κανένα χρήστη';
$string['noquizreport'] = 'Κανένα διαθέσιμο δεδομένο.';
$string['norecordingtoshow'] = 'Καμία εγγραφή (ήχου/βίντεο) προς εμφάνιση';
$string['noreport'] = 'Κανένα διαθέσιμο δεδομένο.';
$string['nosession'] = 'Καμία σύνοδος δεν είναι διαθέσιμη προς εμφάνιση.';
$string['notavaliduser'] = 'Μη έγκυρος παρουσιαστής.';
$string['notavaliduserwithname'] = 'είναι μη έγκυρος παρουσιαστής.';
$string['notcapabletodeletereport'] = 'Δεν μπορείτε να διαγράψετε μια αναφορά, επειδή δεν έχετε τη δυνατότητα να διαχειριστείτε την σύνοδο.';
$string['notcapabletoviewschedules'] = 'Δεν έχετε δικαίωμα να εμφανίσετε χρονοπρογράμματα.';
$string['nouser'] = 'Το όνομα χρήστη δεν βρέθηκε';
$string['opentime'] = 'Ανοιχτές σύνοδοι';
$string['options'] = 'Επιλογές';
$string['overallprogress'] = 'Γενική πρόοδος';
$string['overrideheading'] = 'Παράκαμψη ρυθμίσεων';
$string['percentage'] = 'Ποσοστό';
$string['play'] = 'Εκτέλεση';
$string['pluginadministration'] = 'Διαχείριση Congrea';
$string['pluginname'] = 'Congrea';
$string['pollquestions'] = 'Ερωτήσεις ψηφοφορίας';
$string['pollreport'] = 'Αναφορά ψηφοφορίας';
$string['presence'] = 'Παρουσία';
$string['present'] = 'Παρών:';
$string['preset'] = 'Προρύθμιση χρώματος';
$string['presetd'] = 'Επιλογή προρύρθμισης χρώματος';
$string['pressAlwaysToSpeak'] = 'Να πατάτε πάντα για να μιλήσετε';
$string['pressalways'] = 'Να πατάτε πάντα για να μιλήσετε';
$string['pressonce'] = 'Να πατάτε μία φορά για να μιλήσετε';
$string['privacy'] = 'Αποδέχομαι την <a href=\'https://www.congrea.com/documents-for-foreign-customers/#5e886344a0508-0\' target=\'_blank\'>Πολιτική Προστασίας Προσωπικών Δεδομένων</a>.';
$string['privacy_help'] = 'Διαβάστε την Πολιτική Προστασίας Προσωπικών Δεδομένων και επιλέξτε το πλαίσιο επιλογής.';
$string['proposedspeed'] = 'Προτεινόμενη ταχύτητα';
$string['psession'] = 'Καταγεγραμμένες σύνοδοι';
$string['pushtotalk'] = 'Πιέστε για να μιλήσετε';
$string['pushtotalk_help'] = 'Εάν ενεργοποιηθεί, εμφανίζεται μια επιπλέον επιλογή για δοκιμή ήχου.';
$string['qaAnswer'] = 'Απάντηση';
$string['qaAnswer_help'] = 'Εάν ενεργοποιηθεί, να επιτρέπεται στους μαθητές να απαντήσουν στην ερώτηση που αναρτήθηκε στον πίνακα «Ερώτηση»';
$string['qaComment'] = 'Σχόλιο';
$string['qaComment_help'] = 'Εάν ενεργοποιηθεί, να επιτρέπεται στους μαθητές να αναρτούν σχόλια για απαντήσεις και άλλα σχόλια';
$string['qaMarkNotes'] = 'Σελιδοδείκτες & Σημειώσεις';
$string['qaMarkNotes_help'] = 'Εάν ενεργοποιηθεί, να επιτρέπεται στον παρουσιαστή και στους μαθητές να προσθέτουν ιδιωτικούς σελιδοδείκτες και σημειώσεις';
$string['qaUpvote'] = 'Ψήφοι';
$string['qaUpvote_help'] = 'Εάν ενεργοποιηθεί, να επιτρέπεται στους μαθητές να ψηφίζουν υπέρ για τις ερωτήσεις και τις απαντήσεις';
$string['qattempted'] = 'Ερ.Προσπαθήθηκε';
$string['quantity'] = 'ποσότητα';
$string['questionsanswersettings'] = 'Ρυθμίσεις ερωτήσεων & απαντήσεων';
$string['quizheading'] = 'Επισκόπηση κουίζ Congrea';
$string['quizname'] = 'Όνομα κουίζ';
$string['quizreport'] = 'Αναφορά κουίζ';
$string['recShowPresentorRecordingStatus'] = 'Ορατότητα προς τον παρουσιαστή, της κατάστασης εγγραφής';
$string['recordedsessions'] = 'Συνεδρίες με εγγραφή ήχου/βίντεο';
$string['recordingcontrol'] = 'Έλεγχος εγγραφών';
$string['recordingsection'] = 'Ρυθμίσεις εγγραφών';
$string['recordingviewed'] = 'Η εγγραφή ήχου/βίντεο εμφανίστηκε';
$string['repeatedweeks'] = 'εβδομάδες κάθε';
$string['repeaton'] = 'Επανάληψη στις';
$string['repeatsession'] = 'Σύνοδοι επανάληψης';
$string['repeatsessions'] = 'Εάν θέλετε να χρονοπρογραμματίσετε πολλαπλές συνόδους';
$string['repeatstatus'] = 'Επανάληψη για';
$string['repeattype'] = 'Τύπος επανάληψης';
$string['repeattype_help'] = 'Τύπος επανάληψης';
$string['repeatweekly'] = 'Επανάληψη κάθε εβδομάδα, δημιουργία συνολικά';
$string['replay'] = 'Επαν-εκτέλεση';
$string['replay_message'] = 'Ευχαριστούμε για την παρακολούθηση.';
$string['scheduleid'] = 'Αναγνωριστικό χρονοπρογράμματος';
$string['secretis'] = 'Μυστικό κλειδί:';
$string['secs'] = 'δευτερόλεπτο/-α';
$string['selectcolor'] = 'Επιλογή χρώματος';
$string['selectcolor_help'] = 'Επιλογή του δικού σας χρώματος για την τάξη σας';
$string['selectdays'] = 'Επιλογή ημερών';
$string['selectteacher'] = 'Επιλογή παρουσιαστή';
$string['selectteacher_help'] = 'Ανάθεση ενός παρουσιαστή για αυτή τη σύνοδο.';
$string['sessionareport'] = 'Αναφορά παρουσιών συνόδου';
$string['sessionclosed'] = 'Η αίθουσα τάξης δεν έχει ανοίξει ακόμα';
$string['sessiondate'] = 'Ημερομηνία συνόδου';
$string['sessionduration'] = 'Διάρκεια συνόδου:';
$string['sessionedited'] = 'Η σύνοδος/-οι ενημερώθηκαν.';
$string['sessionenddate'] = 'Ημερομηνία λήξης συνόδου';
$string['sessionenddate_help'] = 'Ημερομηνία λήξης συνόδου';
$string['sessionendmsg'] = 'Η σύνοδος έχει κλείσει. Μπορείτε τώρα να κλείσετε τον περιηγητή σας.';
$string['sessionnouser'] = 'Δεν υπάρχει χρήστης σε αυτήν την σύνοδο';
$string['sessions'] = 'σύνοδος/-οι';
$string['sessionsettings'] = 'Χρονοπρογραμματισμός συνόδου/-ων';
$string['sessionsschedule'] = 'Χρονοπρόγραμμα για συνόδους';
$string['showAttendeeRecordingStatus'] = 'Ορατότητα προς τον μαθητή, της κατάστασης εγγραφής';
$string['silencedetect'] = 'Ανίχνευση σιγής';
$string['srecordingsection_help'] = '<b>Ρυθμίσει μαθητή</b> - Αυτές οι ρυθμίσεις θα επηρρεάσουν τα δικαιώματα εγγραφής ήχου/βίντεο των μαθητών.';
$string['studentaudio'] = 'Ήχος των μαθητών';
$string['studentgc'] = 'Ομαδική γραπτή συνομιλία';
$string['studentgc_help'] = 'Εάν ενεργοποιηθεί, επιτρέπει στους μαθητές να συμμετέχουν σε ομαδική γραπτή συνομιλία/συζήτηση κατά τη διάρκεια της συνόδου.';
$string['studentm'] = 'Διαχείριση δυνατοτήτων';
$string['studentm_help'] = 'Διαχείριση δυνατοτήτων';
$string['studentpc'] = 'Ιδιωτική γραπτή συνομιλία';
$string['studentvideo'] = 'Βίντεο μαθητή';
$string['submiterror'] = 'Σφάλμα:';
$string['teacher'] = 'Παρουσιαστής';
$string['testingbrowser'] = 'Δοκιμασία συμβατότητας περιηγητή';
$string['testinginternetspeed'] = 'Δοκιμασία ταχύτητας Διαδικτύου';
$string['testingmichrophone'] = 'Δοκιμασία μικροφώνου';
$string['testingspeaker'] = 'Δοκιμασία ηχείου';
$string['testingwebcam'] = 'Δοκιμασία σύνδεσης βιντεοκάμερας ιστού';
$string['time'] = 'Ώρα:';
$string['timecreated'] = 'Ώρα δημιουργίας';
$string['timedur'] = 'Χρονική διάρκεια';
$string['timeduration'] = 'Χρονική διάρκεια σε λεπτά';
$string['timetaken'] = 'Ώρα';
$string['to'] = 'προς';
$string['tosessiondate'] = 'Τέλος χρόνου συνόδου';
$string['tosessiondate_help'] = 'Επιλέξτε την ώρα λήξης της συνόδου που δεν πρέπει να υπερβαίνει τη συνολική διάρκεια των 10 ωρών.';
$string['totalconflicts'] = 'Συνολικές διενέξεις =';
$string['totalprogress'] = 'Συνολική πρόοδος';
$string['tpAudioTest'] = 'Δοκιμή ήχου';
$string['upcomingsession'] = 'Επερχόμενες σύνοδοι';
$string['updated'] = 'Αποθηκεύτηκε με επιτυχία.';
$string['userlist'] = 'Ορατότητα λίστας χρηστών';
$string['userlist_help'] = 'Εάν ενεργοποιηθεί, επιτρέπει στους μαθητές να βλέπουν την λίστα όσων παρακολουθούν κατά τη διάρκεια της συνόδου.';
$string['username'] = 'Όνομα χρήστη';
$string['users'] = 'Χρήστες';
$string['usersactivity'] = 'Δραστηριότητα χρήστη (Γεγονότα από χρήστη)';
$string['video'] = 'Βίντεο';
$string['video_help'] = 'Εάν ενεργοποιηθεί, από προεπιλογή, το βίντεο για όλους τους μαθητές θα είναι ενεργοποιημένο.';
$string['videoquality'] = 'Ποιότητα βίντεο';
$string['waitmsgconnect'] = 'Παρακαλούμε, περιμένετε λίγο. Η εφαρμογή προσπαθεί να συνδεθεί.';
$string['weeksevery'] = 'εβδομάδες κάθε';
$string['withoutrecording'] = 'χωρίς εγγραφές';
$string['withrecording'] = 'με εγγραφές';
