<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for component 'repository', language 'el', version '3.11'.
 *
 * @package     repository
 * @category    string
 * @copyright   1999 Martin Dougiamas and contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['accessiblefilepicker'] = 'Προσπελάσιμος επιλογέας αρχείων';
$string['activaterep'] = 'Ενεργοί χώροι αποθήκευσης';
$string['activerepository'] = 'Διαθέσιμα πρόσθετα αποθετηρίων';
$string['activitybackup'] = 'Αντίγραφο ασφαλείας δραστηριότητας';
$string['add'] = 'Προσθήκη';
$string['addfile'] = 'Προσθήκη...';
$string['addfiletext'] = 'Προσθήκη αρχείου';
$string['addplugin'] = 'Προσθήκη ενός πρόσθετου αποθετηρίου';
$string['aliaseschange'] = 'Υπάρχουν {$a} σύνδεσμοι προς αυτό το αρχείο. Εάν προχωρήσετε, τότε τυχόν τοποθεσίες με συνδέσμους, αυτή τη στιγμή, προς το αρχείο θα ενημερωθούν αυτόματα για να χρησιμοποιούν αντί αυτού ένα αντίγραφο του αρχείου.';
$string['allowexternallinks'] = 'Επιτρέπονται εξωτερικοί σύνδεσμοι';
$string['areacategoryintro'] = 'Εισαγωγή στην κατηγορία';
$string['areacourseintro'] = 'Εισαγωγή στο μάθημα';
$string['areacourseoverviewfiles'] = 'Εικόνα μαθήματος';
$string['areamainfile'] = 'Κύριο αρχείο';
$string['arearoot'] = 'Σύστημα';
$string['areauserbackup'] = 'Αντίγραφο ασφαλείας χρήστη';
$string['areauserdraft'] = 'Προσχέδια';
$string['areauserpersonal'] = 'Προσωπικά αρχεία';
$string['areauserprofile'] = 'Προφίλ';
$string['attachedfiles'] = 'Συνημμένα αρχεία';
$string['attachment'] = 'Συνημμένο';
$string['author'] = 'Συγγραφέας';
$string['automatedbackup'] = 'Αυτοματοποιημένα αντίγραφα ασφαλείας';
$string['back'] = '« Επιστροφή';
$string['backtodraftfiles'] = 'Επιστροφή στη διαχείριση προσχεδίων αρχείων';
$string['cachecleared'] = 'Τα αρχεία στην κρυφή μνήμη διαγράφονται';
$string['cacheexpire'] = 'Λήξη κρυφής μνήμης';
$string['cannotaccessparentwin'] = 'Όταν χρησιμοποιείται το HTTPS, το αποθετήριο δεν ανανεώνεται αυτόματα. Αντίθετα, πρέπει να επιστρέψετε στο εργαλείο επιλογής αρχείων και να επιλέξετε ξανά το αποθετήριο.';
$string['cannotdelete'] = 'Δεν είναι δυνατή η διαγραφή αυτού του αρχείου.';
$string['cannotdownload'] = 'Δεν είναι δυνατή η λήψη αυτού του αρχείου.';
$string['cannotdownloaddir'] = 'Δεν είναι δυνατή η λήψη αυτού του φακέλου';
$string['cannotinitplugin'] = 'Η κλήση plugin_init απέτυχε';
$string['cannotunzipcontentunreadable'] = 'Δεν είναι δυνατή η αποσυμπίεση αυτού του αρχείου, επειδή δεν είναι δυνατή η ανάγνωση των περιεχομένων του.';
$string['cannotunzipextractfileerror'] = 'Δεν είναι δυνατή η αποσυμπίεση αυτού του αρχείου, επειδή δεν είναι δυνατή η ανάγνωση ενός ή περισσότερων αρχείων του.';
$string['cannotunzipquotaexceeded'] = 'Δεν είναι δυνατή η αποσυμπίεση αυτού του αρχείου επειδή θα υπερβεί το μέγιστο επιτρεπόμενο μέγεθος σε αυτήν την περιοχή πρόχειρου.';
$string['choosealink'] = 'Επιλέξτε έναν σύνδεσμο…';
$string['chooselicense'] = 'Επιλογή άδειας χρήσης';
$string['chooselicense_help'] = 'Ακολουθήστε αυτούς τους συνδέσμους για περισσότερες πληροφορίες σχετικά με τις διαθέσιμες επιλογές άδειας χρήσης:';
$string['cleancache'] = 'Καθαρισμός των αρχείων στη προσωρινή μνήμη';
$string['close'] = 'Κλείσιμο';
$string['commonrepositorysettings'] = 'Κοινές ρυθμίσεις αποθετηρίων';
$string['configallowexternallinks'] = 'Αυτή η επιλογή δίνει την δυνατότητα σε όλους τους χρήστες να επιλέξουν ή όχι, αν εξωτερικά πολυμέσα αντιγράφονται στο Moodle ή όχι. Αν αυτό είναι απενεργοποιημένο τότε τα πολυμέσα αντιγράφονται πάντα στο Moodle (αυτό είναι συνήθως καλύτερο για τη συνολική ακεραιότητα και ασφάλεια των δεδομένων). Αν αυτό είναι ενεργοποιημένο τότε οι χρήστες μπορούν να επιλέξουν κάθε φορά που προσθέτουν πολυμέσα μέσα σε κείμενο.';
$string['configcacheexpire'] = 'Ο χρόνος (σε δευτερόλεπτα) για τον οποίο οι λίστες αρχείων αποθηκεύονται σε κρυφή μνήμη τοπικά κατά την περιήγηση σε εξωτερικούς χώρους αποθήκευσης.';
$string['configgetfiletimeout'] = 'Λήξη χρόνου σε δευτερόλεπτα για λήψη ενός εξωτερικού αρχείου στο Moodle.';
$string['configsaved'] = 'Οι ρυθμίσεις αποθηκεύτηκαν!';
$string['configsyncfiletimeout'] = 'Χρονικό όριο σε δευτερόλεπτα για συγχρονισμό του μεγέθους του εξωτερικού αρχείου.';
$string['configsyncimagetimeout'] = 'Χρονικό όριο σε δευτερόλεπτα για λήψη ενός αρχείου εικόνας από εξωτερικό αποθετήριο κατά το συγχρονισμό.';
$string['confirmdelete'] = 'Είστε σίγουροι ότι θέλετε να διαγράψετε το αποθετήριο {$a}; Αν επιλέξετε «Συνέχεια και λήψη», θα γίνει λήψη από το Moodle αναφορών σε αρχεία για εξωτερικό περιεχόμενο . Μπορεί να χρειαστεί αρκετή ώρα για την επεξεργασία.';
$string['confirmdeletefile'] = 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το αρχείο;';
$string['confirmdeletefilewithhref'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το αρχείο; Υπάρχουν {$a} σύνδεσμοι προς αυτό το αρχείο. Εάν προχωρήσετε, τότε τυχόν τοποθεσίες με συνδέσμους, αυτή τη στιγμή, προς το αρχείο θα ενημερωθούν αυτόματα για να χρησιμοποιούν αντί αυτού ένα αντίγραφο του αρχείου.';
$string['confirmdeletefolder'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτόν τον φάκελο; Όλα τα αρχεία και οι υποφάκελοι θα διαγραφούν.';
$string['confirmdeleteselectedfile'] = 'Είστε βέβαιοι ότι θέλετε να διαγράψετε τα επιλεγμένα {$a} αρχεία;';
$string['confirmremove'] = 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτό το πρόσθετο αποθετηρίου, τις επιλογές του και <strong>όλα τα στιγμιότυπά του</strong> - {$a}; Αν επιλέξετε «Συνέχεια και λήψη», θα γίνει λήψη στο Moodle των αναφορών αρχείων σε εξωτερικά περιεχόμενα. Αυτό θα μπορούσε να πάρει πολύ χρόνο για επεξεργασία.';
$string['confirmrenamefile'] = 'Είστε βέβαιοι ότι θέλετε να μετονομάσετε/μετακινήσετε αυτό το αρχείο;';
$string['confirmrenamefolder'] = 'Σίγουρα θέλετε να μετακινήσετε/μετονομάσετε αυτό το φάκελο; Οποιεσδήποτε τοποθεσίες με συνδέσμους, αυτή τη στιγμή, προς αρχεία αυτού του φακέλου θα ενημερωθούν αυτόματα ώστε να χρησιμοποιούν αντί αυτών αντίγραφα των αρχείων.';
$string['continueuninstall'] = 'Συνέχεια';
$string['continueuninstallanddownload'] = 'Συνέχεια και λήψη';
$string['copying'] = 'Αντιγραφή';
$string['coursebackup'] = 'Αντίγραφα ασφαλείας μαθήματος';
$string['create'] = 'Δημιουργία';
$string['createfolder'] = 'Δημιουργία φακέλου';
$string['createfolderfail'] = 'Αποτυχία δημιουργίας αυτού του φακέλου';
$string['createfoldersuccess'] = 'Επιτυχής δημιουργία φακέλου';
$string['createinstance'] = 'Δημιουργία ενός στιγμιότυπου αποθετηρίου';
$string['createrepository'] = 'Δημιουργία ενός στιγμιότυπου αποθετηρίου';
$string['createxxinstance'] = 'Δημιουργία στιγμιότυπου «{$a}»';
$string['date'] = 'Ημερομηνία';
$string['datecreated'] = 'Δημιουργήθηκε';
$string['deleted'] = 'Το αποθετήριο διαγράφηκε';
$string['deleterepository'] = 'Διαγραφή αυτού του αποθετηρίου';
$string['detailview'] = 'Εμφάνιση λεπτομερειών';
$string['dimensions'] = 'Διαστάσεις';
$string['disabled'] = 'Απενεργοποιημένο';
$string['displayasdetails'] = 'Εμφάνιση ως λεπτομέρειες αρχείου';
$string['displayasicons'] = 'Εμφάνιση ως εικονίδια αρχείων';
$string['displayastree'] = 'Εμφάνιση ως δέντρο αρχείων';
$string['displaydetails'] = 'Εμφάνιση φακέλου με λεπτομέρειες αρχείου';
$string['displayicons'] = 'Εμφάνιση φακέλου με εικονίδια αρχείων';
$string['displaytree'] = 'Εμφάνιση φακέλου ως δέντρο αρχείων';
$string['download'] = 'Λήψη';
$string['downloadallfiles'] = 'Λήψη όλων των αρχείων';
$string['downloadfolder'] = 'Λήψη όλων';
$string['downloadsucc'] = 'Το αρχείο μεταφορτώθηκε με επιτυχία';
$string['draftareanofiles'] = 'Δεν είναι δυνατή η λήψη επειδή δεν υπάρχουν συνημμένα αρχεία';
$string['editrepositoryinstance'] = 'Επεξεργασία στιγμιότυπου αποθετηρίου';
$string['emptylist'] = 'Κενή λίστα';
$string['emptytype'] = 'Αποτυχία δημιουργίας τύπου αποθετηρίου: το όνομα του τύπου είναι κενό';
$string['enablecourseinstances'] = 'Επιτρέψτε στους χρήστες να προσθέτουν ένα στιγμιότυπο αποθετηρίου στο μάθημα';
$string['enableuserinstances'] = 'Επιτρέψτε στους χρήστες να προσθέτουν ένα στιγμιότυπο αποθετηρίου στο πλαίσιο χρήστη';
$string['enter'] = 'Εισαγωγή';
$string['entername'] = 'Παρακαλούμε εισάγετε όνομα φακέλου';
$string['enternewname'] = 'Παρακαλούμε, εισαγάγετε το νέο όνομα αρχείου';
$string['error'] = 'Συνέβη ένα άγνωστο σφάλμα!';
$string['errordoublereference'] = 'Δεν είναι δυνατή η αντικατάσταση αρχείου με ένα σύνδεσμο, επειδή υπάρχουν ήδη σύνδεσμοι σε αυτό το αρχείο.';
$string['errornotyourfile'] = 'Μπορείτε να επιλέξετε μόνο αρχεία τα οποία προσθέσατε εσείς.';
$string['errorpostmaxsize'] = 'Το αρχείο που προσπαθήσατε να ανεβάσετε είναι πολύ μεγάλο για να το επεξεργαστεί ο εξυπηρετητής.';
$string['erroruniquename'] = 'Το όνομα στιγμιότυπου αποθετηρίου πρέπει να είναι μοναδικό';
$string['errorwhilecommunicatingwith'] = 'Σφάλμα κατά την επικοινωνία με το αποθετήριο «{$a}».';
$string['errorwhiledownload'] = 'Παρουσιάστηκε σφάλμα κατά τη λήψη του αρχείου: {$a}';
$string['existingrepository'] = 'Αυτό το αποθετήριο υπάρχει ήδη';
$string['federatedsearch'] = 'Ταυτόχρονη αναζήτηση σε πολλές πηγές';
$string['fileexists'] = 'Το όνομα αρχείου χρησιμοποιείται ήδη. Παρακαλούμε, χρησιμοποιήστε ένα άλλο όνομα.';
$string['fileexistsdialog_editor'] = 'Ένα αρχείο με αυτό το όνομα έχει ήδη επισυναφθεί στο κείμενο που επεξεργάζεστε.';
$string['fileexistsdialog_filemanager'] = 'Ένα αρχείο με αυτό το όνομα έχει ήδη επισυναφθεί';
$string['fileexistsdialogheader'] = 'Το αρχείο υπάρχει';
$string['filename'] = 'Όνομα αρχείου';
$string['filenotnull'] = 'Πρέπει να επιλέξετε ένα αρχείο για ανέβασμα.';
$string['filepicker'] = 'Επιλογέας αρχείου';
$string['filesaved'] = 'Το αρχείο αποθηκεύτηκε';
$string['filesizenull'] = 'Το μέγεθος αρχείου δεν μπορεί να καθοριστεί';
$string['folderexists'] = 'Το όνομα φακέλου χρησιμοποιείται ήδη. Παρακαλούμε, χρησιμοποιήστε ένα άλλο όνομα.';
$string['foldernotfound'] = 'Αδυναμία εύρεσης φακέλου';
$string['folderrecurse'] = 'Ένας φάκελος δεν μπορεί να μετακινηθεί σε δικό του υποφάκελο.';
$string['getfile'] = 'Επιλογή αυτού του αρχείου';
$string['getfiletimeout'] = 'Λήψη χρονικού ορίου αρχείου';
$string['help'] = 'Βοήθεια';
$string['iconview'] = 'Εμφάνιση ως εικονίδια';
$string['imagesize'] = '{$a->width} x {$a->height} px';
$string['instance'] = 'στιγμιότυπο';
$string['instancedeleted'] = 'Το στιγμιότυπο διαγράφηκε';
$string['instances'] = 'Στιγμιότυπα αποθετηρίου';
$string['instancesforcourses'] = '{$a} Κοινά στιγμιότυπα(ο) σε όλο το μάθημα';
$string['instancesforsite'] = '{$a} Κοινά στιγμιότυπα(ο) σε όλον τον ιστότοπο';
$string['instancesforusers'] = '{$a} Ιδιωτικά στιγμιότυπα(ο) χρηστών';
$string['invalidfiletype'] = 'Ο τύπος αρχείου {$a} δεν μπορεί να γίνει αποδεκτός.';
$string['invalidjson'] = 'Μη έγκυρη συμβολοσειρά JSON';
$string['invalidparams'] = 'Μη έγκυρες παράμετροι';
$string['invalidplugin'] = 'Μη έγκυρο πρόσθετο για το αποθετήριο «{$a}»';
$string['invalidrepositoryid'] = 'Μη έγκυρο αναγνωριστικό αποθετηρίου';
$string['isactive'] = 'Ενεργό;';
$string['keyword'] = 'Λέξη κλειδί';
$string['lastmodified'] = 'Τελευταία τροποποίηση';
$string['license'] = 'Άδεια χρήσης';
$string['linkexternal'] = 'Σύνδεση εξωτερικά';
$string['listview'] = 'Εμφάνιση ως λίστα';
$string['loading'] = 'Φόρτωση...';
$string['login'] = 'Σύνδεση στον λογαριασμό σας';
$string['logintoaccount'] = 'Συνδεθείτε στον λογαριασμό σας {$a}';
$string['logout'] = 'Έξοδος';
$string['lostsource'] = 'Σφάλμα. Η προέλευση λείπει. {$a}';
$string['makefilecontrolledlink'] = 'Δημιουργία ενός συνδέσμου στο αρχείο με έλεγχο πρόσβασης';
$string['makefileinternal'] = 'Δημιουργία ενός αντιγράφου του αρχείου';
$string['makefilelink'] = 'Σύνδεσμος προς το εξωτερικό αρχείο';
$string['makefilereference'] = 'Σύνδεσμος προς το αρχείο';
$string['manage'] = 'Διαχείριση αποθετηρίων';
$string['manageinstances'] = 'Διαχείριση στιγμιότυπων';
$string['manageurl'] = 'Διαχείριση';
$string['manageuserrepository'] = 'Διαχείριση μεμονωμένου αποθετηρίου χρήστη';
$string['missingsourcekey'] = 'Το κλειδί προέλευσης λείπει. Αυτό το κλειδί πρέπει επίσης να παρέχεται για την ανάκτηση του αρχείου.';
$string['moving'] = 'Μετακίνηση';
$string['name'] = 'Όνομα';
$string['newfolder'] = 'Νέος φάκελος';
$string['newfoldername'] = 'Όνομα νέου φακέλου';
$string['noenter'] = 'Δεν εισήχθη τίποτα';
$string['nofilesattached'] = 'Δεν υπάρχουν συνημμένα αρχεία';
$string['nofilesavailable'] = 'Δεν υπάρχουν διαθέσιμα αρχεία';
$string['nofilesselected'] = 'Δεν επιλέχθηκαν αρχεία';
$string['nolicenses'] = 'Δεν υπάρχουν διαθέσιμες άδειες';
$string['nomorefiles'] = 'Δεν επιτρέπονται άλλα συνημμένα';
$string['nopathselected'] = 'Δεν επιλέχθηκε ακόμη μονοπάτι προορισμού (κάντε διπλό κλικ σε ένα κόμβο του δέντρου για να επιλέξετε)';
$string['nopermissiontoaccess'] = 'Χωρίς δικαίωμα πρόσβασης σε αυτό το αποθετήριο';
$string['norepositoriesavailable'] = 'Λυπούμαστε, κανένα από τα τρέχοντα αποθετήρια δεν μπορεί να επιστρέψει αρχεία με τον απαιτούμενο μορφότυπο.';
$string['norepositoriesexternalavailable'] = 'Λυπούμαστε, κανένα από τα τρέχοντα αποθετήρια δεν μπορεί να επιστρέψει εξωτερικά αρχεία.';
$string['noresult'] = 'Χωρίς αποτέλεσμα αναζήτησης';
$string['notyourinstances'] = 'Δεν μπορείτε να δείτε/επεξεργαστείτε στιγμιότυπα αποθετηρίου άλλου χρήστη';
$string['off'] = 'Ενεργοποιημένο αλλά κρυφό';
$string['on'] = 'Ενεργοποιημένο και ορατό';
$string['openpicker'] = 'Επιλέξτε ένα αρχείο...';
$string['operation'] = 'Λειτουργία';
$string['original'] = 'Πρωτότυπο';
$string['originalextensionchange'] = 'Η αρχική επέκταση αρχείου έχει τροποποιηθεί ως μέρος της αλλαγής ονόματος αρχείου. Η αλλαγή της επέκτασης από «.{$a->originalextension}» σε «.{$a->newextension}» ενδέχεται να έχει ως αποτέλεσμα ένα αρχείο που δεν είναι δυνατό να ανοιχτεί.';
$string['originalextensionremove'] = 'Η αρχική επέκταση αρχείου αφαιρέθηκε ως μέρος της αλλαγής ονόματος αρχείου. Η αφαίρεση της επέκτασης «.{$a}» είναι πιθανό να έχει ως αποτέλεσμα ένα αρχείο που δεν είναι δυνατό να ανοιχτεί.';
$string['overwrite'] = 'Αντικατάσταση';
$string['overwriteall'] = 'Αντικατάσταση όλων';
$string['path'] = 'Μονοπάτι';
$string['plugin'] = 'Πρόσθετα αποθετηρίου';
$string['pluginerror'] = 'Σφάλματα σε πρόσθετο αποθετηρίου.';
$string['pluginname'] = 'Όνομα πρόσθετου αποθετηρίου';
$string['pluginnamehelp'] = 'Αν το αφήσετε κενό θα χρησιμοποιηθεί το προεπιλεγμένο όνομα.';
$string['popup'] = 'Κλικ στο πλήκτρο «Σύνδεση» για σύνδεση/είσοδο';
$string['popupblockeddownload'] = 'Το παράθυρο λήψης είναι μπλοκαρισμένο. Παρακαλούμε επιτρέψτε το αναδυόμενο παράθυρο και δοκιμάστε ξανά.';
$string['preview'] = 'Προεπισκόπηση';
$string['privacy:metadata:repository'] = 'Το στοιχείο λογισμικού Αποθετηρίου αποθηκεύει τους τύπους αποθετηρίου στο βασικό υποσύστημα.';
$string['privacy:metadata:repository_instances'] = 'Το στοιχείο λογισμικού των πρόσθετων Αποθετηρίου αποθηκεύει δεδομένα στιγμιότυπων αποθετηρίου χρηστών μέσα στο υποσύστημα πυρήνα.';
$string['privacy:metadata:repository_instances:name'] = 'Το προσαρμοσμένο όνομα του στιγμιότυπου αποθετηρίου.';
$string['privacy:metadata:repository_instances:password'] = 'Ο προαιρετικός κωδικός πρόσβασης έχει ρυθμιστεί για το στιγμιότυπο αποθετηρίου.';
$string['privacy:metadata:repository_instances:timecreated'] = 'Η ημερομηνία/ώρα της δημιουργίας για το στιγμιότυπο αποθετηρίου.';
$string['privacy:metadata:repository_instances:timemodified'] = 'Η ημερομηνία/ώρα τροποποίησης για το στιγμιότυπο αποθετηρίου.';
$string['privacy:metadata:repository_instances:typeid'] = 'Ο τύπος αναγνωριστικού του στιγμιότυπου αποθετηρίου.';
$string['privacy:metadata:repository_instances:userid'] = 'Το αναγνωριστικό του χρήστη που είναι ιδιοκτήτης του στιγμιότυπου αποθετηρίου.';
$string['privacy:metadata:repository_instances:username'] = 'Το προαιρετικό όνομα χρήστη που έχει ρυθμιστεί για το στιγμιότυπο του αποθετηρίου.';
$string['privatefilesof'] = '{$a} Ιδιωτικά αρχεία';
$string['readonlyinstance'] = 'Δεν μπορείτε να τροποποιήσετε/διαγράψετε ένα στιγμιότυπο που είναι μόνο για ανάγνωση';
$string['referencesexist'] = 'Υπάρχουν {$a} σύνδεσμοι προς αυτό το αρχείο';
$string['referenceslist'] = 'Σύνδεσμοι';
$string['refresh'] = 'Ανανέωση';
$string['refreshnonjsfilepicker'] = 'Παρακαλούμε, κλείστε αυτό το παράθυρο και ανανεώστε τον επιλογέα αρχείων χωρίς javascript';
$string['removed'] = 'Το αποθετήριο διαγράφηκε';
$string['renameall'] = 'Μετονομασία όλων';
$string['renameto'] = 'Μετονομασία σε «{$a}»';
$string['repositories'] = 'Αποθετήρια';
$string['repository'] = 'Αποθετήριο';
$string['repositorycourse'] = 'Αποθετήρια μαθήματος';
$string['repositoryerror'] = 'Το απομακρυσμένο αποθετήριο επέστρεψε σφάλμα: {$a}';
$string['repositoryicon'] = 'Εικονίδιο αποθετηρίου';
$string['save'] = 'Αποθήκευση';
$string['saveas'] = 'Αποθήκευση ως';
$string['saved'] = 'Αποθηκεύτηκε';
$string['saving'] = 'Αποθήκευση';
$string['search'] = 'Αναζήτηση';
$string['searching'] = 'Αναζήτηση σε';
$string['searchrepo'] = 'Αναζήτηση στο αποθετήριο';
$string['sectionbackup'] = 'Αντίγραφα ασφαλείας τμήματος';
$string['select'] = 'Επιλογή';
$string['setmainfile'] = 'Ορίστε κύριο αρχείο';
$string['setmainfile_help'] = 'Εάν υπάρχουν πολλά αρχεία στο φάκελο, το κύριο αρχείο είναι αυτό που εμφανίζεται στη σελίδα προβολής. Άλλα αρχεία, όπως εικόνες ή βίντεο, μπορούν να ενσωματωθούν σε αυτό. Στο διαχειριστή αρχείων, το κύριο αρχείο υποδεικνύεται με έναν τίτλο με έντονους χαρακτήρες.';
$string['settings'] = 'Ρυθμίσεις';
$string['setupdefaultplugins'] = 'Ρυθμίζονται τα προεπιλεγμένα πρόσθετα αποθετηρίων';
$string['siteinstances'] = 'Στιγμιότυπα αποθετηρίων του ιστοτόπου';
$string['size'] = 'Μέγεθος';
$string['sourcekeymismatch'] = 'Η διεύθυνση URL προέλευσης δεν ταιριάζει με το κλειδί προέλευσης.';
$string['submit'] = 'Υποβολή';
$string['sync'] = 'Συγχρονισμός';
$string['syncfiletimeout'] = 'Τέλος χρόνου συγχρονισμού αρχείου';
$string['syncimagetimeout'] = 'Τέλος χρόνου συγχρονισμού εικόνας';
$string['thumbview'] = 'Εμφάνιση ως εικονίδια';
$string['title'] = 'Επιλέξτε ένα αρχείο...';
$string['type'] = 'Τύπος';
$string['typenotvisible'] = 'Τύπος μη ορατός';
$string['undisclosedreference'] = '(Μυστικός)';
$string['undisclosedsource'] = '(Μυστικός)';
$string['unknownoriginal'] = 'Άγνωστος';
$string['unknownsource'] = 'Άγνωστη προέλευση';
$string['unzipped'] = 'Αποσυμπίεση με επιτυχία';
$string['upload'] = 'Ανέβασμα αυτού του αρχείου';
$string['uploading'] = 'Ανέβασμα...';
$string['uploadsucc'] = 'Το αρχείο ανέβηκε με επιτυχία';
$string['uselatestfile'] = 'Χρήση του τελευταίου αρχείου';
$string['usenonjsfilemanager'] = 'Άνοιγμα της διαχείρισης αρχείων σε νέο παράθυρο';
$string['usenonjsfilepicker'] = 'Ανοίξτε τον επιλογέα αρχείων σε νέο παράθυρο';
$string['usercontextrepositorydisabled'] = 'Δεν επιτρέπεται επεξεργασία αυτού του αποθετηρίου στο πλαίσιο χρήστη';
$string['wrongcontext'] = 'Δεν έχετε πρόσβαση σε αυτό το πλαίσιο';
$string['xhtmlerror'] = 'Πιθανώς χρησιμοποιείτε μια αυστηρή κεφαλίδα XHTML. Κάποια στοιχεία λογισμικού YUI δεν λειτουργούν σε αυτή την κατάσταση λειτουργίας· παρακαλούμε απενεργοποιήστε τη.';
$string['ziped'] = 'Συμπιέστε επιτυχώς τον φάκελο';
